- backend/libbackend/webserver.ml
This mostly motivated by reducing the segment bill.
> When reporting to segment, use the canvas name instead of the IP

- client/src/api/APIError.ml
- client/test/api_error_test.ml
- client/test/unittests.ml
Fixes #2538
The solution proposed was to change `APIError.msg` function to stop returning the error context for some errors (in this case `Http.BadStatus` when code is 502).
I also created a test file for the `APIError` file and added 2 tests to it. One that tests the new behavior for the error 502 and another for `Http.NetworkError` to verify that the behavior of other error messages is preserved.
Screenshot before the change:
Screenshot after the change:
> Change error message for 502 (AddOps)

- docs/mfa.md
What's done:
- if someone sends you an email inviting you to enroll in MFA, you can
enroll
- if you have enrolled, you will be prompted on every login for MFA
- if you have not enrolled, you will not be prompted for MFA, login
works as it always has
What's not done:
- no way to enroll people in MFA without a manual step by us (though it
is at least easy)
- we could automate this - there is an API, we could add a button to our
UI that says "yes please turn on MFA for me"
See details in docs/mfa.md
> MFA is now on, sort of - here's a PR documenting that

- backend/libbackend/sql_compiler.ml
- backend/test/test_db_libs.ml
Done as part of initiative to expand query compiler. #2424 
I've added Date::hour_v1 to the unary_op_to_sql function, mapping the Dark function to respective Postgres function (date_part('hour', ...).
This will allow the Db::query family of functions to compile the aforementioned Date::hour_v1 function successfully when applied to DB record date values.
I had to add the ability to pass the Dark unary op argument (in this case a Date) as the last argument as opposed to the first where it is evaluated in lambda_to_sql. This probably isn't the most elegant solution and likely this will need to become even more sophisticated later on for unary Dark ops that translate to postgres functions with more than 2 args.
Closes #2616
> support Date::hour_v1 in query compiler and allow appending of Dark arg in unary_ops

- backend/libbackend/httpclient.ml
We had an operational incident today because we didn't have a timeout for Curl. As a result, requests to a bad server waited 5m, which took up all the queue servers.
Set a timeout to 30s. We could probably go lower, but might want to alert customers if we do.
> Add a timeout for HTTPClient:: calls

- .circleci/config.yml
This was needed for forking private repos. Not needed now that everything is public
> Don't use a special checkout

- docs/editor-setup.md
The editor-setup doc instructions on integrating merlin is missing information if the contributor is using vim or neovim.
I added that information to the doc
> Add info about needing python for vim+merlin integration

- backend/libbackend/sql_compiler.ml
- backend/test/test_db_libs.ml
Done as part of initiative to expand query compiler. #2424 
I've added String::replaceAll to the lambda_to_sql function, mapping to the postgres function "replace", and wrote a test to verify it works
This will allow the Db::query family of functions to compile the aforementioned String::replaceAll function successfully when applied to DB record values.
I think likely there should be another function to contain the logic of functions with 3 arguments (like unary and binop functions) but for now I just really want the functionality. We've also discussed evolving where the logic for each function is stored, but I'm still just focusing on expanding support within the existing infrastructure (what I'm capable of right now).
Closes #2691
> Add String::replaceAll to sql compiler

- config/dev
- scripts/support/kubernetes/garbagecollector/garbagecollector-deployment.yaml.template
I disabled the garbage collection process while determining the cause of the DB CPU spikes (it was an export on the replica, oddly). This reenables it. I'll keep an eye on the outcome of the GC for the next few days.
> Reenable gc

- backend/libbackend/webserver.ml
- backend/templates/ui.html
- client/src/appsupport.js
- scripts/bsb-wrapper.sh
- scripts/clear-node-modules
All dark tabs say "darklang - Dark", which is confusing when you have multiple canvases open.
Show the canvas name instead: "canvasname - Dark"
> Show canvas name

- client/src/fluid/Fluid.ml
- client/src/fluid/FluidEditorView.ml
Adding `fluid-error` for duplicated record filed name, to fix #2686 
Checking record filed names to see duplicated tokens, and add `fluid-error` to them.
> Add checking duplicated record filed name in fluid editor

- client/src/canvas/ViewSidebar.ml
- client/styles/_sidebar.scss
We used to show unused functions in a different color in the sidebar. I don't know where it went but it was really useful.
A css tag based on the `uses` field, which was still there.
Manually tested
> Show unused functions using a darker grey

- client/styles/_fluid.scss
Change `playbutton` z-index to `100` to be lower than `dropdown`.
Fixes #2676 
Change `z-index`, since these elements are not siblings and positioned `absolute`.
> Fix playbutton z-index with dropdown

- client/test/fluid_expression_test.ml
- libshared/FluidExpression.ml
Allow to update variable name even it has been rebounded, to fix #2712 
Currently, it is not allow to rename rebounded variable. Enable this might lead to other unexpected behaviour, eg if new variable name is same for other variable than rebounded variable name, then all referenced places will be marked as updated variable.
The original implementation seems disable rename rebounded variable intentionally, is to enable it has been well thought about in this case?
> Allow update rebounded variable name

- client/src/app/Main.ml
Replace start and end quotes for live value copy, to fix #2684 
Replace start and end quotes for live value through `copy-value` button.
> Replace start and end quotes for live value copy text

- client/src/fluid/Fluid.ml
- client/test/fluid_clipboard_test.ml
Put caret at the end of text if paste in front of open quote, to fix #2675 
> Move caret to text of end when paste in front of open quote

- backend/test/test_other_libs.ml
Tests were missing for the standard library function List::contains.
To add the missing tests.
Three tests were added:
(1) Testing on a list containing the value queried.
(4) Testing on a list NOT containing the value queried.
(3) Testing on an empty list.
> Add stdlib tests for List::contains

- .circleci/config.yml
AWS doesn't like IAM keys being exposed, and they're threatening to close our AWS account as a result. So switch to using dockerhub instead of ECR.
> Pull from docker hub instead

- backend/libexecution/liblist.ml
- backend/test/test_other_libs.ml
Issue #2466: Standard library lacks a list interpose/join function.
To add List::interpose to the stdlib, along with the required tests.
List::interpose tests completed successfully.
> Add List::interpose to the stdlib

- client/src/fluid/Fluid.ml
- client/test/fluid_test.ml
Original bug caused by using old parameter `index` as new parameter `index` for aligned parameters. This PR is to fix #2682 
Using `compareParams` to check two different parameters matched case `Aligned` and `TypeAndPositionMatched` to keep parameter.
> Fix parameter positions after function rename

- backend/libexecution/liblist.ml
- backend/test/test_other_libs.ml
Adds List::interleave to the standard library. #2465 
I tried multiple different takes on the description and settled with this very verbose one as a starting point.  I failed to find any example descriptions from other standard libraries to work from.
The "List::interleave works (mixed types)" test probably isn't necessary as it's kind of a given I think, I just wanted to verify it worked as I expected.  Let me know if you want it removed.
> Add List::interleave to the standard library

- scripts/gcp-proxy-db
- scripts/gcp-psql
I noticed I accidentally connected to the wrong DB via the SQL proxies (if a connection was already established, it would use that instead of the one I was connecting to).
> Make it harder to connect to the wrong DB

- postgres-honeytail/Dockerfile
- postgres-honeytail/cmd/cloudsqltail/main.go
- postgres-honeytail/run.sh
We weren't getting any events in honeycomb about our DB. This was because google changed the logging format on the last minor update. This fixes the logging format.
Testing: I have this working locally using the production value, and I can confirm the data is going into honeycomb, which it was not doing before.
> Fix honeytail

- scripts/support/kubernetes/builtwithdark/bwd-deployment.template.yaml
- scripts/support/kubernetes/builtwithdark/bwd-ingress.yaml
- scripts/support/kubernetes/builtwithdark/bwd-network-policy.yaml
- scripts/support/kubernetes/builtwithdark/darklang-ingress.yaml
- scripts/support/kubernetes/builtwithdark/editor-deployment.template.yaml
- scripts/support/kubernetes/builtwithdark/editor-network-policy.yaml
- scripts/support/kubernetes/builtwithdark/honeycomb.yaml
- scripts/support/kubernetes/certs/cert-manager.yaml
- scripts/support/kubernetes/certs/darkcustomdomain-ingress.yaml
- scripts/support/kubernetes/certs/nginx-ingress-controller.yaml
- scripts/support/kubernetes/cronchecker/cc-network-policy.yaml
- scripts/support/kubernetes/cronchecker/cron-deployment.template.yaml
- scripts/support/kubernetes/garbagecollector/garbagecollector-deployment.template.yaml
- scripts/support/kubernetes/honeycomb-heapster.yaml
- scripts/support/kubernetes/postgres-honeytail-deployment.template.yaml
- scripts/support/kubernetes/queueworker/qw-deployment.template.yaml
- scripts/support/kubernetes/queueworker/qw-network-policy.yaml
- scripts/support/kubernetes/queueworker/scheduler-deployment.template.yaml
- scripts/support/kubernetes/tunnel/isolate-tunnel.yaml
- scripts/support/kubernetes/tunnel/tunnel-deployment.template.yaml
- scripts/support/yamllinter
Production is now k8s 1.16, but the deployment files were not updated. This led to this failure: https://app.circleci.com/pipelines/github/darklang/dark/420/workflows/9e2ba329-dc41-4746-9e66-ea2877d94437/jobs/3749
This update all the k8s files to 1.16 using the https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/ and an updated kubeval
> Fix deploy

- scripts/support/kubernetes/queueworker/qw-deployment.template.yaml
When we switch to 30, the queue gets overrun. This is part of the fix after the
outage at the weekend
> Double the capacity of the queue

- backend/libbackend/event_queue.ml
- backend/libbackend/event_queue.mli
- backend/libbackend/queue_worker.ml
- backend/test/test_event_queue.ml
We spend about 39 hours of time every day dequeuing and reenqueuing events that do nothing. Instead, let's delete those events once they become a week old.
> Don't put_back events that are over a week old and have no handler

- backend/libbackend/queue_worker.ml
When you don't do anything after a dequeue, it stays scheduled and something else will pick it up after. The actual thing I want to do so that events stop being processed is to "finish" it.
> Actually stop processing

- fsharp-backend/src/LibExecution/Interpreter.fs
- scripts/support/compile
This switches to a less performant but more correct F# task implementation
Still faster than wrapping everything in a task, but slower (probably due to
more allocations) than what was the before. However, with the DTask version,
there was no type safety. Everything could be a task and you could have lists of
tasks. Rather, we'd like to get a proper dval out the back of it, and then be
able to do things to it.
> Resolve tasks

- backend/libbackend/account.ml
- backend/libbackend/analysis.ml
- backend/libbackend/garbage_collection.ml
- backend/libbackend/stored_event.ml
- backend/libbackend/stored_event.mli
- backend/libbackend/stored_function_result.ml
- backend/libbackend/stored_function_result.mli
The garbage collection didn't work for function results, and had performance issues so had to be disabled. This makes it work with a different algorithm (find valid traces in the app then delete others in small chunk; previously it tried to figure out invalid traces during the query).
Right now the DB is 1.4TB, this should drop it to 200GB of actual data (barring fragmentation).
> Fix trace garbage collection for function results

- backend/libbackend/stored_function_result.ml
Operationally, it seems that massive canvases slow down the GC massively. Let's skip them for now.
> GC followup

- backend/bin/garbage_collector_worker.ml
It seems the cost is the read, not the delete, so this might not cause any
problems. Will be watching as it goes out.
> Try deleting twice as many things

- client/src/fluid/Fluid.ml
- client/test/fluid_test.ml
Suppose you have
```
let x = 5
let _ = let y = 6
___
7
```
You probably got here by pasting and hoping for the best. This allows you to
clean it up by deleting the `let _`, giving you
```
let x = 5
let y = 6
7
```
> Allow backspacing a let containing another let:

- .circleci/config.yml
- client/src/fluid/Fluid.ml
- client/test/fluid_test.ml
Previously, it wrapped the string.
> When pressing "[" in a string, enter it in the string

- fsharp-backend/tests/Tests/FSharpToExpr.fs
- fsharp-backend/tests/testfiles/int.tests
- fsharp-backend/tests/testfiles/language.tests
When we tried to test functions with large numbers, they weren't working.
It looks like the F# parser treats long integers as 0 instead of bigint. The documentation said that the "I" suffix allowed for bigint literals (eg `9999999999999999999I`). However, it still needed explicit test parser support.
Added tests for Int.mod_v0 and for matching.
> Add support for bigints in test files (use the "I" suffix)

- fsharp-backend/src/LibExecution/StdLib/LibBytes.fs
- fsharp-backend/tests/testfiles/bytes.tests
Libbytes.fs functions implementation.
Functions translated 
Functions implemented and unit test included.
Test cases are working as the old Ocaml version does.
Revert changes
> Libbytes.fs

- client/src/fluid/Fluid.ml
- client/src/fluid/FluidToken.ml
- client/test/fluid_test.ml
Elements within a list are not currently pipeable. The main problem is that when the cursor is at the end of a variable within a list (and nothing is selected), createPipe (in Fluid.ml) is given the id of the list and no other context to know if the cursor is inside the list or outside. The logic simply assumes that if nothing is selected it should find the top most element and pipe from there. 
Add a list of pipeable Fluid Tokens to check if the element being piped from is pipeable. So when nothing is selected the token to the left is checked and if it is pipeable a pipe is created from it.
With no token selected and pressing shift-enter:
Current behaviour:
New behaviour:
Three new tests have been added and two have been …
> Issue #2863

- backend/bin/libserialization.ml
- backend/libserialize/serialization_stubs.c
- fsharp-backend/src/LibBackend/File.fs
- fsharp-backend/src/LibBackend/OCamlInterop.fs
- fsharp-backend/src/LibExecution/DvalRepr.fs
- fsharp-backend/src/LibExecution/Interpreter.fs
- fsharp-backend/src/LibExecution/RuntimeTypes.fs
- fsharp-backend/src/Prelude/Prelude.fs
- fsharp-backend/tests/FuzzTests/FuzzTests.fs
- fsharp-backend/tests/TestUtils/TestUtils.fs
- fsharp-backend/tests/Tests/DvalRepr.Tests.fs
- fsharp-backend/tests/Tests/OCamlInterop.Tests.fs
- fsharp-backend/tests/Tests/ProgramTypes.Tests.fs
- scripts/dotnet-fsi
- scripts/support/dotnet-regen-fsi
- scripts/support/fsi-setup.fsx
This significantly improves most of the DvalRepr functions by fuzzing them, handling edge cases, adding them as tests, etc.
Funcrtions I know believe to be perfect:
- {to,of}InternalRoundtrippableV0 - 
- {to,of}InternalQueryableV0
- toDeveloperRepr
- toPrettyMachineJson
- toEnduserReadable
Also does:
- significantly improves error handling and display in serialization_stubs (used for OCaml interop)
- improves the dotnet-fsi script
- add lots of float tests
- removes some static methods of Dval that did nothing useful
> DvalRepr functions

- fsharp-backend/src/LibExecution/StdLib/LibNoModule.fs
- fsharp-backend/tests/testfiles/twitter.tests
This PR ports over the Twitter::urlencode function from OCaml to F#. 
The main change is removing the use of the previous OCaml unicode library, and use the built in `Uri.EscapeDataString` method from .NET. 
The existing twitter.tests unit test passes, I also tested it out against the [examples on the Twitter documentation](https://developer.twitter.com/en/docs/authentication/oauth-1-0a/percent-encoding-parameters) and the output was correct.
> Port Twitter::urlencode function

- fsharp-backend/src/LibExecution/StdLib/LibNoModule.fs
- fsharp-backend/tests/testfiles/aws.tests
Porting AWS::urlencode  to F#
Duplicate the behavior of the OCaml implementation, including some potential bugs.
Added aws.tests, including some tests showing that the potential bug in the OCaml implementation is also in the F# version
> Port AWS::urlencode to F#

- fsharp-backend/src/LibExecution/StdLib/LibList.fs
- fsharp-backend/tests/testfiles/list.tests
Porting stdlib List functions to F# backend
Ported `List::repeat_v0`, `List::drop_v0` and `List::flatten_v0`
`List::repeat_v0` raised an interesting choice: since Dark ints are now infinite precision, should we allow functions like this to create truly massive lists or should we just expose some sort of limit (the most obvious being F#'s own limit of Int32). 
I chose the latter option because materializing extremely large lists is a very good way to undermine the stability of a shared runtime. 
I noticed other list functions have similar problems (eg. `List::take`, which I ran out of time to finish, has no efficient way to take more than `Int32.MaxValue` items), which suggests to me that a lazy list implementation might be a better pairing with infinite precision integers.
Added test …
> Port More List functions

- backend/libexecution/libjson.ml
- fsharp-backend/src/ApiServer/Functions.fs
- fsharp-backend/src/LibBackend/OCamlInterop.fs
- fsharp-backend/src/LibExecution/DvalRepr.fs
This is a followup to #3072, to avoid the _v0 situation (we don't want to change the OCaml implementation at all, so we just have to marshal the data over there carefully).
> Lib-json followup

- .devcontainer/devcontainer.json
Fix some problems in the vscode. By having the build-server as a postAttachCommand, we run one build-server every time we reload vscode (which is a lot, because ionide is fickle). But we really only want one build-server to run because otherwise it will run multiple build jobs, and that will confuse dotnet, causing it to hang (and probably other side effects too).
So really, build-server needs to be a postStartCommand, and we can just show the output in the postAttachCommand.
Reference: https://code.visualstudio.com/docs/remote/devcontainerjson-reference#_lifecycle-scripts
> Don't run multiple build-servers in the devcontainer

- .devcontainer/devcontainer.json
- scripts/support/vscode-post-start-command
Unclear why nohup wasn't working, but it does now
> Make starting build-server in the vscode container work

- fsharp-backend/src/LibExecution/StdLib/LibDict.fs
- fsharp-backend/src/Prelude/Prelude.fs
- fsharp-backend/tests/testfiles/dict.tests
Continue with the migration of the functions written in OCaml to F#, in this case those of the LibDict.fs class. I added some functions to Prelude too to help
Functions previously in OCaml, migrated to F#
Tests passed and I added some aditional tests to try different results.
> LibDict functions migration to F#

- fsharp-backend/src/LibBackend/StdLib/LibDB2.fs
- fsharp-backend/tests/testfiles/db.tests
Continue with the migration of the functions written in OCaml to F#, in this case were missing only DB2::delete_v1 and DB2::deleteAll_v1 from LibDB2.
Functions previously in OCaml, migrated to F#
Tests passed and I added some aditional tests to try different results.
> LibDB2 functions migration

- fsharp-backend/src/LibExecution/StdLib/LibFloat.fs
- fsharp-backend/tests/testfiles/float.tests
Continue with the migration of the functions written in OCaml to F#, in this case it was only added Float::roundTowardsZero_v0 function to LibFloat
Functions previously in OCaml, migrated to F#
Tests I added for the function passed
> LibFloat migration

- fsharp-backend/src/LibExecution/StdLib/LibDate.fs
- fsharp-backend/tests/testfiles/date.tests
Continue with the migration of the functions written in OCaml to F#.
There were only one function left to migrate in `LibDate.fs`, `Date::toHumanReadable`
It is a function that has been deprecated because it doesn't work but I added some tests just in case we ever use it again.
> LibDate function migration

- fsharp-backend/src/LibExecution/StdLib/LibList.fs
- fsharp-backend/src/Prelude/Prelude.fs
- fsharp-backend/tests/testfiles/list.tests
Continue with the migration of the functions written in OCaml to F#.
Rewrite LibList.fs functions to F#. I also added a new function to Prelude (`List.filter_map`), to help with the code.
Tests passed and I added some more tests to check
> LibList functions migration

- fsharp-backend/src/Prelude/Prelude.fs
While working on the functions migration in `LibDict`, I needed to write a `fold_s` function to help with the code. So now I rewrite functions in Prelude to work with this new one.
Wrote `map_s`, `filter_s` and `filter_map` from Map module in `Prelude` using the new function `fold_s` to reuse code
I ran the tests again and they passed
> Prelude functions rewrited

- fsharp-backend/src/LibBackend/Routing.fs
- fsharp-backend/src/LibExecution/Errors.fs
- fsharp-backend/src/LibExecution/StdLib/LibList.fs
- fsharp-backend/src/Prelude/Prelude.fs
- fsharp-backend/tests/FuzzTests/FuzzTests.fs
- fsharp-backend/tests/testfiles/list.tests
List::sortByComparator_v0 needs to sort with a callback. However, the existing sorting algorithms in .NET (also true of OCaml) can't be made to use async. 
We need a sorting algorithm that is async aware. I copied an existing C# merge sort algorithm and ported it to F# and used TaskOrValue to make it async.
Merge sort is a good candidate as it is very predictable, and doesn't have bad worst-case complexity like other `O(n log n)` sorting algorithms. There are probably more performant options (like using insertion sort for small arrays) but this seems fine.
This could do with some fuzzing, actually.
None.
Yes
> Add List::sortByComparator

- scripts/push-assets-to-cdn
On GCP, I recently set the access control for the darklang-static-assets bucket to use "Uniform ACLs".
On a [recent deploy](https://app.circleci.com/pipelines/github/darklang/dark/1370/workflows/af460aa6-1dee-474f-900c-1d50605aa648/jobs/13366), there were HTTP 400 errors when pushing to the bucket:
```
BadRequestException: 400 Cannot insert legacy ACL for an object when uniform bucket-level access is enabled. Read more at https://cloud.google.com/storage/docs/uniform-bucket-level-access
```
It looks like we should just avoid setting them ACL, which is no longer necessary.
> Dont set an ACL that's no longer used

- fsharp-backend/src/LibBackend/StdLib/LibCrypto.fs
- fsharp-backend/tests/FuzzTests/FuzzTests.fs
We have a number of functions marked impure to match the OCaml versions. Some of them are fuzzable - mark them as such.
> Fuzz some impure functions too

- .devcontainer/devcontainer.json
When using VSCode with the Remote Containers extension, the extension
bootstraps a container using a default alpine container. The alpine
container does not have bash.
When executing the `initializeCommand` script, the build fails when
trying to call bash. I speculate that it is trying to call bash because
there's a string in initializeCommand, but that it wouldn't if there was
instead an array - which doesn't need a shell to sort out.
> Attempt to avoid bash during Remote Container bootstrap

- backend/liblegacy/fuzzing.ml
- fsharp-backend/src/ApiServer/Middleware.fs
- fsharp-backend/src/BwdServer/BwdServer.fs
- fsharp-backend/src/LibExecution/Execution.fs
- fsharp-backend/src/LibExecution/Interpreter.fs
- fsharp-backend/src/LibExecution/RuntimeTypes.fs
- fsharp-backend/src/LibService/Rollbar.fs
- fsharp-backend/src/Prelude/Prelude.fs
- fsharp-backend/tests/TestUtils/FSharpToExpr.fs
- fsharp-backend/tests/TestUtils/LibTest.fs
- fsharp-backend/tests/Tests/Execution.Tests.fs
- fsharp-backend/tests/testfiles/language.tests
- fsharp-backend/tests/testfiles/string.tests
Go through the remaining cases where the old and new interpreter differ and make sure they're tested and correct.
- Make the interpreter work the same, including supporting previews for:
- records
- feature flags
- Fix race conditions with side effect counter in tests
- Use `.[]` instead of .Add to add to collections to avoid exceptions
- Support an edge case in `if` with `DError`
- Support an edge case piping into errors
- Support more things in the parser
- Reorganize and expand language tests
- fix equality tests
> Match old interpreter

- CODING-GUIDE.md
- backend/bin/legacyserver.ml
- backend/liblegacy/serialization.ml
- backend/libserialize/binary_serialization.ml
- docs/benchmarking.md
- fsharp-backend/src/LibBackend/OCamlInterop.fs
- fsharp-backend/src/LibBackend/Serialize.fs
- fsharp-backend/src/LibExecution/OCamlTypes.fs
- fsharp-backend/tests/FuzzTests/FuzzTests.fs
- scripts/support/build-server
- scripts/support/compile
- scripts/support/compile-project
I need to compare the actual running time of the F# backend to the existing OCaml one, to ensure things at least stay the same.
The first step was to ensure the ocaml and f# were built with the optimization settings turned on.
Also adds an optimization where we only ask legacyserver to decode toplevels once per toplevel. This increases throughput by 20%.
> Optimize f# backend more

- fsharp-backend/src/ApiServer/Api/APIOps.fs
- fsharp-backend/src/ApiServer/Middleware.fs
- fsharp-backend/src/ApiServer/Ui.fs
- fsharp-backend/src/BwdServer/BwdServer.fs
- fsharp-backend/src/LibBackend/Config.fs
- fsharp-backend/src/LibBackend/LibBackend.fsproj
- fsharp-backend/src/LibBackend/Pusher.fs
- fsharp-backend/src/LibService/Config.fs
- fsharp-backend/src/LibService/HeapAnalytics.fs
- fsharp-backend/src/LibService/LibService.fsproj
- fsharp-backend/src/LibService/Rollbar.fs
- fsharp-backend/src/LibService/Telemetry.fs
- fsharp-backend/src/QueueWorker/QueueWorker.fs
- fsharp-backend/tests/Tests/EventQueue.Tests.fs
This started as an attempt to improve the performance of the Rollbar middleware, though it didn't improve the performance, it's better to use this as it doesn't add a thing that has known poor performance.
This also abstracts ExecutionID, using the current OpenTelemetry trace id as the execution id.
Also some slight refactoring of heap and rollbar.
> Cleanup Rollbar and ExecutionID

- containers/base-service-Dockerfile
- services/apiserver-deployment/apiserver-deployment.template.yaml
- services/bwd-deployment/bwd-deployment.template.yaml
- services/cron-deployment/cron-deployment.template.yaml
- services/editor-deployment/editor-deployment.template.yaml
- services/garbagecollector-deployment/garbagecollector-deployment.template.yaml
- services/qw-deployment/qw-deployment.template.yaml
- services/scheduler-deployment/scheduler-deployment.template.yaml
- services/tunnel-deployment/tunnel-deployment.template.yaml
Put quotes around yaml in the deploy templates, as sometimes k8s will think these strings are objects.
Also change ubuntu mirror to ec2 mirror to speed up deploys.
> Fix deploy templates

- .circleci/config.yml
- scripts/deployment/gke-deploy
- scripts/deployment/shipit
Hashes are missing during the deploy. This adds debugging and error checking.
Also fixes a few errors in gke-deploy, where I got the order wrong with testing for a manual deploy.
The I saw was that listing files from docker to put in the manifest didn't necessarily work right, so instead I took the results from when they were output while building or pulling containers.
> Fix missing hashes

- fsharp-backend/src/ApiServer/Api/APITraces.fs
- fsharp-backend/src/LibBackend/Traces.fs
- fsharp-backend/src/Tablecloth/TableclothList.fs
- fsharp-backend/tests/Tests/ApiServer.Tests.fs
- fsharp-backend/tests/testfiles/list.tests
The APIServer tests have been failing for a while (they're not run in CI). This makes them work again:
- Trim the HSTS server heading before comparing with the OCaml headers
- refactor APIserver tests to have the port handled automatically
- fix the sample header
Also added a bunch of tests for empty lists
> Fix APIServer tests

- containers/gcp-exechost/prep.sh
- fsharp-backend/src/ExecHost/ExecHost.fs
- scripts/production/connect-to-exec-host
I can connect to the execHost, but the executable doesn't work. Let's find out what's wrong.
> Get better warnings in ExecHost

- fsharp-backend/src/Wasm/static/BlazorWorker.js
It looks like blazor.boot.json was loaded without the hash. Let's try to fix that.
> Attempt to fix blazor in production

- fsharp-backend/src/ApiServer/Api/APIExecution.fs
- fsharp-backend/src/ApiServer/Middleware.fs
- fsharp-backend/src/BackendOnlyStdLib/LibDB2.fs
- fsharp-backend/src/BwdServer/Server.fs
- fsharp-backend/src/LibBackend/EventQueue.fs
- fsharp-backend/src/LibBackend/Migrations.fs
- fsharp-backend/src/LibExecution/DvalRepr.fs
- fsharp-backend/src/LibExecution/Execution.fs
- fsharp-backend/src/LibExecution/OCamlTypes.fs
- fsharp-backend/src/LibExecution/VendoredTablecloth.fs
- fsharp-backend/src/LibExecutionStdLib/LibBytes.fs
- fsharp-backend/src/LibExecutionStdLib/LibList.fs
- fsharp-backend/src/LibExecutionStdLib/LibMiddleware.fs
- fsharp-backend/src/LibExecutionStdLib/LibNoModule.fs
- fsharp-backend/src/LibService/Rollbar.fs
- fsharp-backend/src/Prelude/Prelude.fs
- fsharp-backend/src/Tablecloth/TableclothArray.fs
- fsharp-backend/src/Tablecloth/TableclothMap.fs
- fsharp-backend/src/Tablecloth/TableclothString.fs
- fsharp-backend/src/Wasm/Wasm.fs
- fsharp-backend/tests/FuzzTests/FuzzTests.fs
- fsharp-backend/tests/TestUtils/FSharpToExpr.fs
- fsharp-backend/tests/TestUtils/LibTest.fs
- fsharp-backend/tests/Tests/BwdServer.Tests.fs
- fsharp-backend/tests/Tests/HttpClient.Tests.fs
- fsharp-backend/tests/Tests/SqlCompiler.Tests.fs
In the client, the execution engine was failing to parse DErrors. It turns out it was trying to read using the Dval serializers, when it should have been using the ORT.Dval serializer.
Also add more debugging, and address error reading from WorkerSchedule.
> Address blazor exceptions

- services/apiserver-deployment/apiserver-deployment.template.yaml
- services/bwdserver-deployment/bwdserver-deployment.template.yaml
- services/queueworker-deployment/queueworker-deployment.template.yaml
apiserver and bwdserver aren't loading because of errors in legacyserver
The error is
```
Uncaught exception:
(Failure
"Sys.getenv_exn: environment variable DARK_CONFIG_PUSHER_KEY is not set")
```
> Fix apiserver and bwdserver deployments

- containers/fsharp-service-Dockerfile
Hopefully this is the problem in production
Trying to fix the startup of all the F# pods in production, they all have a stack trace like this. For some reason it won't start the http servers. My working theory is that it's using the ASPNETCORE_URLS env var instead of the string provided (the port there being 80, which is restricted for non-root users, while the string provided is port 9001/11001/etc).
```
$ kubectl logs queueworker-deployment-7f4d865ffb-lwv2k queueworker-ctr
Starting queueworker
Starting QueueWorker
Initing LibService in QueueWorker
Configuring rollbar
Configured rollbar
Configuring Telemetry
Configured Telemetry
Inited LibService in QueueWorker
Initing LibExecution in QueueWorker
Inited LibExecution in QueueWorker
Initing LibExecutionStdLib in QueueWorker
Inited …
```
> Don't set ASPNETCORE_URLS - we set it manually everywhere

- fsharp-backend/src/BackendOnlyStdLib/LibDarkInternal.fs
- fsharp-backend/src/BackendOnlyStdLib/LibEvent.fs
- fsharp-backend/src/Benchmark/Benchmark.fs
- fsharp-backend/src/LibBackend/Account.fs
- fsharp-backend/src/LibBackend/Canvas.fs
- fsharp-backend/src/LibBackend/Cron.fs
- fsharp-backend/src/LibBackend/EventQueue.fs
- fsharp-backend/src/LibExecution/RuntimeTypes.fs
- fsharp-backend/src/LibService/Telemetry.fs
- fsharp-backend/src/Tablecloth/TableclothList.fs
- fsharp-backend/src/Wasm/Wasm.fs
- fsharp-backend/tests/TestUtils/TestUtils.fs
- fsharp-backend/tests/Tests/EventQueue.Tests.fs
- fsharp-backend/tests/Tests/Prelude.Tests.fs
- fsharp-backend/tests/Tests/StdLib.Tests.fs
Cronchecker wasn't running properly and when I fixed that it wasn't generating stuff in the right shape.
- trace Enqueue event (add canvasName to it)
- fix SQL bug when fetching orgs
- switch some events to spans, where appropriate
- fix root spans to not have a parent
- for child spans to properly connect to their parent
- fix attributes in events
- fix List.chunksOf, which was throwing away the crons we wanted to run
- fix some warnnings
> Fix what I hope are the remaining problems with events in CronChecker

- fsharp-backend/src/ApiServer/ApiServer.fs
- fsharp-backend/src/ApiServer/Http.fs
- fsharp-backend/src/BackendOnlyStdLib/HttpClient.fs
- fsharp-backend/src/BackendOnlyStdLib/LibDarkInternal.fs
- fsharp-backend/src/BwdServer/Server.fs
- fsharp-backend/src/CronChecker/CronChecker.fs
- fsharp-backend/src/LibBackend/Canvas.fs
- fsharp-backend/src/LibService/Rollbar.fs
- fsharp-backend/src/LibService/Telemetry.fs
- fsharp-backend/src/Prelude/Prelude.fs
- fsharp-backend/src/QueueWorker/QueueWorker.fs
- fsharp-backend/tests/Tests/ApiServer.Tests.fs
- fsharp-backend/tests/Tests/Tests.fs
CronChecker in production had way too many events - 1 per DB query - which blew our budget for events. This disables Npgsql events in CronChecker and QueueWorker - hopefully this should keep them in check.
> Reduce events in cronchecker

- config/gke-builtwithdark
- fsharp-backend/src/LibBackend/Cron.fs
Note this doesn't change the number of CronChecker (or cron_checker) pods, which will be done manually and checked.
The remaining steps:
- kubectl scale deployment/cron-deployment  --replicas=0
- kubectl scale deployment/cronchecker-deployment  --replicas=1
> Enable crons in production

- fsharp-backend/src/LibBackend/Config.fs
- fsharp-backend/src/LibBackend/init.ml.unported
- fsharp-backend/src/LibService/Config.fs
- fsharp-backend/src/LibService/Telemetry.fs
- services/cronchecker-deployment/cronchecker-deployment.template.yaml
- services/exechost-deployment/exechost-deployment.template.yaml
- remove some dead code
- allow mulitple telemetry exporters (and so disable the console exporter in prod)
- change the k8s deployment strategy for cronchecker to be just one at a time
- change CPU limits for cronchecker and exechost
This also enables the last PR (parallel cronchecker) which was deployed in the wrong order.
> Final steps in CronChecker

- services/bwd-deployment/bwd-deployment.template.yaml
- services/editor-deployment/editor-deployment.template.yaml
- services/qw-deployment/qw-deployment.template.yaml
Based on GCP/k8s numbers in production
This is to avoid warnings about being out of resources during a deploy, which makes cronchecker take longer to load.
> Match memory consumption to use

- services/cronchecker-deployment/cronchecker-deployment.template.yaml
Now that it's running in production, let's get the cronchecker resources set closer to actual usage.
> Update cronchecker resources

- fsharp-backend/src/LibBackend/Init.fs
- fsharp-backend/src/LibBackend/OCamlInterop.fs
The F# containers are not starting up correctly, due to the new checkTierOne canvas check. Let's disable this for now.
> Fix startup

- services/cronchecker-deployment/cronchecker-deployment.template.yaml
It will be killed if it runs out of memory. It's safe to run out of CPU as it will just be throtted.
> Give this more memory, just in case

- client/workers/FSharpAnalysisWrapper.res
- fsharp-backend/src/Wasm/Wasm.fs
Fixes the last part of #3272. This gets errors from Wasm analysis into Rollbar and the red error bar.
> Get analysis errors into rollbar and the error bar

- .circleci/config.yml
- backend/bin/cron_checker.ml
- backend/bin/legacy_fuzzing_server.ml
- backend/bin/legacy_serialization_server.ml
- backend/bin/queue_worker.ml
- backend/bin/server.ml
- backend/libbackend/init.ml
- backend/libbackend/stored_function_result.ml
- backend/migrations/20220116_234036_add-function_results_v3.sql
- backend/test/test.ml
- fsharp-backend/src/LibBackend/Migrations.fs
- fsharp-backend/tests/Tests/ApiServer.Tests.fs
- fsharp-backend/tests/testfiles/internal.tests
- scripts/devcontainer/_wait-until-server-ready
- scripts/run-fsharp-tests
This is the first deploy of #3379, simply adding a DB migration to add the table.
It also adds code to read from function_results_v3 as well as v2, but that code is disabled for now.
Another major change is removing DB migrations from running when the server starts up - now migrations are run after a deploy by hand using ExecHost, not automatically. So I've removed migrations from the OCaml backend, and replaced them with calling ExecHost for tests as well.
> Start moving to function_results_v3

- backend/libbackend/libdarkinternal.ml
- backend/libbackend/stored_function_result_v3_migration.ml
- backend/migrations/20220118_083627_drop-function-results-v2.sql
- backend/test/utils.ml
- fsharp-backend/tests/TestUtils/TestUtils.fs
- fsharp-backend/tests/testfiles/internal.tests
- integration-tests/clear-db.sh
Add the migration to drop function_result_v2. This will be run in production, manually, after deploy.
Remove remaining code that references function_result_v2, mostly test code
Disable DarkInternal::copyToplevelTraces, as it's no longer useful
> Remove function_results_v2 code

- fsharp-backend/src/Prelude/Prelude.fs
- fsharp-backend/tests/FuzzTests/FuzzTests.fs
- fsharp-backend/tests/allowedFuzzerErrors.jsonc
With these changes the fuzzers start up again.
- Use standard Option handling (null vs string)
- Allow comments
- Rename to jsonc so vscode/github highlight nicely
It broke because we changed how we parsed json, and we switched this to the "vanilla" parser which can't read comments.
> Fix fuzz test json config file

- fsharp-backend/src/CronChecker/CronChecker.fs
- fsharp-backend/src/LibBackend/Init.fs
Don't start up cronchecker until the DB is available.
This is to prevent the huge number of exceptions reported to rollbar during startup (now that events make it to rollbar).
> Cronchecker exceptions

- .circleci/config.yml
CircleCI was blocking contributor builds because we used a "Context" (a collection of secrets) and if it can't share those (because we don't enable sharing secrets) it fails the builds as unauthorized.
The secrets were slack keys, so the obvious thing is to move the slack notification to a darklang canvas (where the secret is hidden away) and remove the context from the build.
> Allow contributor builds

- fsharp-backend/src/ApiServer/ApiServer.fs
When loading Blazor assemblies (.dlls and .wasm files), console warnings indicate that they are being loaded with the incorrect MIME type. (application/octet-stream)
Ensures that `ApiServer` returns all statically-hosted `.dll` and `.wasm` files are returned with a MIME type of `application/wasm`
Use `FileExtensionContentTypeProvider` type exposed in `Microsoft.AspNetCore.StaticFiles` to configure the MIME types per file  extension
Tested locally; console warnings that existed previously no longer do.
> Correct mimetype of WASM files in ApiServer

- fsharp-backend/src/ApiServer/Ui.fs
When loading the editor in production on apiserver, some files are not loaded. These are all files that use `fetcher` to call. `fetcher` checks hashReplacements, and when I checked `hashReplacements` on production apiserver, it had the wrong values. I think it's because we did a string replacement the entire html file after adding `hashReplacements`. I was able to replicate it locally, and this fixes it.
> Don't overwrite the hashreplacements with the hashreplacements

- .circleci/config.yml
- integration-tests/_integration-test-results-to-honeycomb.sh
CI fails to post the results of integration tests to honeycomb, for PRs against a fork of Dark.
Example: https://app.circleci.com/pipelines/github/darklang/dark/2149/workflows/1877e29a-765c-49c1-b9c4-3bb46564c7bd/jobs/22397?invite=true#step-112-3
Only attempt push to honeycomb if credential `BUILDEVENT_APIKEY` is recent, in the appropriate shell script.
> Push integration test results only when credentials present

- .vscode/launch.json
- backend/bin/legacy_serialization_server.ml
- fsharp-backend/src/LibBackend/OCamlInterop.fs
- fsharp-backend/src/LibService/Telemetry.fs
- scripts/production/connect-to-production-container
I cant figure out why the legacyserver isn't being reached by the ApiServer, so this adds some instrumentation on both ends to see if we can get some answers.
Also some minor fixed to VSCode launching, and connecting to production containers.
> Add debugging to legacyserver

- .gitignore
- backend/bin/legacy_serialization_server.ml
- fsharp-backend/src/LibBackend/PackageManager.fs
- services/apiserver-deployment/apiserver-deployment.template.yaml
- services/bwdserver-deployment/bwdserver-deployment.template.yaml
Adds enough telemetry to figure out the problem with calling the /packages route. What was happening was that the requests were happening quickly, but the JSON decoding was attrociously slow. Each decode was taking 200ms, even though the request was happing in fractions of a second.
The decode is slow because it's using Json.NET, but also because the server is underpowered. I fixed it by setting the servers to have 3 CPUs and 2GB memory. We're doing more of a beefy server than millions of underpowered servers like we were with OCaml (though that itself was async dodge).
We'll remove the JSON.net stuff at some point in the future, but it's fine for now. Given we'll remove all this stuff in the future, it isn't a huge problem.
> Fix /api/packages requests

- fsharp-backend/src/BwdServer/Server.fs
- fsharp-backend/src/LibService/Kubernetes.fs
- services/bwdserver-deployment/bwdserver-network-policy.yaml
- services/bwdserver-deployment/bwdserver-service-backendconfig.yaml
- services/bwdserver-deployment/bwdserver-service.yaml
The Google load balancer (which is configured by a backend-config) needs to succeed for bwdserver to be reachable. However, the healthcheck as configured received a 302 response (this is because it hits the regular bwd codepath, returning a 302 https redirect).
We want it to hit the k8s endpoints instead. Alas, the default "host" http header does not include the port by default. As such, it needs instead to have a host provided (and it did not like having a port included on the host). So let's instead make a host that signals this, that customers can't accidentally hit.
Also, because the backend-config doesn't support the host header, I had to add this by manually.
> Get the healthcheck to the bwdserver in a way it will respond to

- client/src/api/API.res
- client/src/app/VariantTesting.res
- client/src/core/Types.res
- fsharp-backend/src/ApiServer/ApiServer.fs
- services/apiserver-deployment/nginx.conf
- services/editor-deployment/darklang-ingress.yaml
Part of https://github.com/darklang/dark/issues/3508
This allows users to test out the new backend in the editor by going to
`https://darklang/a/canvasname?fsharp-backend=true`
At also allows them to test loading the editor by going to 
`https://darklang.com/a-testing-fsharp/canvasname`
Or to get both:
`https://darklang.com/a-testing-fsharp/canvasname?fsharp-backend=true`
> Enable apiserver access

- client/src/analysis/Analysis.res
- client/src/api/API.res
- client/src/app/VariantTesting.res
- client/src/core/Types.res
- client/workers/Fetcher.res
I apparently missed a couple of API calls, and while many paths are going to the apiserver when requested, some still go to the OCaml editor. This moves the rest to use the root that's passed in.
> More apiserver

- fsharp-backend/src/BackendOnlyStdLib/LibStaticAssets.fs
- fsharp-backend/src/BackendOnlyStdLib/LibTwilio.fs
- fsharp-backend/src/LibBackend/Canvas.fs
- fsharp-backend/src/LibBackend/StaticAssets.fs
Add StaticAssets module. I opted not to use the legacy http clients, but to replicate what we used them for instead.
Also add Twilio module - I used the legacy clients for that.
> Add support for libstaticassets

- fsharp-backend/src/BwdServer/Server.fs
- fsharp-backend/src/LibService/Kubernetes.fs
- services/apiserver-deployment/apiserver-service-backendconfig.yaml
- services/apiserver-deployment/apiserver-service.yaml
- services/bwd-deployment/bwd-ingress.yaml
- services/bwdserver-deployment/bwdserver-deployment.template.yaml
- services/bwdserver-deployment/bwdserver-service-backendconfig.yaml
- services/bwdserver-deployment/bwdserver-service.yaml
Allow the bwdserver to join the load balancer:
- Fix the configuration settings to get the healthcheck to the bwdserver. The missing configuration was the nodeport. 
- Copy the bwdserver settings to apiserver.
- Change the host in the healthchecks to gce-ingress-healthcheck
- add note about logging
- turn on logging in apiserver
- Fix infinite redirects (it's the header that indicates https, not actually https on the server, as TLS is terminated at the load balancer)
- support the rest of the tryfsharpdark paths on bwdserver
- reduce bwdserver replicas to 3 (from 4)
> Fix production configs

- services/apiserver-deployment/apiserver-network-policy.yaml
- services/apiserver-deployment/apiserver-service-backendconfig.yaml
- services/apiserver-deployment/apiserver-service.yaml
- services/apiserver-deployment/nginx.conf
- services/bwdserver-deployment/bwdserver-service-backendconfig.yaml
- services/bwdserver-deployment/bwdserver-service.yaml
- services/editor-deployment/darklang-ingress.yaml
Finishing touches on making the apiserver healthcheck work the same as the bwdserver healthcheck.
It turns out the missing thing was the ingress rule to allow incoming traffic on 9002.
Also:
- fixed a lot of comments to reflect current reality.
- change to unhealthyThreshold of 1
- change to more consistent ports for the healthchecks
- remove unneeded nginx forwarding for the healthcheck
This config is already live in production.
> Fully fix apiserver backendconfig

- fsharp-backend/src/ApiServer/ApiServer.fs
- fsharp-backend/src/BackendOnlyStdLib/LibDarkInternal.fs
- fsharp-backend/src/BwdServer/Server.fs
- fsharp-backend/src/CronChecker/CronChecker.fs
- fsharp-backend/src/ExecHost/ExecHost.fs
- fsharp-backend/src/LibBackend/Account.fs
- fsharp-backend/src/LibExecution/Errors.fs
- fsharp-backend/src/LibExecution/Interpreter.fs
- fsharp-backend/src/LibExecution/RuntimeTypes.fs
- fsharp-backend/src/LibRealExecution/RealExecution.fs
- fsharp-backend/src/LibService/FireAndForget.fs
- fsharp-backend/src/LibService/Kubernetes.fs
- fsharp-backend/src/LibService/Rollbar.fs
- fsharp-backend/src/QueueWorker/QueueWorker.fs
- fsharp-backend/tests/TestUtils/TestUtils.fs
I'm trying to debug some exceptions and don't have enough metadata to make it easy. This adds more for program execution.
> Improve exception metadata during execution

- fsharp-backend/src/LibService/HeapAnalytics.fs
The error is 
"postBody.events[0].timestamp is not a valid unix,iso8601 timestamp"
This is because the timestamp was in this format "2022-02-28T23:48:04.2847713Z"
> Fix 400 error from Heap API

- .circleci/config.yml
- backend/test_appdata/test-fluid_test_copy_request_as_curl.json
- backend/test_appdata/test-package_function_references_work.json
- fsharp-backend/src/LibBackend/Canvas.fs
- fsharp-backend/src/LibBackend/File.fs
- integration-tests/README.md
- integration-tests/clear-db.sh
- integration-tests/playwright.config.ts
- integration-tests/run.sh
- integration-tests/tests.ts
- scripts/devcontainer/_wait-until-apiserver-ready
- scripts/run-fsharp-server
We attempted to deploy #3485, but had issues with Blazor-related performance - we thus reverted.
We'd like to address those concerns in a silo, while also getting out other work in that PR.
This PR is a subset of #3485, aimed only to switch integration tests to use the F# backend.
Note that this does _not_ include the switch to using Blazor in the client during integration testing.
> Default to F# backend for integration tests

- client/src/appsupport.js
- fsharp-backend/src/Wasm/static/BlazorWorker.js
Errors that occur in Blazor-compiled F# backend are lost inside of BlazorWorker.js
Pass an on-error callback to the blazor worker initializer, and adjust BlazorWorker to ensure such errors get there
> Ensure Blazor failures get to Rollbar

- fsharp-backend/tests/testfiles/http.tests
`http.tests` was missing tests around `Http.redirectTo_v0` and `Http.responseWithHeaders_v0`
Add tests
> Add tests for Http.redirectTo and .responseWithHeaders

- fsharp-backend/src/LibBackend/Canvas.fs
- fsharp-backend/src/LibBackend/OCamlInterop.fs
- fsharp-backend/src/LibBackend/Serialize.fs
- fsharp-backend/src/LibBackend/Traces.fs
- fsharp-backend/src/LibExecution/OCamlTypes.fs
- fsharp-backend/src/Prelude/Prelude.fs
- fsharp-backend/tests/DataTests/DataTests.fs
- fsharp-backend/tests/Tests/ApiServer.Tests.fs
- fsharp-backend/tests/Tests/DvalRepr.Tests.fs
Fixes #3542.
Expands the DataLoads testing framework to test all the read-only API calls in ApiServer for all users:
- remove call to initialLoad where it isn't needed
- structure all tests in APIServer.Tests in the same format to be easy to call
- allow running which tracking failures
- allow specifying a filename
Caught some errors:
- DPasswords were incorrect deserialized
- unknown handlers and old workers didn't get sample traces
- old worker handlers didn't get sample traces
> More readonly API call fixes

- backend/libbackend/event_queue.ml
- backend/libbackend/event_queue.mli
- backend/liblegacyfuzzing/fuzzing.ml
- fsharp-backend/src/LibBackend/EventQueue.fs
- fsharp-backend/tests/TestUtils/LibTest.fs
- fsharp-backend/tests/Tests/LibExecution.Tests.fs
- fsharp-backend/tests/testfiles/README.md
- fsharp-backend/tests/testfiles/events.tests
`emit_v0` and `emit_v1` are untested.
Add a `events.tests` file with tests - and generally allow for testing of `emit` within testfiles.
- in `EventQueue.fs`, add fn `testingGetQueue` for test purposes, to fetch all events on a queue
- add a Test-only lib fn `getQueue` that uses `testingGetQueue`
- adjust `LibExecution.Test.fs`
- to allow for the parsing of `[test.name] with Worker MyWorker` tests
- to add the handlers to test programs when relevant, using `Canvas.addOps` (if there's a better way to do this, please let me know)
- update the relevant README.md
- add tests around `emit`
> Add tests around `emit` StdLib fn

- fsharp-backend/tests/testfiles/string.tests
No tests are present around `String::foreach_v0`
Add them
> Add tests around lib fn String.foreach_v0

- fsharp-backend/src/ApiServer/Ui.fs
Blazor assets that are stored in `backend/static/blazor` are hashed in prod, and the OCaml server expects them to be such, but the F# server doesn't.
This updates `ApiServer` to expect hashed `blazor` folder files.
> Update ApiServer to expect static blazor files to be hashed

- fsharp-backend/src/Prelude/Prelude.fs
- fsharp-backend/src/Wasm/Wasm.fs
Aimed to resolve #3577.
Tested locally by updating `src/LibExecution/OCamlTypes.fs` locally, commenting out the handling of `EIntegers` from `rt2ocamlExpr`, and running an analysis on something that returned an Int.
If I try to change the shape of the Error returned (e.g. by returning an anonymous record of `{ message: string, metadata: ...}` , I get issues in decoding the error on the client. So, I shoe-horned both into the string - happy to take recommendations there.
> Include metadata in F# Wasm exceptions

- CODING-GUIDE.md
- backend/migrations/20220316_174259_add-extra-events-index.sql
This migration is already in production, but this adds it to the repo.
It will still be run when it goes to production, hence  `if not exists`. I've tested this locally on prodclone to ensure it's instant if the index already exists.
Adds an index which drops the DB CPU usage from 80% to 20%, see https://twitter.com/paulbiggar/status/1504182057928470529 for details.
> Add migration

- fsharp-backend/src/ApiServer/Api/APIOps.fs
- fsharp-backend/src/LibBackend/Canvas.fs
- fsharp-backend/src/LibBackend/CanvasClone.fs
- fsharp-backend/src/LibBackend/PackageManager.fs
- fsharp-backend/src/LibBackend/Serialize.fs
- fsharp-backend/src/Prelude/Prelude.fs
- fsharp-backend/tests/DataTests/DataTests.fs
- fsharp-backend/tests/Tests/ApiServer.Tests.fs
- fsharp-backend/tests/Tests/Canvas.Tests.fs
Currently, when you edit code in the F# ApiServer, we save it in a binary format for both the OCaml and F# servers.
This PR also saves it in that format when you read code from F# servers (not just when you write it).
I tested this by loading some canvases and looking at what happened via honeycomb. I could see for example that in the ops-adduser trace (which has hundreds of toplevels), it made requests for all toplevels via the legacy server, then saved them with these new functions. Then future loads were practically instant (which is much faster than they are on ocaml servers).
ops-adduser went from 200s to load, to 600ms.
Once this is in production, any user who opens their canvas using the F# apiserver or bwdserver or queueworker will have their canvas auto-upgraded to the new …
> Save F# binary serialization whenever reading from OCaml legacy server

- fsharp-backend/src/LibBackend/Init.fs
The Cronchecker is supposed to wait until the DB is ready to start up. The exceptions
in Rollbar indicate that it is trying to run the crons before the DB is actually
ready for it, implying it got past the WaitForDB call.
This could be because the `return` was in the wrong place, executing after the first
iteration of the loop, as opposed to after the loop is over.
Hard to tell if this fixes things without trying it.
> Attempt to fix exception in the CronChecker

- fsharp-backend/src/ApiServer/Ui.fs
Many Blazor files copied to `backend/static/blazor` are like `System.Xml.dll`, containing multiple `.`s.
Logic within `UI.fs` to include those hashed assets failed, expecting only one `.` 
This fixes that.
> Fix ApiServer load of hashed blazor files

- fsharp-backend/src/LibBackend/Canvas.fs
- fsharp-backend/src/LibService/Rollbar.fs
- fsharp-backend/src/LibService/Telemetry.fs
- fsharp-backend/src/Prelude/Prelude.fs
- fsharp-backend/src/QueueWorker/QueueWorker.fs
I noticed that some metadata wasn't making it through to Honeycomb, including the tag that causes the pager to go off. This should bring the info to the end.
> More metadata for exceptions

- services/cronchecker-deployment/cronchecker-deployment.template.yaml
We see several errors in Rollbar that happen on every deploy. The errors are about the connection to the DB being missing. While I initially thought this happened on startup, my current guess is that it happens on shutdown.
This configures the cloud_sql_proxy to wait until connections have closed before shutting down. It seems a pretty reasonable guess as to the cause of the exceptions.
> Potentially prevent DB errors when cronchecker is shutting down

- fsharp-backend/src/Prelude/Prelude.fs
- fsharp-backend/src/Wasm/Wasm.fs
Reverts darklang/dark#3581
I believe we reverted this change because we thought it caused an issue. It turns out that the actual issue was irrelevant, to do with hashing, and has since been resolved.
> Re-include metadata in F# Wasm exceptions

- services/apiserver-deployment/apiserver-deployment.template.yaml
- services/bwdserver-deployment/bwdserver-deployment.template.yaml
- services/cronchecker-deployment/cronchecker-deployment.template.yaml
- services/exechost-deployment/exechost-deployment.template.yaml
- services/queueworker-deployment/queueworker-deployment.template.yaml
This makes all the cloud_sql_proxy kubernetes configs match each other. We wouldn't have had the cronchecker issues if the configs had matched.
Also switches the timeout to 30s, cause there's no reason to match it to 28s.
> Regularize gce proxy config

- backend/migrations/20220319_140703_add-package-binary-column.sql
- fsharp-backend/src/ExecHost/ExecHost.fs
- fsharp-backend/src/LibBackend/BinarySerialization.fs
- fsharp-backend/src/LibBackend/PackageManager.fs
Same as #3607, but just the first few commits. The goal is to get the migration safely merged (it has already been applied), and to ensure that things still works (low risk, just being careful).
> Add tools to use new binary serialization for packages

- scripts/deployment/shipit
I noticed a long time ago that the exechost deployment was broken, but hadn't gotten around to fixing it.
It seems it was broken because the same configmap was used in two different namespaces, but `shipit` only used one of them (due to using the same key for both and overwriting it). This adds the namespace to the key as well, so we get both.
Also fixes `shipit release current-manifest`, which didn't like image urls with multiple `:` in the url.
> Fix Exechost deployment

- .circleci/config.yml
- fsharp-backend/src/CronChecker/CronChecker.fs
- fsharp-backend/src/LibRealExecution/Init.fs
The Cronchecker container wouldn't initialize because we were trying to call legacy-ctr, which it doesn't have.
> Fix cronchecker initialization

- services/editor-deployment/darklang-ingress.yaml
Since we can't switch the defaultBackend over to use ApiServer everywhere, let's try something else. The built-in rules clearly work, so let's use them instead.
We can later create a whole new load-balancer to avoid the switchover.
> Use rules to point everything to the F# backend

- fsharp-backend/src/ApiServer/ApiServer.fs
- fsharp-backend/src/Wasm/Wasm.fsproj
- scripts/deployment/_push-assets-to-cdn
I'm investigating [why fetching blazor assets](
https://github.com/darklang/dark/issues/3589) from the CDN causes Chrome to not connect anymore. I have no idea why this would be, but one idea I had is that perhaps the content-types are weird and triggering some sort of built-in DDOS protection. Not a great guess, but it does make all the content-type headers right instead of weird, so it's a net improvement anyway.
This was tested by pointing at a different bucket and comparing against the darklang-static-assets bucket.
> Fix content types for blazor

- fsharp-backend/src/LibExecution/Interpreter.fs
- fsharp-backend/src/LibRealExecution/RealExecution.fs
Within the `HttpClient` stdlib fns, passing in a `string` where a `DObj<string>` is expected for `headers` results in a DeveloperException, both in OCaml and F# backends. Issue #3524.
This error comes from [Dval.to_string_pairs_exn request_headers](https://github.com/darklang/dark/blob/4de2da65b007579ec0e36ff27539007620101120/backend/libbackend/libhttpclient.ml#L104) and [DvalReprExternal.toStringPairs reqHeaders](https://github.com/darklang/dark/blob/4de2da65b007579ec0e36ff27539007620101120/fsharp-backend/src/BackendOnlyStdLib/HttpClient.fs#L439), respectively.
In the OCaml backend, these sort of expected runtime exceptions seem to be handled by the `InProcess` wrappers that surround many functions.
For example, `HttpClient::get_v5` is wrapped by `InProcess` …
> Adjust Interpreter.fs to handle DevExceptions

- containers/base-fsharp-nginx.conf
- scripts/run-nginx-server
- services/apiserver-deployment/apiserver-deployment.template.yaml
- services/apiserver-deployment/shipit.yaml
- services/bwdserver-deployment/bwdserver-deployment.template.yaml
- services/bwdserver-deployment/shipit.yaml
I've started load testing the new F# implementation, using for now:
`./wrk -t 8 -c 5000 -d 5s https://trydarkfsharp.builtwithdark.com/fizzbuzz --timeout 4s`
I'm seeing a lot of 500 and 502 errors, along with an alert in the nginx logs that the container doesn't have enough workers. Hopefully this should fix this and we'll see where we are then.
Also, it seems that after switching to an unprivileged version of nginx, we didn't use the default config from that container. So this switches to that, and then makes the appropriate changes.
> Load testing

- fsharp-backend/src/Prelude/Prelude.fs
- fsharp-backend/tests/FuzzTests/BytesToString.FuzzTests.fs
- fsharp-backend/tests/FuzzTests/DvalRepr.FuzzTests.fs
- fsharp-backend/tests/FuzzTests/ExecutePureFunctions.FuzzTests.fs
- fsharp-backend/tests/FuzzTests/FQFnName.FuzzTests.fs
- fsharp-backend/tests/FuzzTests/FuzzTests.fs
- fsharp-backend/tests/FuzzTests/FuzzTests.fsproj
- fsharp-backend/tests/FuzzTests/HttpClient.FuzzTests.fs
- fsharp-backend/tests/FuzzTests/Json.FuzzTests.fs
- fsharp-backend/tests/FuzzTests/NodaTime.FuzzTests.fs
- fsharp-backend/tests/FuzzTests/OCamlInterop.FuzzTests.fs
- fsharp-backend/tests/FuzzTests/Passwords.FuzzTests.fs
- fsharp-backend/tests/FuzzTests/README.md
- fsharp-backend/tests/FuzzTests/Utils.FuzzTests.fs
- fsharp-backend/tests/Tests/DvalRepr.Tests.fs
> Commentate+Tidy FuzzTests

- fsharp-backend/src/LibExecution/Interpreter.fs
- fsharp-backend/tests/Tests/Traces.Tests.fs
I'm not done with this yet but would like a directional review.
It's hard to see from the diff, but there's almost no change here:
- the try catch is moved from around all function calls to just the StdLib fn call
- the catch logic is moved into a function
- added type checking for the results of functions
I'm going to continue looking at this to add tests and some defense in depth:
My main question is when to merge. I'm tempted to merge here or after adding tests. wdyt?
> Ensure traces are stored if there are errors

- fsharp-backend/src/LibBackend/OCamlInterop.fs
Before merging #3643, I missed that the OCaml legacy backend is now expecting an extra (`packageFns`) item in the tuple that's sent over as part of expr evaluations.
`OCamlInterop.execute` had been adjusted (outside of that PR) for the change, but not `executeExpr`, which was used (only) by `executePureFunctions` fuzztests, causing those to fail without this change.
> Fix: include packageFns in OCamlInterop executeExpr

- scripts/deployment/shipit
I removed the namespace from the ConfigMapDef, intending to use it implicitly as part of the key. But looks like I did it wrong.
As a result, I was reusing the old `namespace` value that was last updated in a loop, and so all the configmaps were being applied in the final namespace (which was the darklang namespace, not the default namespace).
This fixes it by re-adding the `namespace` field to the ConfigMapDef, and using it when doing `kubectl apply configmap`. It also adds the namespace to all the logging, as kubectl will print the resource that's being created/configured, but not the namespace. This would have made debugging this much easier.
> Fix bug causing us to ship all configmaps in one namespace

- fsharp-backend/src/LibBackend/OCamlInterop.fs
We're seeing some timeouts here. We really can't help it if these take a long time, so let's just extend the timeout and hope that we can ride it out until we remove OCamlInterop.
> Increase the timeout

- services/tunnel2-deployment/darklang-executors-networkpolicy.yaml
We didn't enable the 10.0.0.0/8 exclusion before, which removed basically all the advantage of the defense in depth. Fortunately, it looks like that only provided TCP port 53 (needed for DNS) and so we can disable it.
This is already applied in production.
> This removes the firewall exclusion for 10.0.0.8 for sql access

- fsharp-backend/src/BackendOnlyStdLib/LibStaticAssets.fs
Use the tunnel2 proxy, same as LibHttpClient.
The proxy is firewalled so that it can't touch internal stuff. This makes sense for LibHttpClient as we don't want customers poking around. However, potentially people could try to access stuff via malformed StaticAssets URLs, so this provides some extra protection.
> Use proxy for libstaticassets

- fsharp-backend/src/BackendOnlyStdLib/LibDB2.fs
- fsharp-backend/src/LibBackend/SqlCompiler.fs
- fsharp-backend/tests/testfiles/db.tests
Partial fix for https://github.com/darklang/dark/issues/3699
There's an exception in rollbar that comes from the following code:
```
DB::query TableWithIntField \p -> p.intField = "string"
```
This is because for the `=` function we check the two arguments separately to see if they are the `TAny` type, which they are. In fact, we should check that both arguments are the **same** type.
However, this was also a bug in the old version, so I'm not fixing that. Instead, I'm fixing two related problems:
- we didn't catch the error in tests
- we raised an internal exception instead of showing a semi-nice error to users
This catches the exception and tidies up how we do tests a little in db.tests to be able to see the error.
We don't need to do the rest of #3699 for the migration to be complete …
> Handle sql errors better

- fsharp-backend/src/BwdServer/Server.fs
- fsharp-backend/src/ExecHost/ExecHost.fs
- fsharp-backend/src/LibBackend/SqlCompiler.fs
- fsharp-backend/src/LibExecution/Interpreter.fs
- fsharp-backend/src/LibExecution/OCamlTypes.fs
- fsharp-backend/src/LibExecution/ProgramTypesToRuntimeTypes.fs
- fsharp-backend/src/LibExecution/RuntimeTypes.fs
- fsharp-backend/src/LibExecution/RuntimeTypesAst.fs
- fsharp-backend/tests/TestUtils/FSharpToExpr.fs
- fsharp-backend/tests/TestUtils/TestUtils.fs
- fsharp-backend/tests/testfiles/README.md
- fsharp-backend/tests/testfiles/language.tests
- scripts/production/gcp-psql
- scripts/production/get-production-handler
When switching new users over to the BwdServer today, we ran into some [exceptions](https://rollbar.com/darkops/darklang/items/3094/) which caused the handlers to break. The exceptions were 
"No EPipeTargets should remain".
The problem was on code such as:
```
something
|> partial "my" (myFn 5)
```
which is to say, piping into a partial.
When being converted to RuntimeTypes, the partial got in the way of the pattern matches when deconstructing the pipe.
My first attempts to solve this was to remove EPartial from RuntimeTypes. That was a good move imo, even though it didn't solve the problem.
It didn't solve the problem because the pattern matching was at the ProgramType level, so it didn't make a difference whether there was an RT.EPartial.
So to solve it we needed to unwrap the contents …
> Handle partials in pipes

- CODING-GUIDE.md
- fsharp-backend/src/LibBackend/Canvas.fs
- fsharp-backend/tests/Tests/BwdServer.Tests.fs
- fsharp-backend/tests/httptestfiles/README.md
This is a no-op change that helped me understand `BwdServer.Tests.fs`, since I was getting lost in the huge `t` fn.
Mainly, it extracts out new `setupTestCanvas` and `runTestRequest` fns from `t`
The extracted `runTestRequest` is still quite a bit, but imo much better (and I've hit my self-set timebox of refactoring)
> Tidy BwdServer tests

- fsharp-backend/src/ApiServer/Api/APIOps.fs
- fsharp-backend/src/ApiServer/ApiServer.fs
- fsharp-backend/src/LibBackend/CanvasClone.fs
- fsharp-backend/src/LibBinarySerialization/BinarySerialization.fs
- fsharp-backend/src/LibBinarySerialization/SerializedTypesToProgramTypes.fs
I was investigating the DB, and discovered that contrary to my expectations, very many rows in toplevel_oplist did not have the columns for the F# serialization of oplist or toplevel (these are called oplist and oplist_cache).
This investigation is in https://github.com/darklang/dark/issues/3727. I went through all the canvases and found reasons why various groups of canvases didn't have these, and it seems that overall, if the canvas is deleted or live, it should have an F# version of the oplist and the oplist_cache.
```
ol           |           opcache           | deleted |         meta          | count
-----------------------+-----------------------------+---------+-----------------------+-------
error: oplist missing | error: missing oplist cache | f       | error: missing meta   | …
```
> Fix oplists in the DB

- scripts/builder
`gid` is needed in the last `docker run` command, but it `gid` is not defined if NEVER_REBUILD_DOCKER is set
Define `gid` unconditionally.
> Fix gid with NEVER_REBUILD_DOCKER env var

- fsharp-backend/src/LibBackend/OCamlInterop.fs
This should hopefully allow the final 3 toplevels to use F# as their primary store,
and also should allow more saves to go through (some are failing due to this timeout)
> Increase timeout

- fsharp-backend/src/LibBackend/CanvasClone.fs
Toplevels can't be found occasionally, if they're deleted forever.
I think I've eliminated toplevels that are deleted forever, but best to be careful.
> Don't fail if a toplevel can't be found during canvasClone

- fsharp-backend/tests/Tests/ApiServer.Tests.fs
Inspired by being confused by this error report: https://github.com/darklang/dark/issues/3745, as the expectation/actual are reversed.
> Correct arg. order of Expect.equal in HSTS test

- fsharp-backend/src/ApiServer/Api/APIExecution.fs
- fsharp-backend/src/BwdServer/Server.fs
- fsharp-backend/src/HttpMiddleware/MiddlewareV0.fs
- fsharp-backend/src/HttpMiddleware/RequestV0.fs
- fsharp-backend/src/LibBackend/Db.fs
- fsharp-backend/src/LibBackend/TraceFunctionArguments.fs
- fsharp-backend/src/LibBackend/TraceFunctionResults.fs
- fsharp-backend/src/LibExecution/Execution.fs
- fsharp-backend/src/LibExecution/Interpreter.fs
- fsharp-backend/src/LibExecution/RuntimeTypes.fs
- fsharp-backend/src/LibRealExecution/RealExecution.fs
- fsharp-backend/src/LibService/FireAndForget.fs
- fsharp-backend/src/LibService/Rollbar.fs
- fsharp-backend/src/Prelude/Prelude.fs
- fsharp-backend/src/QueueWorker/QueueWorker.fs
- fsharp-backend/tests/Tests/EventQueue.Tests.fs
- fsharp-backend/tests/Tests/Traces.Tests.fs
We were storing traces in the foreground, which in an async server slowed things down.
I was trying to switch a user over, and their handlers that used to run in 3-5 seconds now took 10 (which timed out some other stuff). It's not a particularly interesting function, it just calls a few user-defined functions on a reasonable chunk of data. The json generated is about 70k.
The problem here is that we are over-storing traces for functions. We store argument- and result-traces for every time a user-function is called (for stdlib functions, we only save results for impure one function calls). This PR actually doesn't do anything to address this problem, it just deals with the volume of calls created by this.
I tried a few different things like running the requests in the background as they …
> Store traces in the background

- docs/production/custom-domains.md
- scripts/custom-domains/_add-to-cert-manager
- scripts/custom-domains/_check-cert-added
- scripts/custom-domains/add
- scripts/custom-domains/check-consistency
- scripts/custom-domains/delete-from-cert-manager
- services/bwdserver-deployment-darklang/bwdserver-deployment.template.yaml
- services/custom-domains-darklang/cert-manager-clusterrolebinding.yaml
- services/custom-domains-darklang/cert-manager-issuer.yaml
- services/custom-domains/nginx-ingress-controller.yaml
Change the cert-manager scripts to use the new ingress.
Make sure the old deployment doesn't use the new deployment's ingress.
Increase the number of bwdservers in the darklang deployment.
> Use new custom domains ingress

- fsharp-backend/src/HttpMiddleware/MiddlewareV0.fs
- fsharp-backend/tests/httptestfiles/cors-no-setting-user-setting-wins.test
- fsharp-backend/tests/httptestfiles/cors-one-header-user-setting-wins.test
- fsharp-backend/tests/httptestfiles/cors-star-user-setting-wins.test
- services/honeycomb-agent/shipit.yaml
Got a bug report from @xtopherbrandt that CORS was not functioning right.
```
let headers = { Access-Control-Allow-Origin : "x" }
Http::responseWithHeaders {} headers 200
```
The middleware would overwrite the custom header.
Turns out we added headers in the wrong order. Tests included.
> Fix user cors settings

- fsharp-backend/src/CronChecker/CronChecker.fs
- fsharp-backend/src/LibBackend/EventQueueV2.fs
- fsharp-backend/src/LibBackend/Init.fs
- fsharp-backend/src/LibService/LaunchDarkly.fs
- fsharp-backend/src/QueueWorker/QueueWorker.fs
- fsharp-backend/tests/Tests/EventQueueV2.Tests.fs
- fsharp-backend/tests/Tests/Tests.fs
Handles a couple of issues seen running in production.
The queueworker was de facto single threaded, but we have capacity to run probably hundreds of simultaneous events at a time. Now we run more than one, up to a number dictated by a feature flag.
Add something to calculate CPU and memory usage in the background. We're not ready to use these to factor into the decision making process, but let's collect the number for now and see what we get.
Add a fix for a production exception: when someone unpauses the queue but there's no jobs in it.
> Queueworker, 5th pass

- fsharp-backend/src/LibBackend/EventQueueV2.fs
- fsharp-backend/src/QueueWorker/QueueWorker.fs
Remove the CPU usage stuff - it was the wrong way to approach it.
Have a fresh Telemetry parent for each event, and ensure it has the right data
> Queueworker pass 6

- scripts/build/_dotnet-wrapper
- scripts/build/compile
I played around with build speed a little bit, culminating in removing `unbuffer` and
`-graphBuild:true`. Unbuffer was just used to get commands to display like they do in
a terminal (there's other ways to do it, but I'll just remove this for now)
```
unbuffer | graphBuild | no touch | change test file | change Prelude.fs
y        | y          | 4.7s     | 12.7s            | not tested
y        | n          | 5.3s     | 13.6s            | not tested
n        | y          | 3.0s     | 11.3s            | 47.9s
n        | n          | 1.8s     | 9.98s            | 46.92
```
> Improve build speed

- fsharp-backend/src/ApiServer/ApiServer.fs
- fsharp-backend/src/BackendOnlyStdLib/LibDarkInternal.fs
- fsharp-backend/src/BwdServer/Server.fs
- fsharp-backend/src/CronChecker/CronChecker.fs
- fsharp-backend/src/ExecHost/ExecHost.fs
- fsharp-backend/src/LibBackend/Account.fs
- fsharp-backend/src/LibRealExecution/RealExecution.fs
- fsharp-backend/src/LibService/FireAndForget.fs
- fsharp-backend/src/LibService/Kubernetes.fs
- fsharp-backend/src/LibService/Rollbar.fs
- fsharp-backend/src/Prelude/Prelude.fs
- fsharp-backend/src/QueueWorker/QueueWorker.fs
It turns out there's a bunch of exceptions we're not seeing - any thing that doesn't have an id (much more common for queues and cronworkers than anything else, though probably it was hiding any PageableExceptions).
This includes code to debug the issue, which I might leave on and see how it goes. It prints to stdout, which we don't much use otherwise.
I removed the email from the Person type and made it an option.
Also adds more info to exceptions.
> Queueworker pass 8

- fsharp-backend/src/LibBackend/TraceFunctionArguments.fs
- fsharp-backend/src/LibBackend/TraceFunctionResults.fs
- fsharp-backend/src/LibRealExecution/RealExecution.fs
- fsharp-backend/src/Prelude/Prelude.fs
- scripts/build/compile
When moving traces out of the main execution, I added them to a dictionary. However, it seems there is a very-bad performance impact from this: each item we add to a dictionary has a HashCode calculated, and hashcodes to Lists can be very slow.
This PR makes these more performant. We calculate our own hash for FunctionResults, so that we don't duplicate saving the data (still using Dictionarys). For FunctionArguments, don't use the arguments to hash a dictionary, instead just save the whole list (I'm not sure we saved anything by having a dictionary).
> Queueworker pass 11 - prevent stackoverflow

- fsharp-backend/src/LibBackend/EventQueueV2.fs
- fsharp-backend/src/QueueWorker/QueueWorker.fs
- fsharp-backend/tests/Tests/EventQueueV2.Tests.fs
Also improve comments a lot
The reason for this is that pulling events from the queue is quite slow right now - we do a full loop iteration for each event.
For context, here are events all queued at roughly the same time via cron:
Even though we have the 2 workers set to take 8 events each, it takes over two seconds to get all 27 values out of the queue (most complete in about 250ms). Really we have the capacity to start them all at once, so let's not be coy about this.
> Support reading more events from the queue

- scripts/build/_generate-etags
- scripts/deployment/_push-assets-to-cdn
Relates to #3811 and #3872.
It seems that the CI step of uploading static assets is failing on .br files. This should fix that.
> When deploying, don't try to upload .br files

- config/gke-builtwithdark
- services/apiserver-deployment-darklang/apiserver-deployment.template.yaml
- services/bwdserver-deployment-darklang/bwdserver-deployment.template.yaml
- services/cronchecker-deployment/cronchecker-deployment.template.yaml
- services/exechost-deployment/exechost-deployment.template.yaml
- services/queueworker-deployment/queueworker-deployment.template.yaml
This one is in Oregon. I'm hoping that it will prevent the timeouts we're seeing (our k8s cluster is in oregon).
I'm a little sketch on this change though - will the old stuff continue to work? Will the new stuff? I've added the credentials to k8s already.
> Add new pusher credentials for a different pusher app

- fsharp-backend/src/ApiServer/ApiServer.fs
This reverts commit 9c35b9d757d70b893f07261b6709574ba827ebe6.
When users try to load a trace, it responds just fine, but then it calls the API again, hundreds of times a minute. Reverting until we figure this out and have a test on it.
> Revert "Use vanilla json version instead for loading traces"

- fsharp-backend/src/ApiServer/Api/APIExecution.fs
- fsharp-backend/src/BwdServer/Server.fs
- fsharp-backend/src/LibBackend/TraceFunctionResults.fs
- fsharp-backend/src/LibBackend/Tracing.fs
- fsharp-backend/src/LibExecution/Execution.fs
- fsharp-backend/src/LibRealExecution/RealExecution.fs
- fsharp-backend/src/QueueWorker/QueueWorker.fs
- fsharp-backend/tests/Tests/Traces.Tests.fs
When executing functions, their traces were not showing on refresh.
This was due to a bug in the refactoring in #3867, where we [stopped using the `caller_id`](https://github.com/darklang/dark/pull/3867/files#diff-36cabfc96e28c87b2a5e82195618503964ce5ad8d5b811b869e3e285faa7c015R60)
Also some tiny code fixes, no changes.
> Fix missing trace results of execute function

- scripts/deployment/_push-assets-to-cdn
Currently, this script is failing, seemingly due to high memory usage. See commentary in #3872.
The intention here is to reduce the # of gsutil calls, uploading in batches per file extension or content-type.
The needs of the script got complex enough where it made sense to port to Python.
I'm at a point now where this is ported to match the original.
I'm not well-versed in Python or Bash, so I could be doing some plain dumb things here, stylistically.
> Rewrite _push-assets-to-cdn in Python

- fsharp-backend/src/BackendOnlyStdLib/HttpClient.fs
- fsharp-backend/src/BackendOnlyStdLib/LegacyBaseHttpClient.fs
- fsharp-backend/src/Prelude/Prelude.fs
- fsharp-backend/src/QueueWorker/QueueWorker.fs
This adds a little more info to see if things are working (or why they aren't).
In http requests, get more errors if they exist, and see if we can get enough info from this to know why a http request has failed.
In the queues, we now see `Option(None)` or `Option(Some)` (and similar for results) instead of `Option`. We have that info in OCaml, so it makes for a better comparison.
> More httpclient info

- scripts/deployment/_push-assets-to-cdn
If a file is at `/backend/static/blazor/blazor.js`, we expect it to land at `{BUCKET}/blazor/blazor.js`, but prior to this, it'd land at `{BUCKET}/blazor.js`.
This corrects that, and improves commentary of the script generally.
> Respect relative dirs in _push-assets-to-cdn script

- .circleci/config.yml
- scripts/run-fsharp-tests
Forgot to merge this it seems
This fixes the junit output on fsharp tests in CI. This would have been useful for diagnosing the flaky tests.
> Get correct junit.xml in CI

- .circleci/config.yml
- Dockerfile
- fsharp-backend/global.json
- fsharp-backend/src/BwdServer/Server.fs
- fsharp-backend/src/LibBackend/Tracing.fs
- fsharp-backend/src/LibExecutionStdLib/LibDict.fs
- fsharp-backend/src/LibExecutionStdLib/LibList.fs
- fsharp-backend/tests/TestUtils/LibTest.fs
- scripts/linting/yamllinter
- services/custom-domains-darklang/cert-manager-clusterrolebinding.yaml
Upgrades involving kubernetes and the dockerfile:
- use the new non-deprecated version of gke cloud plugin
- upgrade kubeconform
- set version of kubeconform to match cluster
- upgrade to dotnet 6.0.5
- fix code to not fail in 6.0.5
- remove unused sos plugin
- upgrade fantomas
- reformat to match fantomas
> Upgrade k8s/dockerfile

- services/qw-deployment/qw-deployment.template.yaml
- services/scheduler-deployment/scheduler-deployment.template.yaml
Turn down queueworkers to nothing.
Removing them is not hard but not completely trivial either, so let's just go down to zero for now.
> Turn deployments down to zero for now

- services/apiserver-deployment-darklang/apiserver-deployment.template.yaml
- services/bwdserver-deployment-darklang/bwdserver-deployment.template.yaml
- services/custom-domains-darklang/darkcustomdomain-nginx-ingress-controller.yaml
- services/exechost-deployment/exechost-deployment.template.yaml
- services/queueworker-deployment/queueworker-deployment.template.yaml
- services/tunnel2-deployment/tunnel2-deployment.template.yaml
Removed limits for dotnet containers.
I left them on for containers that are basically a loop that's running as fast as it
can, or that will be removed shortly
Discussions: 
https://www.reddit.com/r/kubernetes/comments/all1vg/on_kubernetes_cpu_limits/efgyygu/
https://medium.com/inside-sumup/are-kubernetes-cpu-limits-bad-a04430bf54e1
> The prevailing advice is to remove cpu limits.

- .circleci/config.yml
In #4040, I split apart the asset push from the container push. However, the container push was doing something the asset push needed (regenerating etags.json), and so it failed:
https://app.circleci.com/pipelines/github/darklang/dark/3147/workflows/4f15899d-35a1-48cb-bf0c-51c51ca4145d/jobs/33975
This refactors so they can both call the same code.
> Fix breakage from asset/container push

- fsharp-backend/src/Wasm/Wasm.fs
Prior to this, serialization failures led to an infinite loading spinner in the client.
> Blazor analysis result serialization now results in Rollbars

- fsharp-backend/src/Prelude/Prelude.fs
The entire canvasname must fit in a varchar64. (Since that's the length of subdomains
allowed by DNS, this won't have any user-facing effects)
> It should be the entire canvasname that is <= 64

- CODING-GUIDE.md
- fsharp-backend/src/LibBackend/Pusher.fs
- fsharp-backend/src/LibExecution/OCamlTypes.fs
Large pushes are happening because the user is renaming something (probably a DB), that causes a ton of other TLs to be pushed.
For now, it's much much easier to drop these. I'd rather put the effort into making renames not change every toplevel, and this happens rarely and canvases are fairly rarely used by two people at once anyway.
> Don't error when the push is too big

- fsharp-backend/src/BackendOnlyStdLib/LibDarkInternal.fs
- fsharp-backend/src/BwdServer/Server.fs
- fsharp-backend/src/ExecHost/ExecHost.fs
- fsharp-backend/src/HttpMiddleware/CorsV0.fs
- fsharp-backend/src/LibBackend/Canvas.fs
- fsharp-backend/src/LibBackend/CanvasClone.fs
- fsharp-backend/tests/DataTests/DataTests.fs
- fsharp-backend/tests/Tests/ApiServer.Tests.fs
- fsharp-backend/tests/Tests/BwdServer.Tests.fs
- fsharp-backend/tests/Tests/Canvas.Tests.fs
- fsharp-backend/tests/testfiles/internal.tests
This stops us from fetching cors setting from the DB. Instead, we have a table in the code with the only cors settings that remain, and the DB column is no longer used and can be deleted.
The goal here is to simplify the loading code for BwdServer (from a readability perspective).
This feature is not documented anywhere, and only 3 users continue to use it (two of them being us).
> No longer read cors from the DB

- fsharp-backend/src/LibService/Rollbar.fs
This exception was fixed before in a different place, now it's cropping up in exception handling.
Fixes https://rollbar.com/darkops/darklang/items/3312/.
> Fix another exception from bad urls, this one exception handling

- fsharp-backend/src/BackendOnlyStdLib/LibDarkInternal.fs
- fsharp-backend/src/LibBackend/CanvasClone.fs
- fsharp-backend/src/Prelude/Prelude.fs
- fsharp-backend/tests/testfiles/internal.tests
- fsharp-backend/tests/testfiles/language.tests
Removes LibDarkInternal functions that do nothing, and that have been replaced. I checked in honeycomb to see what the usage was for the last month and removed any that were not used which had a successor. I left in some that seemed like they would be useful going forward.
> Remove unused functions

- fsharp-backend/src/Wasm/Wasm.fs
As discovered/discussed in #4059, large requests to the Blazor-powered WASM analysis sometimes resulted in this nasty runtime error, _only_ when built in Release mode with AOT compilation flag on in `Wasm.fsproj`:
(Note: #4059 includes a fair amount of discovery around this issue. If you're reading this in the future, start there)
This PR resolves that. 
It's unclear _exactly_ why this works, but two things have changed:
- the old code had a nested `task{}` and `let!` pair when computing the `result`, before serializing and posting back the result.
- we added a `|> Task.map (fun _ -> ())` at the end of the last `task{}`. Without this, we still get the error
The underlying problem seems to be related to some of { GC, binding scope, `tasks`, AOT/release builds }, but I'm not sure. …
> Prevent failures of large analysis requests to Blazor

- scripts/deployment/_push-assets-to-cdn
Deploying assets took an unreasonably large amount of time, when in fact it should have been pretty quick.
What was happening is that for each file, we were uploading the directory. That is, given N files split into K buckets, we intended to upload K buckets, but in fact uploaded N buckets (and disproportionately the bigger ones of course).
This fixes it to upload K buckets by using a set instead of an array.
> Don't upload one directory per file

- .circleci/config.yml
- Dockerfile
- scripts/build/_dune-wrapper.sh
- scripts/build/_npm-run-build-with-retry
- scripts/build/_rescript-wrapper.sh
- scripts/build/compile
A few more fixes to make CI faster.
Before: 9m22sm
After: 8m7s
There's two changes:
- use a 5% smaller docker container (not a great win)
- figure out (and fix) why dotnet was rebuilding so much (which is that the git checkout mtime was recent, while the CircleCI cached build objects' mtime was not recent).
> More CI speedups

- fsharp-backend/src/BackendOnlyStdLib/LibDarkInternal.fs
- fsharp-backend/src/BackendOnlyStdLib/LibEvent.fs
- fsharp-backend/src/BackendOnlyStdLib/LibHttpClientAuth.fs
- fsharp-backend/src/BackendOnlyStdLib/LibJwt.fs
- fsharp-backend/src/BackendOnlyStdLib/LibStaticAssets.fs
- fsharp-backend/src/LibExecutionStdLib/LibHttpClient.fs
- fsharp-backend/src/LibExecutionStdLib/LibList.fs
- fsharp-backend/src/LibExecutionStdLib/LibString.fs
- fsharp-backend/tests/testfiles/httpclient.tests
These were like this in OCaml so we kept them the same to match during the migration.
> Small improvements to the error messages and signatures

- client/src/appsupport.js
- fsharp-backend/src/Wasm/Wasm.fs
- remove some redundancy in Wasm.fs
- use Exception.getMessages to roll inner exception into returned error message for Blazor errors
> Include inner exception details in Blazor rollbars

- fsharp-backend/src/BackendOnlyStdLib/LibDarkInternal.fs
- fsharp-backend/src/Prelude/Prelude.fs
- fsharp-backend/tests/Tests/Account.Tests.fs
- fsharp-backend/tests/testfiles/internal.tests
I've already disallowed it in the adduser canvas. Now it's disallowed in the insertUser_v2 function.
> Disallow underscores in usernames

- fsharp-backend/src/Wasm/Wasm.fs
Locally, this makes it so I can't reproduce [these](https://github.com/darklang/dark/issues/4099) nasty things.
Maybe we can escape Blazor hell? :)
> Make Wasm/EvalWorker.OnMessage synchronous with .Result

- fsharp-backend/src/LibExecution/OCamlTypes.fs
- fsharp-backend/src/Wasm/Wasm.fs
An empty list `[]` of Secrets is currently being passed through for F# analysis. This fixes that.
> Pass secrets through in F# analysis

- fsharp-backend/src/LibExecutionStdLib/LibDict.fs
- fsharp-backend/src/LibExecutionStdLib/LibOption.fs
- fsharp-backend/src/LibExecutionStdLib/LibResult.fs
- fsharp-backend/src/LibExecutionStdLib/LibString.fs
- fsharp-backend/tests/testfiles/dict.tests
- fsharp-backend/tests/testfiles/result.tests
This excludes LibList fns, which have been separately updated in #4150. This will resolve #4153.
Personally I think this is in the right direction, per a single CLEANUP item in LibList.fs.
> Rename function params of StdLib fns (f -> fn)

- fsharp-backend/src/LibExecutionStdLib/LibDate.fs
- fsharp-backend/tests/testfiles/date.tests
Keep existing fns as-is (while removing CLEANUP annotations) and create new versions of `Date::` `hour`, `minute`, and `second`
> Add new Date fns with correct handling of pre-1970 dates

- fsharp-backend/tests/Tests/Authorization.Tests.fs
We kept seeing a race condition where the tests in
Authorization.Tests.fs caused flakiness in ApiServer.Tests.fs,
due to the sharing of these users. Specifically, access granted
to the test user to the test_admin org.
> Fix tests flaky due to shared use of test and test_admin users

- fsharp-backend/tests/testfiles/staticassets.tests
This corrects a mistake I made in #4200, currently causing `main` builds to fail currently.
Upon CI being happy, I plan to merge this.
> Fix new LibStaticAssets tests; Just/Nothing, not Some/None

- client/src/app/IntegrationTest.res
- client/src/core/Decoders.res
- client/src/core/Encoders.res
- client/src/core/ProgramTypes.res
- client/src/fluid/AST.res
- client/src/fluid/Fluid.res
- client/src/fluid/FluidExpression.res
- client/src/fluid/FluidPrinter.res
- client/src/fluid/FluidShortcuts.res
- client/src/fluid/FluidTokenizer.res
- client/test/FluidFuzzer.res
- client/test/FluidTestData.res
- client/test/TestFluid.res
- client/test/TestRefactor.res
This changes the pipe definition to match the definition on the backend. There were quite a few test errors - fortunately this code is super well tested so I have high but not perfect confidence.
That said, nothing massively bad can break here.
> Change pipe definition to remove impossible states

- fsharp-backend/src/BackendOnlyStdLib/LibDarkInternal.fs
- fsharp-backend/src/LibBackend/Canvas.fs
- fsharp-backend/src/LibBackend/UserDB.fs
- fsharp-backend/src/LibExecutionStdLib/LibResult.fs
- fsharp-backend/tests/TestUtils/LibTest.fs
- fsharp-backend/tests/Tests/LibExecution.Tests.fs
- fsharp-backend/tests/testfiles/internal.tests
We want to move all Apiserver stuff to a dark-editor canvas. A necessary part of this is exposing these functions as LibDarkInternal, which this does.
Also, adds tests and some bug fixes.
> Add a bunch of ApiServer-related functions to LibDarkInternal

- scripts/linting/shellchecker
I noticed it was slow to run the `find` to get all the shellcheck targets.
> Add more exclusions to shellcheck directory searching

- scripts/builder
This makes the build work on macs with new(ish) arm chips. They still build in x86-64, which is what we want because that's the platform we deploy on.
> Make build work on m1/m2 macs

- client/src/util/PrettyDocs.res
- client/test/TestPrettyDocs.res
- fsharp-backend/src/BackendOnlyStdLib/LibDB2.fs
- fsharp-backend/src/LibExecutionStdLib/LibBool.fs
- fsharp-backend/src/LibExecutionStdLib/LibBytes.fs
- fsharp-backend/src/LibExecutionStdLib/LibChar.fs
- fsharp-backend/src/LibExecutionStdLib/LibCrypto.fs
- fsharp-backend/src/LibExecutionStdLib/LibDate.fs
- fsharp-backend/src/LibExecutionStdLib/LibDict.fs
- fsharp-backend/src/LibExecutionStdLib/LibFloat.fs
- fsharp-backend/src/LibExecutionStdLib/LibHttp.fs
- fsharp-backend/src/LibExecutionStdLib/LibHttpClient.fs
- fsharp-backend/src/LibExecutionStdLib/LibHttpClientAuth.fs
- fsharp-backend/src/LibExecutionStdLib/LibInt.fs
- fsharp-backend/src/LibExecutionStdLib/LibJson.fs
- fsharp-backend/src/LibExecutionStdLib/LibList.fs
- fsharp-backend/src/LibExecutionStdLib/LibMath.fs
- fsharp-backend/src/LibExecutionStdLib/LibNoModule.fs
- fsharp-backend/src/LibExecutionStdLib/LibObject.fs
- fsharp-backend/src/LibExecutionStdLib/LibOption.fs
- fsharp-backend/src/LibExecutionStdLib/LibResult.fs
- fsharp-backend/src/LibExecutionStdLib/LibString.fs
- fsharp-backend/src/LibExecutionStdLib/StdLib.fs
- fsharp-backend/tests/TestUtils/LibTest.fs
We have the ability to have pretty docstrings, but we didn't use the formatting for most functions. This adds them for probably about 40-50% of functions, which now look like this:
Also:
- fixes a bug in the format parsing
- reformats untidy and too-long strings in the F# source
- rewrote some comments that were unclear
> Better descriptions

- client/src/core/DType.res
This will resolve https://rollbar.com/darkops/darklang/items/3412
> Include `TFloat` case in `client`'s `DType`.`decodeOld`

- docs/running-against-production.md
I had to use `--hostname` instead of `-hostname`. Not sure if the arg name has changed in recent versions or if it's always been that way.
> Correct ngrok command in docs

- fsharp-backend/src/LibExecutionStdLib/LibExecutionStdLib.fsproj
- fsharp-backend/src/LibExecutionStdLib/LibTuple.fs
- fsharp-backend/src/LibExecutionStdLib/LibTuple2.fs
- fsharp-backend/src/LibExecutionStdLib/LibTuple3.fs
- fsharp-backend/src/LibExecutionStdLib/StdLib.fs
- fsharp-backend/tests/testfiles/tuple.tests
This will resolve #3309, and is a part of #4265.
This adds the following stdlib fns:
- `Tuple2::pair`
- `Tuple2::first`
- `Tuple2::second`
- `Tuple2::swap`
- `Tuple2::mapFirst`
- `Tuple2::mapSecond`
- `Tuple2::mapBoth`
- `Tuple3::first`
- `Tuple3::second`
- `Tuple3::third`
- `Tuple3::mapFirst`
- `Tuple3::mapSecond`
- `Tuple3::mapThird`
- `Tuple3::mapAllThree`
> Add StdLib fns for Tuples

- fsharp-backend/src/BackendOnlyStdLib/LibDarkInternal.fs
- fsharp-backend/src/BackendOnlyStdLib/LibStaticAssets.fs
- fsharp-backend/src/LibBackend/StaticAssets.fs
- fsharp-backend/tests/testfiles/internal.tests
This PR will expose and test 3 new functions for use in `dark-editor`, to support an eventual replacement of the OCaml-supported static asset upload. It's a piece of #4259.
The three functions will support `start`ing, `finish`ing, and `delete`-ing a deploy.
> Expose more internal staticassets fns for uploads

- fsharp-backend/src/LibExecutionStdLib/LibTuple2.fs
- fsharp-backend/src/LibExecutionStdLib/LibTuple3.fs
While I disabled the creation of tuples in Fluid, I forgot that tuples could be created by way of Tuple2::create and Tuple3::create. This disables those functions for now.
> Disable Tuple2:: and Tuple3:: fns

- fsharp-backend/src/ApiServer/Api/APIOps.fs
I noticed that these bindings were unused; removed now.
> Remove unused emptyHandler bindings from APIOps.fs

- fsharp-backend/src/LibExecution/ProgramTypesToRuntimeTypes.fs
- fsharp-backend/tests/Tests/ProgramTypes.Tests.fs
Allow deleting the whole part of a float. The client allowed it, and the server would save it, but there would be a runtime exception.
> Allow floats where the whole number part is empty

- client/src/api/API.res
- client/src/api/APIAddOps.res
- client/src/core/Encoders.res
- integration-tests/tests.ts
TLSavepoints haven't been persisted alongside recent ops, as they have prior - this is causing Undo to not work for recently-changed code.
The relevant integration test has been working, because the TLSavepoint ops were persisted in the actual integration test _file_, not part of the tested UX. As such, a follow-up will be to add another integration test that ensures TLSavepoint is added appropriately (or just adjust the existing one).
> Add Savepoints to Ops in Client, to re-support Undo functionality

- client/src/app/Main.res
- client/src/canvas/ViewSidebar.res
- client/src/components/Settings/SettingsContributing.res
- client/src/components/Settings/SettingsContributingView.res
- client/src/fluid/Fluid.res
- client/src/fluid/FluidTokenizer.res
- client/src/fluid/FluidTokenizer.resi
- client/src/fluid/FluidTypes.res
- client/src/fluid/FluidUtil.res
- client/src/ui/ViewUtils.res
- client/test/FluidTestData.res
- client/test/TestFluid.res
- client/test/TestFluidAutocomplete.res
- client/test/TestFluidPattern.res
- client/test/TestFluidSelection.res
- client/test/TestViewBlankor.res
Problems I'm solving for:
- I'm tired of flipping this hardcoded flag on/off when I'm developing Tuple stuff
- I'd like others to be able to use Tuples and provide feedback without having to pull the Dark source code and flip the hardcoded flag
What this does:
- renames the "Tools" section of Contributor Settings to "General"
- adds a new "Allow Tuples" setting to the Contributor Settings
use _it_ rather than the hardcoded `bool` value to determine if Fluid should allow Tuples to be created
---
Outstanding problem:
The settings being updated doesn't seem to propogate to Fluid immediately, so a refresh is currently required for the tuple setting to take effect. This is likely due to the `ViewUtils.createVS` fn being called so rarely (i.e. only when the TLID or something big is changing).
> Add "allow tuples" contributor setting

- client/src/fluid/Fluid.res
- client/test/TestFluid.res
- fsharp-backend/tests/TestUtils/TestUtils.fs
When you're at the start of an expressions, pressing enter should insert a new line (which at the moment means a let). That mostly works, but there were two places it didn't:
> Allow pressing enter in more expression bodies

- client/styles/_fluid.scss
> Make match arrows match the style of other arrows

- fsharp-backend/src/BwdServer/Server.fs
- fsharp-backend/tests/Tests/HttpClient.Tests.fs
It is possible to throw exception during `BwdServer.runDarkHandler`, but after the Http body has started to be written back to the client. Our attempt to create an error response after this point cause an exception.
This is the cause of https://rollbar.com/darkops/darklang/items/3471/, which has the message "Headers are read-only, response has already started.".
This adds logging for the actual exception, and prevents throwing the extra exception.
> Don't fail while handling exception

- client/styles/_fluid.scss
Note the position of the "l" in `let`
Before:
After:
> Fix the uneven spacing due to ligatured arrows

- client/src/fluid/FluidShortcuts.res
- client/src/fluid/FluidTypes.res
- client/test/FluidTestData.res
- client/test/TestFluid.res
- client/test/TestFluidPattern.res
This replaces #4434 - the tests are now in `TestFluidPattern`, which has been updated to support tests that only `render`.
> Add Fluid tests around the Tuple match pattern

- client/src/app/Main.res
This hides the error from https://github.com/darklang/dark/issues/4161#issuecomment-1237454993
I tried finding the cause as error makes it look like there's a null being added to a dictionary somewhere during analysis. However, I couldn't find any dictionary of the right type, and I did some printf debugging that also didn't turn up anything, so I think this is happening in the framework.
Given the error doesn't seem to break anything, maybe the best approach is to ignore it for now.
> Hide the error - it doesnt seem to break anything afaict

- client/src/fluid/Fluid.res
- client/test/TestFluidPattern.res
Given the following code involving a "tuple match pattern":
```
match (1,2)
(|"one",2) -> "success"
```
with the cursor at the noted spot, typing `1` should do nothing, leaving the cursor in place.
Instead, prior to this change, it would turn into:
```
match (1,2)
(1|,2) -> "success"
```
Logic has been adjusted to not overwrite non-blank patterns in such a case, and a test around this has been added.
> Bugfix: don't allow tuple pattern parts to be overwritten

- client/src/fluid/Fluid.res
- client/test/TestFluid.res
- client/test/TestFluidPattern.res
Given the Dark code `let x = (___,|2,3)`, hitting `backspace` changes it to `let x = (|___,3)`, with the cursor at the _start_ of the blank.
The equivalent, for the tuple match pattern, was different. It turned:
```
match (1,2)
(___,|2,3) -> ___
```
into
```
match (1,2)
(|___,3) -> ___
```
This was done by updating `caretTargetForEndOfPattern` to `offset` the cursor position by `0` rather than by `3`.
There was a relevant note in place, and this seemed an appropriate time to follow the note.
> Put cursor at _start_ of blank pattern when removing elements, not end

- client/src/fluid/Fluid.res
- client/test/TestFluidPattern.res
Given this Dark code:
```
match (1,2)
(1,2|) -> ...
```
, with the cursor at the noted position, a `)` input snow properly skips over the tuple's closing `)`.
> Swallow ) input at end of tuple pattern

- client/src/analysis/Runtime.res
- client/src/analysis/RuntimeTokenizer.res
- client/src/fluid/Fluid.res
- client/src/fluid/FluidAutocomplete.res
- client/src/fluid/FluidExpression.res
- client/src/fluid/FluidTokenizer.res
- client/src/fluid/FluidTypes.res
- client/src/fluid/FluidView.res
- client/src/toplevels/ViewDB.res
- client/src/toplevels/ViewData.res
- client/src/util/Util.res
- client/test/TestFluidAutocomplete.res
- client/test/TestUtils.res
- docs/dblock-serialization.md
- fsharp-backend/src/LibExecution/DvalReprDeveloper.fs
- fsharp-backend/src/LibExecution/Interpreter.fs
- fsharp-backend/testfiles/execution/float.tests
- fsharp-backend/testfiles/execution/int.tests
- fsharp-backend/testfiles/execution/list.tests
- fsharp-backend/tests/Tests/DvalRepr.Tests.fs
- fsharp-backend/tests/Tests/Execution.Tests.fs
- make AST debugging representation a little bit clearer
- ensure lambda arguments are always traced (so they don't spin)
- use better defaults for lambda preview execution (with test)
- refactor autocomplete literals (allows removing some dead code)
- refactor to catch a few places secrets weren't hidden
- make backend and frontend toRepr implementations match
- remove some dumb stuff from the backend DvalReprDeveloper format
- make a copy of the FluidTokenizer for runtimeTypes, and use it to display lambda live values (see below)
> A number of fixes related to lambdas

- client/src/fluid/Fluid.res
- client/test/FluidTestData.res
- client/test/TestFluid.res
When backspacing over the keyword of an expr, when that expr has contents, intentionally does nothing.
This changes it in the case that the expression contains exactly one expression.
> Backspacing fixes

- client/styles/_fluid.scss
I think I overdid it with the string background color. This turns it down by about half. It's still there, just more subtle. It still provides a little contrast against the background so you can see spaces on it, it just no longer overwhelms the entire handler.
Before:
After:
> Tone down the string background a bit

- fsharp-backend/src/BackendOnlyStdLib/LibDarkInternal.fs
- fsharp-backend/src/LibExecutionStdLib/LibString.fs
- fsharp-backend/src/LibExecutionStdLib/LibUuid.fs
- fsharp-backend/src/LibExecutionStdLib/StdLib.fs
- fsharp-backend/testfiles/execution/internal.tests
- fsharp-backend/testfiles/execution/uuid.tests
- fsharp-backend/tests/TestUtils/LibTest.fs
A lot of our internal functions use usernames and canvas names instead of IDs. That can make things a little bit ambiguous, especially in the future if we choose to allow users to rename themselves.
Instead, we want to use canvasIDs and UserID where possible. This ads two functions that help with that. It also renames `String::toUUID` to `Uuid.parse`, which is better naming.
> Use IDs more

- client/src/fluid/Fluid.res
- client/test/TestFluidClipboard.res
- generally documents `reconstructExprFromRange`
- adds notes around limitations in reconstructing `Constructor` patterns
- adds _basic_ support for reconstructing `Tuple` patterns
- starts to fill in tests around this functionality
- fixes a bug: given a `match` with multiple patterns, if you select `match` through the first pattern, the reconstruction would mistakenly create a blank 'case' per each unselected line.
> Fluid Pattern Reconstruction fixes

- client/src/appsupport.js
Too many false positives
I tried to find another way to do this, but it seemed too complicated. BlazorWorker.js spams errors to the onmessage handler, and it seems really hard to try to track them.
> Don't show any blazor worker errors for now

- client/src/toplevels/ViewHandler.res
The key did not have the url in it, and so the DOM did not update when the url changed.
> When url changes, update "open-in-new-window"

- client/src/app/Main.res
We previously hid an error from the GC in .NET analysis which seemed harmless, but we didn't catch all cases. The following error still got through:
> Error in JS: Uncaught Error: System.ArgumentNullException: ArgumentNull_Generic Arg_ParamName_Name, key
at System.Collections.Generic.Dictionary`2[[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Int32, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Remove(Object )
at System.Runtime.InteropServices.JavaScript.Runtime.ReleaseJSOwnedObjectByGCHandle(Int32 gcHandle)
Make the rule to ignore it more generic to catch this one too
> Be less specific to catch another error

- client/src/canvas/View.res
- client/src/canvas/ViewErrorRailDoc.res
- client/src/fluid/FluidAutocomplete.res
- client/src/fluid/FluidAutocomplete.resi
- client/styles/_doc.scss
In both places that docs are used, use the same code to generate them. Also show the return type of a called function.
> Use the same documentation box in autocomplete and when showing docs

- client/src/analysis/RuntimeTokenizer.res
- client/src/fluid/FeatureFlags.res
- client/src/fluid/Fluid.res
- client/src/fluid/FluidDebugger.res
- client/src/fluid/FluidPrinter.res
- client/src/fluid/FluidTokenizer.res
- client/src/fluid/FluidTokenizer.resi
- client/src/fluid/FluidTypes.res
- client/test/FluidFuzzer.res
- client/test/FuzzTests.res
- client/test/TestFluid.res
- client/test/TestFluidAutocomplete.res
- client/test/TestFluidClipboard.res
- client/test/TestFluidPrinter.res
- docs/unittests.md
Reconstruction (what happens when you copy/paste some Dark code) of Exprs has been generally solid in Fluid, but the implementation for reconstructing match patterns was hacky, and did not support reconstructing only some of a nested pattern (i.e. if a Tuple pattern or Constructor pattern was partially highlighted when cutting/copying, the whole thing would be reconstructed - even the unselected parts).
This is how it used to operate:
and here's with the fix
---
This broke down as follows:
- in `FluidTokenization.res`, organize the code to have all of the actual 'tokenization' be in one area visually.
- extend tokenization MP inputs (without needing to pass in the wrapping `match` expr)
- rename `FluidTokenization.tokensForEditor` to `.tokenizeForDebugger`
previously, we had …
> Rewrite fluid match pattern reconstruction

- client/src/api/API.res
- fsharp-backend/src/ApiServer/ApiServer.fs
- fsharp-backend/src/ApiServer/Templates/ui.html
This is a fun little performance hack - let's preload initial_load and packages API calls!
Note, only the last commit is new here.
There's a brief window here where someone might be loading an API call that doesn't exist (on old servers), but it'll be brief, only affect loading the editor for the first time, and be easy to resolve by refreshing, so probably fine to ship this in one PR.
> Preload initial APIs

- .circleci/config.yml
- Dockerfile
- docs/production/static-assets.md
- scripts/deployment/_push-assets-to-cdn
- scripts/deployment/deploy-lock-all-clear
- scripts/deployment/deploy-lock-all-list
- scripts/deployment/deploy-lock-one-add
- scripts/deployment/deploy-lock-one-remove
- scripts/production/create-download-gcp-db-bucket
- scripts/production/download-gcp-db
Changelog:
```
Internal:
- Use gcloud storage commands instead of gsutil for deployment
```
Google cloud has a separate tool called `gsutil`, which we use to deploy darklang.com assets and also for the deploy lock. However, it's a little annoying as the tool requires us to install a python module to have reasonably fast deployment.
They recently released a new component to gcloud which replaces this: `gcloud storage`. It means we don't need the python module and it's also supposedly much much faster.
Also updates some dependencies in the dev container
> Move away from gsutil

- scripts/deployment/_push-assets-to-cdn
I believe that this is what [broke some deploys yesterday](https://app.circleci.com/pipelines/github/darklang/dark/4231/workflows/55546e52-b4b1-48bb-ab32-65ad97806eff/jobs/43940).
[This commit](https://github.com/darklang/dark/commit/3ad6c3d28b956fa63fd7f18788777721950a46ee) introduced an errant `"`
> Remove errant quote

- fsharp-backend/src/LibExecutionStdLib/LibFloat.fs
- fsharp-backend/src/LibExecutionStdLib/LibString.fs
- fsharp-backend/src/LibExecutionStdLib/StdLib.fs
- fsharp-backend/testfiles/execution/float.tests
Changelog:
```
Standard library:
- rename `String::toFloat_v1` to `Float::parse_v0`
```
Fixes #4503
> Rename String::toFloat to Float::parse

- .circleci/config.yml
- Dockerfile
- docs/production/static-assets.md
- scripts/deployment/_push-assets-to-cdn
No changelog
I tried to improve the speed of deploys by switching to `gcloud storage cp` from `gsutil cp`, but ended up breaking things. So this goes back to the old one.
> Stick to gsutil

- client/src/fluid/Fluid.res
- client/test/TestFluid.res
- client/test/TestFluidClipboard.res
Changelog:
```
Editor improvements:
- deleting a selected range of code is now more accurate
```
This will fix #4264
Our process to delete a "selection" of Dark code is currently pretty naive, and we're trying to make it much more solid and correct.
Currently, `Fluid.deleteCaretRange` deletes from the end of the selection to the start of the selection character by character.
In order to determine when to stop deleting, it checks for:
- is the 'current' position `<=` the selection's start pos? If so, we're done.
- has the last 'delete' done anything (changed our pos or changed the AST)? if not, stop, so we don't loop forever.
This falls short in situations where the position changes throughout the deletion process.
For example, consider if you start with the AST `(123, 456)` and select …
> Use CaretTargets to handle deleting selection

- client/src/canvas/ViewSidebar.res
- package-lock.json
- package.json
- tailwind.config.js
No changelog
New feature I saw in the dependabot changelog. Seems much nicer, and always better to use a first-class thing rather than a plugin. We also no longer need to declare them, so they're easier to use.
> Use tailwind 3.2 nested groups

- client/src/app/AppTypes.res
- client/src/app/CursorState.res
- client/src/app/Main.res
- client/src/fluid/Fluid.res
- client/src/fluid/FluidEditorView.res
- client/src/forms/Entry.res
- client/src/util/Native.res
- package-lock.json
- package.json
No changelog
Fixes #4413.
This moves off our abandoned fork of bucklescript-tea, to a much newer (but still not latest) version of our new fork, rescript-tea.
renderCallback was never accepted upstream, and they went with a much nicer approach using subscriptions. Some other functions were only in our fork and so I moved them to rescript-webapi instead (which is what should happen for all our uses of Tea.Node).
> Move to later version of bs-tea

- integration-tests/package-lock.json
- integration-tests/package.json
- integration-tests/run.sh
No changelog
When integration tests timeout, it's hard to know the cause. This searches through the json output to find the tests which were skipped, which I take to mean "were not complete when timed out".
We shouldn't really need this, as the test should a) fail after it's own timeout and b) be reported after the global timeout imo, but those aren't happening, so here we are.
I've reported these to playwright as well: https://github.com/microsoft/playwright/issues/18250 and https://github.com/microsoft/playwright/issues/18248
> Print timedout tests in Playwright

- client/src/api/API.res
- fsharp-backend/src/ApiServer/Templates/ui.html
Changelog:
```
Editor
- preload first API requests to load the editor faster
```
I had thought this worked but evidently the headers were wrong, which the devtools reported.
You can see packages being loaded twice:
> Fix preload of API calls

- integration-tests/tests.ts
- integration-tests/utils.ts
Changelog:
```
Internal improvements
- Improve integration tests using non-fluid entry boxes
```
Before pressing Ctrl-a, ensure that the box is focussed. Then wait for it to be selected after ctrl-a is pressed.
This fixes a lot of flaky tests, and I can get integration tests to pass much more frequently with this.
> Make selectAll more resilient to failure

- .circleci/config.yml
No changelog
Try to speed up the build. The .net cache can get stale, so use a new one each week. That will slow down the first build of the week, but I expect this to shave a minute or two off all subsequent builds
> Try a fresh cache each week for .net

- .circleci/config.yml
No changelog
I've added a few F# projects within #4542, and a merge into `main` seems to be failing. Maybe this is relevant?
> Increase fsharp-blazor cache from v4 to v5

- integration-tests/run.sh
Changelog:
```
Internal
- allow integration tests to loop
```
By looping the integration tests with `--loop`, we can find flaky tests. Often it takes 4-15 loops to find a flaky one. It's also really useful to combine with `--pattern`, to debug one test that you know if flaky
> Add --loop flag to integration tests

- services/custom-domains-darklang/cert-manager-issuer.yaml
Changelog:
```
Internal changes:
- don't let cert-manager prevent us from scaling down
```
Cert-manager pods aren't marked as safe-to-evict in k8s, so the GKE autoscheduler will do a bad job of scaling down when it sees them (if someone has a domain added or changes their domain's DNS).
As a result, we've been running with 6 VMs, when we could reasonably have been running with 4.
```
dark@dark-dev:~/app$ kubectl explain issuer.spec.acme.solvers.http01.ingress.podTemplate
KIND:     Issuer
VERSION:  cert-manager.io/v1
RESOURCE: podTemplate <Object>
DESCRIPTION:
Optional pod template used to configure the ACME challenge solver pods used
for HTTP01 challenges.
FIELDS:
metadata	<Object>
ObjectMeta overrides for the pod used to solve HTTP01 challenges. Only the
'labels' and 'annotations' fields …
```
> Don't let cert-manager pods prevent us from scaling down

- client/src/analysis/Functions.res
- fsharp-backend/src/LibExecutionStdLib/LibList.fs
- fsharp-backend/src/Prelude/Prelude.fs
- fsharp-backend/testfiles/execution/list.tests
Changelog:
```
Standard library
- add `List::partition_v0` function to split a list into 2 lists
```
---
I was recently reaching for this function and found that we didn't have it.
For now, it's hidden behind our experimental tuple usage editor setting.
> Add List::partition_v0 stdlib fn

- fsharp-backend/src/LibExecution/RuntimeTypes.fs
- fsharp-backend/src/LibExecutionStdLib/LibList.fs
Changelog:
```
Standard Library
- fix lambda argument names for `List::all_v0`
Internal improvements
- add assertion that all standard library functions that take lambdas have default names provided for the lambda arguments
```
> Fix List::all parameter list

- client/src/forms/Autocomplete.res
- fsharp-backend/src/LibExecutionStdLib/LibChar.fs
- fsharp-backend/testfiles/execution/char.tests
Changelog:
```
Standard Library
- Add functions that operate on characters: `Char::isUppercase_v0`, `Char::isLowercase_v0`, `Char::toUppercase_v1`, `Char::toLowercase_v1`, `Char::isDigit_v0`, `Char::isASCII_v0`, and `Char::isASCIILetter_v0` 
Editor
- Allow using `Char` as a function parameter type and return type
```
Fixes #4625
> Add some Char functions

- client/src/appsupport.js
- client/src/components/Settings/SettingsInvite.res
- client/src/components/Settings/SettingsInviteView.res
- client/src/components/Settings/SettingsViewComponents.res
Changelog:
```
Internal 
-  Update the styling of settings invite.
```
**Changes:**
- Some styling changes in settingsInviteView.
- Remove emailInput from components and replace it with the existing input.
- Reuse more components.
- Remove validateEmail function from appsupport and access validator package directly via an external.
**Before -> After**
This was tested successfully against production. If you want any changes please let me know.
**Note:**
- I definitely did not change 376 files (only 4 files were changed). I got 372 files changed after pulling the latest changes from the remote repo. I wasn't sure if I should commit these. If I did something wrong please let me know and I'll revert these commits.
- Not sure what to put in the changelog.
> Redo settings invite

- backend/src/Prelude/Prelude.fs
No changelog
I noticed that we've been ignoring the `metadata` arg of `Prelude.printException`.
This is mostly only relevant for local development or emergencies when we can't reach Rollbar, but figured it's worth fixing.
> Include given metadata when printing exceptions

- backend/src/ApiServer/ApiServer.fs
Changelog:
```
Internal
- include dark client version in apiserver rollbars
```
> Include dark client version in apiserver rollbars

- backend/src/BackendOnlyStdLib/LibDarkInternal.fs
- backend/testfiles/execution/internal.tests
Changelog:
```
Internal
- add internal function that returns the git hash of the server's current/latest deploy
```
This is to support #4648 - with this fn exposed, an endpoint in `dark-editor` may be defined to expose the current deploy version, which the `client` may then call out to, in order to see if it's at the latest build.
Questions for review:
- is `LibService.Config.buildHash` something we can/should rely on? Locally, it returns just `"dev"` but I understand it will contain the actual hash outside of local development.
- should the function instead be `::buildHash` or `::buildVersion` or `::latestBuild` or something else?
- I haven't written tests around this. I could test that it returns `"dev"`? Not sure what's best here.
> Add DarkInternal::serverBuildHash fn that returns the git hash of the server's current deploy

- .circleci/config.yml
- .devcontainer/devcontainer.json
- .gitignore
- Dockerfile
- scripts/build/compile
- tf/.terraform.lock.hcl
- tf/main.tf
- tf/service_env_vars.tf
No changelog (changes aren't effected yet)
We'd like to move away from kubernetes, and Google Cloud Run is a great option for that:
- does everything we need with minimal config
- only bills when CPU is in use
- autoscales
- no control plane to manage/upgrade
This is the start of the setting it up - I have it working in practice with these settings, but still more testing and stuff before it's ready to put it into production. This doesn't do any deployment, and users can't reach this.
- adds terraform
- adds terraform config to run bwdserver in cloud run
- creates an file with env vars and secrets that should replace config/gke-builtwithdark (can be used for queues as well)
This should be safe to merge as it's not actually connected to anything userfacing.
Remaining work is in #4663.
> Add Cloud Run

- client/src/api/API.res
- client/src/app/AppTypes.res
- client/src/app/Main.res
- client/src/components/Settings/SettingsContributingView.res
- client/src/core/Types.res
Changelog:
```
Editor
- refresh the editor when it is outdated and inactive
```
How this works:
- `appsupport.js` listens for changes in whether the page is in focus or not, with `windowFocusChange`
- upon change of hidden/visible, it sends a message to a `BrowserSubscription` in ReScript land, which in turn triggers a `PageVisibilityChange` `Msg`
- that triggers a `PageVisibilityChange` `Msg`, which results in an update to a `pageVisibility` field in our main `model`
- new: the 'hidden' variant of `PageVisibility` now has a `since` field in it, which is used to track how long it's been since a page became hidden
- separately, a timer runs every minute, triggering a `CheckIfClientIsOutdated` `Msg`; that results in an API call being made to a new endpoint in `dark-editor`, made possible by …
> Refresh client hourly when inactive

- backend/src/LibExecutionStdLib/StdLib.fs
- client/src/canvas/View.res
- client/src/components/Settings/SettingsContributing.res
- client/src/components/Settings/SettingsContributingView.res
- client/src/fluid/Commands.res
- client/src/fluid/FluidAutocomplete.res
- client/src/fluid/FluidAutocomplete.resi
- client/src/fluid/FluidExpression.res
- client/src/fluid/ShortCircuitingBinOpDeprecation.res
- client/test/FluidTestData.res
- client/test/TestFluidAutocomplete.res
Changelog:
```
Editor
- default to short-circuiting `||`/`&&`
- deprecate old `||`/`&&` functions
- add `convert-to-short-circuiting` command to migrate from old `||`\`&&` functions
```
Removes the old settings, defaults to the new expressions, deprecates old expressions, and updates docs/deprecation settings. Also adds a command to convert automatically.
Deprecated old version
Doc for new version
I'm not super happy with the docstring or the name `convert-to-short-circuiting`. Advice appreciated.
> Use new short-circuiting and/or

- .circleci/config.yml
- .circleci/gcp-workflow-identity-config.json
No changelog
This re-enables CircleCI, using OIDC.
This only provides a working token to GCP under specific situations, and for the length of the build only. Right now it's limited to only members of the Github group for engineers (and only needed for deploys).
> Reenable circleci

- .circleci/config.yml
No changelog
We had a single auth command, but it's both faster and more secure to just auth to what we need when we need it (that way, in the event of trouble, we have fewer logs to read to know the impact of the trouble).
> Split authentication to where it's needed and don't reauthenticate

- client/src/fluid/FluidAutocomplete.res
- client/src/ui/PrettyDocs.res
- tailwind.config.js
No changelog
Followup to the New documentation box design PR #4664 
- Styled the deprecated function name with our usual function color and changed the font to font-code.
- Used `typ` instead of `\"type"`.
- Removed the added colors.
- Used colors from our color palette, and used different colors  for the foreground and background.
**Function name:**
**Type error:**
Still experimenting with color options for the foreground and background in the types. I would appreciate your input on whether a colored or grey background would be more suitable.
> New documentation box design PR -followup

- client/src/canvas/View.res
- client/src/components/Tutorial.res
- client/src/components/UserTutorial.res
- client/src/fluid/FluidAutocomplete.res
- client/styles/_canvas.scss
- client/styles/_variables.scss
- tailwind.config.js
Changelog:
```
Internal improvements
-  Convert the tutorial toolotips to Tailwind.
```
**Questions:**
1. I came across this note while converting the tutorial tooltip to tailwind:
`" NOTE: This will change in the future to pretty tool tips, this is just an inbetween state"`
If you have a general idea of the things you want to be changed please let me know. For now it is just converted to tailwind.
2. The tooltips for the sidebar elements are converted to Tailwind but they are not used currently. Re-adding them was mentioned as a followup to this PR #4511. Should I re-add them? (I am not sure how they would look like with the current popups we have)
> Convert parts of canvas to tailwind

- .circleci/config.yml
- scripts/deployment/_deploy-lock-request
- scripts/deployment/deploy-lock-all-clear
- scripts/deployment/deploy-lock-all-list
- scripts/deployment/deploy-lock-one-add
- scripts/deployment/deploy-lock-one-remove
Changelog:
```
Internal
- Move deployment lock to a darklang canvas
```
The deploy lock uses a storage bucket, which requires cloud permissions to be put almost everywhere during a deploy.
This reimplements the deploy lock as a simple dark DB, in https://darklang.com/a/ops-circleci, and rewrites the deploy lock scripts to use it.
There is a secret in that canvas already. For deploying locally, which we almost never do, we could stop using the deploy lock perhaps, or have a key locally. I'm leaving that decision to a later day, when we have more experience with how the goes.
> Move deploy lock to a darklang canvas

- docs/adding-a-secret.md
- docs/production/db-creds-rotation.md
Changelog:
```
Internal:
- make it easier to rotate DB credentials
```
This provides a guide to rotating the DB credentials. I haven't done the steps marked "done" but will before merging.
> Add overview doc of the DB password rotation

- client/src/fluid/FluidAutocomplete.res
- client/src/ui/PrettyDocs.res
- client/test/TestPrettyDocs.res
No changelog
This fixes some broken things I've noticed in the documentation box.
List::sortBy function 
and 
Functions with long names
> Fix documentation box overflow issue

- client/src/fluid/FluidAutocomplete.res
Changelog:
No changelog
**Problem**
When a function is selected, the width of the documentation box expands but the function name stays clipped.
**Fixed**
> Fix fn-name clip in the doc-box

- backend/src/BackendOnlyStdLib/LibCrypto.fs
- backend/src/BackendOnlyStdLib/LibJwt.fs
- backend/src/BackendOnlyStdLib/LibX509.fs
- backend/src/ClientTypes2BackendTypes/UI.fs
- backend/src/LibExecution/RuntimeTypes.fs
- backend/src/LibExecutionStdLib/LibBool.fs
- backend/src/LibExecutionStdLib/LibBytes.fs
- backend/src/LibExecutionStdLib/LibChar.fs
- backend/src/LibExecutionStdLib/LibCrypto.fs
- backend/src/LibExecutionStdLib/LibDate.fs
- backend/src/LibExecutionStdLib/LibDict.fs
- backend/src/LibExecutionStdLib/LibFloat.fs
- backend/src/LibExecutionStdLib/LibHttp.fs
- backend/src/LibExecutionStdLib/LibHttpClient.fs
- backend/src/LibExecutionStdLib/LibHttpClientAuth.fs
- backend/src/LibExecutionStdLib/LibInt.fs
- backend/src/LibExecutionStdLib/LibJson.fs
- backend/src/LibExecutionStdLib/LibList.fs
- backend/src/LibExecutionStdLib/LibMath.fs
- backend/src/LibExecutionStdLib/LibNoModule.fs
- backend/src/LibExecutionStdLib/LibObject.fs
- backend/src/LibExecutionStdLib/LibOption.fs
- backend/src/LibExecutionStdLib/LibResult.fs
- backend/src/LibExecutionStdLib/LibString.fs
- backend/src/LibExecutionStdLib/LibTuple2.fs
- backend/src/LibExecutionStdLib/LibTuple3.fs
- backend/src/LibExecutionStdLib/LibUuid.fs
- backend/tests/TestUtils/LibTest.fs
Changelog:
```
Standard Library
- mark more functions as Not Queryable instead of Unknown
```
The remaining functions are queryable (but we're not doing them right now), so let's remove the TODO from the name.
No effect on the API/client.
> Address NotYetImplementedTODO

- backend/src/LibExecutionStdLib/LibInt.fs
- backend/testfiles/execution/int.tests
- scripts/formatting/pre-commit-hook.sh
Changelog:
```
Area of change
- Int.random_v1 
```
For a case, `Int.random_v1 0 1` always returns 0  
Increasing an upper bound on 1 for this case. 
Run several times the bunch of 10 tests `Int.random_v1 0 1 = 1` and check that at least one test get value 1. In fact, 30-60% of tests were passed. 
yes
> Fix Int.random to correct work on range 0 1

- backend/src/LibExecutionStdLib/LibInt.fs
- backend/src/LibExecutionStdLib/LibList.fs
- backend/testfiles/execution/int.tests
- backend/testfiles/execution/list.tests
Changelog:
```
Standard library
- update Int::random to be inclusive in more scenarios
- add List::unique_v0 - like List::uniqueBy_v0, but without a fn required as input
```
Just as I'd expect `Int::random 0 1` to return 0 or 1, I'd expect `Int::random 0 2` to expect any of {0, 1, 2}. Do you agree, @pbiggar? If so, I think we can update the impl to reflect this.
> Update Int::random; add List::unique

- backend/src/LibExecutionStdLib/LibFloat.fs
- backend/src/LibExecutionStdLib/LibInt.fs
- backend/testfiles/execution/float.tests
- backend/testfiles/execution/int.tests
```
- Float clamp and Int power 
```
Functions using DError (sometimes called err) or Exception.raiseCode should return a Result instead
Refactoring to change return type to Result 
Modified tests were passed.
> Float clamp and Int power return Result

- backend/src/BackendOnlyStdLib/LibHttpClient.fs
- backend/testfiles/execution/httpclient.tests
```
- HttpClient.request
```
Functions using DError (sometimes called err) or Exception.raiseCode should return a Result instead
Refactoring to change return type to Result
Modified tests were passed.
> HttpClient.request returns a Result in all cases

- .circleci/config.yml
- Dockerfile
- backend/src/BackendOnlyStdLib/LibDB.fs
- backend/src/LibBackend/Db.fs
- backend/src/LibBackend/SqlCompiler.fs
- backend/src/LibBackend/UserDB.fs
- backend/src/LibExecution/DvalReprDeveloper.fs
- backend/src/LibExecution/DvalReprInternalQueryable.fs
- backend/src/LibExecution/RuntimeTypes.fs
- backend/src/LibExecutionStdLib/LibNoModule.fs
- backend/src/Parser/Parser.fs
- backend/testfiles/execution/db.tests
- backend/testfiles/execution/dict.tests
- backend/testfiles/execution/http.tests
- backend/testfiles/execution/language.tests
- backend/testfiles/execution/list.tests
- backend/testfiles/execution/result.tests
- backend/testfiles/execution/string.tests
- backend/tests/FuzzTests/ExecutePureFunctions.FuzzTests.fs
- backend/tests/FuzzTests/InternalJson.FuzzTests.fs
- backend/tests/Tests/DvalRepr.Tests.fs
- backend/tests/Tests/TypeChecker.Tests.fs
- scripts/devcontainer/_start-background-services
This redoes a lot of how we store values, to remove inconsistencies, bugs, and weirdness. With those solved it modestly expands the types and tests handled.
DvalReprInternalQueryable is the json-based serialization that we use to store user values in the DB. It's converted to jsonb, and SqlCompiler then queries the stored results using Postgres' jsonb query functions. The SqlComiler thus obviously depends on the structure of the saved data, as created by DvalReprInternalQueryable.
The major problem with the format was that it didn't use the DB's schema to decide how to save data. Thus, when decoding the data, it guessed based on what it saw. If you had a record in the format `{ type: string, date: string }` then it would parse it as a date, not a record with two fields.
By including the …
> Fix bugs and expand storage of Dvals

- backend/src/LibExecution/Interpreter.fs
- backend/testfiles/execution/language.tests
Changelog:
```
Language:
- calling a non-existant function now returns an error
```
There may be some side effects if the trace data is missing on the client, we'll look into that later I suppose
> When the fn doesn't exist, error.

- backend/serialization/vanilla_ClientTypes-Analysis-PerformAnalysisParams_function.json
- backend/serialization/vanilla_ClientTypes-Analysis-PerformAnalysisParams_handler.json
- backend/serialization/vanilla_ClientTypes-Runtime-Dval-T_complete.json
- backend/serialization/vanilla_LibBackend-TraceCloudStorage-CloudStorageFormat_simple.json
- backend/serialization/vanilla_LibExecution-AnalysisTypes-TraceData_testTraceData.json
- backend/serialization/vanilla_LibExecution-DvalReprInternalRoundtrippable-FormatV0-Dval_complete.json
- backend/serialization/vanilla_Microsoft-FSharp-Core-FSharpResult-2-System-Tuple-4-System-Guid-System-Collections-Generic-Dictionary-2-System-UInt64-ClientTypes-Analysis-ExecutionResult-System-Int32-NodaTime-Instant-System-String-_simple.json
- backend/src/ClientTypes/ClientRuntimeTypes.fs
- backend/src/ClientTypes2ExecutionTypes/RuntimeTypes.fs
- backend/src/LibExecution/DvalReprDeveloper.fs
- backend/src/LibExecution/DvalReprInternalQueryable.fs
- backend/src/LibExecution/DvalReprInternalRoundtrippable.fs
- backend/src/LibExecution/RuntimeTypes.fs
- backend/src/LibExecutionStdLib/LibList.fs
- backend/src/LibExecutionStdLib/LibNoModule.fs
- backend/tests/TestUtils/TestUtils.fs
This adds DRecords everywhere. By design, it doesn't do anything with them - in the few cases where we tried to enable them we got errors as almost everything (we're talking DBs here) use DDicts. They can be converted later, for now our goal is simply to get DRecords into the codebase so that the later PR will be manageable.
> Add DRecords everywhere

- backend/src/LibService/LaunchDarkly.fs
- backend/src/LibService/LibService.fsproj
- backend/src/LibService/Telemetry.fs
Changelog:
```
Infrastructure
- enable sampling of OpenTelemetry data
```
We are spending too much on opentelemetry, and that is about to double due to our provider increasing costs. This is the start of addressing that, by allowing whole-trace sampling. I'd love to sample only errors, but that doesn't exist in dotnet OpenTelemetry.
The plan is in https://github.com/darklang/classic-dark/issues/16, merging this is step 1.
> OpenTelemetry sampling

- backend/src/LibExecutionStdLib/LibJson.fs
- backend/testfiles/execution/json.tests
```
Language and Standard Library
- Add minimal support for records+dictionaries to Json::parse<'a> and ::serialize<'a>
```
This was blocking Ocean, so we hacked together to get out a working solution. Does this seem reasonable for now, @pbiggar?
My hesitation is that we're returning a DDict in the parser when we want to return a DRecord.
This was done as the Parser currently interprets (afaik) all 'objects' as DDicts - so, returning a DRecord as we'd _like_ to do would result in difficult testing (until we support labeling a record like `Person { Name = ... }`)
> Handle Dicts/Records in JSON stdlib fns

- backend/experiments/cli/LibCli.fs
- backend/experiments/cli/program.dark
- backend/src/LibExecution/ProgramTypes.fs
- backend/src/Parser/CanvasV2.fs
- backend/src/Parser/ProgramTypes.fs
When parsing, we didn't support user functions in some situations. The parser just thinks they're variables. It works fine in some cases like function application as F# put it in a structure where we know they're variables, but that doesn't work in pipes. This does a post-pass that handles it for pipes.
Also renames IO.print to `print` and `IO.readFile` to `File.read`
> Allow parsing user functions in pipes

- backend/src/LibExecutionStdLib/LibList.fs
- backend/testfiles/execution/list.tests
Related issue: https://github.com/darklang/dark/issues/2552
Adds:
* groupAdjacentBy :  List a -> (a -> a -> Bool) -> List (List a))
* groupBy : List a -> (a -> b) -> List (Tuple (b, (List a)))
The definition of `groupBy` with a key function is more straightforward, the only edge-cases were the ordering of tuples inside the list (based on the first appearence of a key), and the ordering of elements in each tuple.
The definition for `groupAdjacentBy` is not as clear. Initially I went with the definition that's used in [Haskell](https://hackage.haskell.org/package/base-4.7.0.1/docs/src/Data-List.html)
```hs
-- | The 'groupBy' function is the non-overloaded version of 'group'.
groupBy                 :: (a -> a -> Bool) -> [a] -> [[a]]
groupBy _  []           =  []
groupBy eq (x:xs)       = …
```
> Add List.groupAdjacentBy_v0 and List.groupBy_v0

- backend/experiments/LibExperimentalStdLib/LibDarkEditor.fs
Changelog:
```
CanvasHack, experiment1
- `add Editor::parseAndSerializeExpr`
```
**Test:**
Result For `DarkEditor.parseAndSerializeExpr "1 + 2"` :
`Ok "["EInfix",701127178,["InfixFnCall",["ArithmeticPlus"]],["EInt",558621043,1],["EInt",148400566,2]]"`
> Add parseAndSerializeExpr fn

- backend/src/LibExecution/ProgramTypes.fs
- backend/src/Wasm/DarkEditor.fs
- backend/src/Wasm/Init.fs
- backend/src/Wasm/Libs/Editor.fs
- backend/src/Wasm/Libs/HttpClient.fs
- backend/src/Wasm/StdLib.fs
- backend/src/Wasm/Wasm.fsproj
Changelog:
```
WebAssembly Runtime
- split stdlib into 2 files and (partially) 'modules'
```
> Split WASM stdlib into HttpClient and Editor

- backend/src/Parser/CanvasV2.fs
- backend/src/Wasm/DarkEditor.fs
- backend/src/Wasm/Libs/HttpClient.fs
- backend/static/editor-bootstrap.js
- canvases/dark-editor-vue/src/components/ResponseChat.vue
- canvases/dark-editor-vue/src/views/MainView.vue
- canvases/dark-editor/main.dark
- canvases/dark-js-wasm-io/main.dark
- canvases/dark-repl/README.md
- canvases/dark-repl/main.dark
Changelog:
```
WASM Runtime
- enable WASM eval of full user program (types, fns, exprs) rather than just expr
canvases/dark-editor
- eval full user program rather than just expr
canvases/dark-repl
- eval full user program rather than just expr
```
> Enable WASM eval of full user program (types, fns, exprs) rather than just expr

- backend/src/LibExecution/RuntimeTypes.fs
- backend/src/StdLibExecution/Libs/DateTime.fs
- backend/testfiles/execution/date.tests
- backend/testfiles/execution/db.tests
- canvases/dark-editor-vue/src/components/Prompt.vue
- canvases/dark-editor-vue/src/components/ResponseChat.vue
Changelog:
```
Language 
-  Rename DateTime.add to DateTime.addSeconds
```
This PR:
- Fixes what broke after Codemirror PR merge
Fix: use the updated textarea value in executeCode function.
- Renames DateTime.add to DateTime.addSeconds
> Rename DateTime.add to DateTime.addSeconds and fix ResponseChat textarea

- backend/experiments/BwdDangerServer/Server.fs
- backend/experiments/StdLibExperimental/Libs/Experiments.fs
- canvases/dark-editor/main.dark
No changelog
- Add `filename` parameter to `parseAndSerializeProgram` to resolve user program parsing issue
> Fix parsing issue

- backend/src/Wasm/Libs/Editor.fs
- backend/src/Wasm/Wasm.fsproj
> Fix access to Wasm.HttpClient functions from dark-editor and dark-repl

- backend/src/LibAnalysis/ClientProgramTypes.fs
- backend/src/LibAnalysis/ClientRuntimeTypes.fs
- backend/src/LibBinarySerialization/ProgramTypesToSerializedTypes.fs
- backend/src/LibBinarySerialization/SerializedTypes.fs
- backend/src/LibExecution/Interpreter.fs
- backend/src/LibExecution/ProgramTypes.fs
- backend/src/LibExecution/ProgramTypesAst.fs
- backend/src/LibExecution/ProgramTypesToRuntimeTypes.fs
- backend/src/LibExecution/RuntimeTypes.fs
- backend/src/Parser/ProgramTypes.fs
- backend/src/StdLibExecution/Libs/NoModule.fs
- backend/testfiles/execution/language.tests
- backend/tests/TestUtils/TestUtils.fs
- backend/tests/Tests/Serialization.TestValues.fs
The list destructuring for `match with` expression. 
Usage cases:  
```fsharp
1. head :: tail 
2. a :: b :: c... :: n :: rest
3. (a::b::ab_rest)::(x::y::xy_rest)::rest 
```
> List destructuring

- backend/src/Wasm/Libs/Editor.fs
- canvases/dark-editor-vue/src/App.vue
- canvases/dark-editor-vue/src/components/CodeSnippet.vue
- canvases/dark-editor-vue/src/components/Conversation.vue
- canvases/dark-editor-vue/src/components/ConversationStep.vue
- canvases/dark-editor-vue/src/components/Prompt.vue
- canvases/dark-editor-vue/src/types.ts
- canvases/dark-editor-vue/src/views/CodeAndContextView.vue
- canvases/dark-editor-vue/src/views/TasksAndActionsView.vue
- canvases/dark-editor/client.dark
- canvases/dark-editor/system-prompt.txt
Changelog:
```
canvases/dark-editor
- Start handling errors.
```
This PR includes:
- Updating the parseAndSerializeProgram fn to use Result type for better error handling.
- Starting to handle errors ( send syntax errors and parsing errors as prompts and get the updated code snippet).
- Minor styling changes.
- Fixing the loading spinner.
- Displaying the user prompt immediately after sending it.
Current state:
https://github.com/darklang/dark/assets/87861924/29fa190f-9657-4df5-aa70-a8e304a0d9fd
> Handling errors 

- backend/experiments/LibExperimentalExecution/LibExperimentalExecution.fsproj
- backend/experiments/LibExperimentalExecution/RealExperimentalExecution.fs
- backend/src/LibExecution/ProgramTypes.fs
- backend/src/LibRealExecution/RealExecution.fs
- backend/src/LocalExec/Libs/Packages.fs
- backend/src/StdLibDarkInternal/Helpers/ProgramTypesToDarkTypes.fs
- backend/src/StdLibDarkInternal/Libs/Canvases.fs
- backend/src/StdLibDarkInternal/StdLibDarkInternal.fsproj
- backend/tests/TestUtils/TestUtils.fs
- canvases/dark-editor-vue/src/App.vue
- canvases/dark-editor-vue/src/components/Conversation.vue
- canvases/dark-editor-vue/src/components/Function.vue
- canvases/dark-editor-vue/src/components/Repl.vue
- canvases/dark-editor-vue/src/types.ts
- canvases/dark-editor-vue/src/views/MainView.vue
- canvases/dark-editor/client.dark
- canvases/dark-editor/main.dark
- packages/darklang/prettyPrinter/packages.dark
- packages/darklang/prettyPrinter/programTypes.dark
- packages/darklang/stdlib/canvas.dark
- packages/darklang/stdlib/programTypes.dark
No changelog
This PR:
- Updates Dark ProgramTypes given internal changes
- Fixes package-loading 
- Adds functions to the model in client.dark
- Starts creating a new view where functions, types, handlers, etc will live
- Starts adding a Repl
Current editor state:
https://github.com/darklang/dark/assets/87861924/de837a38-ae19-4665-b37f-f6bce9da6f1b
Follow-ups:
> Update Dark ProgramTypes given internal changes and misc work on the editor

- backend/experiments/CanvasHack/CanvasHack.fsproj
- backend/experiments/CanvasHack/Main.fs
No changelog
FYI: I got annoyed at having to type the full of `./scripts/run-canvas-hack load-from-disk dark-editor`.
This allows you to just type `./scripts/run-canvas-hack dark-editor`
> Tidy CanvasHack

- backend/src/LocalExec/Libs/CLI.fs
- backend/src/LocalExec/Libs/Packages.fs
- backend/src/LocalExec/LocalExec.fsproj
- backend/src/LocalExec/StdLib.fs
- backend/src/LocalExec/local-exec.dark
- scripts/deployment/sync-packages-and-canvases.dark
Changelog:
```
LocalExec
- enable ability to add another script
Infra
- add incomplete script to sync packages and canvases during deploys
```
This is final useful bit extracted out of #4949.
> Allow LocalExec to run other scripts; add WIP sync-data script

- backend/src/Cli/Cli.fs
- backend/src/Cli/Libs/Cli.fs
- backend/src/LocalExec/Libs/Cli.fs
- backend/src/LocalExec/Libs/Packages.fs
- backend/src/LocalExec/LocalExec.fs
- backend/src/Parser/CanvasV2.fs
- backend/src/Parser/FSharpToWrittenTypes.fs
- backend/src/Parser/NameResolution.fs
- backend/src/Parser/Package.fs
- backend/src/Parser/Parser.fs
- backend/src/Parser/Parser.fsproj
- backend/src/Parser/ProgramTypes.fs
- backend/src/Parser/TestModule.fs
- backend/src/Parser/Utils.fs
- backend/src/Parser/WrittenTypes.fs
- backend/src/Parser/WrittenTypesToProgramTypes.fs
- backend/tests/Tests/BwdServer.Tests.fs
- backend/tests/Tests/Canvas.Tests.fs
- backend/tests/Tests/Cron.Tests.fs
- backend/tests/Tests/HttpClient.Tests.fs
- backend/tests/Tests/LibExecution.Tests.fs
- backend/tests/Tests/Parser.Tests.fs
- backend/tests/Tests/ProgramTypes.Tests.fs
- backend/tests/Tests/Queue.Tests.fs
- backend/tests/Tests/QueueSchedulingRules.Tests.fs
- backend/tests/Tests/SqlCompiler.Tests.fs
This adds WrittenTypes to the parser, using an exact clone of ProgramTypes.
Also renamed "Parser.ProgramTypes", which converted the F# ASTs into LibExecution.ProgramTypes types, to "Parser.FSharpToWrittenTypes".
There's a bit of clunkiness in here, planning to resolve it on future PRs.
> Add WrittenTypes

- backend/experiments/BwdDangerServer/DangerExecution.fs
- backend/src/Cli/Cli.fs
- backend/src/Cli/Libs/Cli.fs
- backend/src/LibBackend/SqlCompiler.fs
- backend/src/LibExecution/Execution.fs
- backend/src/LibExecution/Interpreter.fs
- backend/src/LibExecution/RuntimeTypes.fs
- backend/src/LibRealExecution/RealExecution.fs
- backend/src/LocalExec/Libs/Cli.fs
- backend/src/LocalExec/LocalExec.fs
- backend/src/StdLibDarkInternal/Libs/Documentation.fs
- backend/src/Wasm/EvalHelpers.fs
- backend/tests/TestUtils/TestUtils.fs
- backend/tests/Tests/DvalRepr.Tests.fs
- backend/tests/Tests/StdLib.Tests.fs
Changelog:
```
Interpreter
- split RT.ExecutionState.libraries into .builtIns and .packageManager
```
towards package streaming
> Split ExecutionState.libraries into .builtIns and .packageManager

- backend/src/LocalExec/local-exec.dark
- backend/src/StdLibDarkInternal/Helpers/ProgramTypesToDarkTypes.fs
- canvases/dark-packages/main.dark
- packages/darklang/languageTools/programTypes.dark
- packages/darklang/prettyPrinter/packages.dark
- packages/darklang/prettyPrinter/programTypes.dark
- packages/darklang/stdlib/canvas.dark
- packages/darklang/stdlib/packages.dark
No changelog
This moves ProgramTypes from Darklang.StdLib to Darklang.LanguageTools
> Move ProgramTypes out of Darklang.StdLib

- backend/src/LibBackend/PackageManager.fs
- backend/src/LibCliExecution/PackageManager.fs
- backend/src/StdLibDarkInternal/Libs/Packages.fs
- packages/darklang/stdlib/packages.dark
This adds pretty naive caching for our package managers (both DB-based and the web-based one for CLI that accesses the `dark-packages` canvas). Still fetches in bulk, but caches results for a minute. Reasonable for now? Makes things much faster for me, anyway.
> naive (temp) caching for package managers to hold us over

- backend/src/LibExecution/TypeChecker.fs
- backend/testfiles/execution/stdlib/dict.dark
- backend/testfiles/execution/stdlib/float.dark
- backend/testfiles/execution/stdlib/httpclient.dark
- backend/testfiles/execution/stdlib/int.dark
- backend/testfiles/execution/stdlib/list.dark
- backend/testfiles/execution/stdlib/string.dark
Recursive run-time type-checks are hurting performance badly. That feature was a recent addition, and this PR guts it (for now).
See https://www.notion.so/darklang/Type-checking-notes-490ff2d80ba240eb80cb37ade394f793
> Stop recursive run-time type-checks

- backend/testfiles/execution/language/type-alias.dark
The formatting of type-alias.dark somehow hid all but one test. This reformats it properly and also fixes some error messages from recent typechecker changes.
> Fix bad reformat which made tests disappear

- backend/src/LibCloud/SqlCompiler.fs
- backend/src/Prelude/Prelude.fs
- backend/testfiles/execution/cloud/db.dark
Changelog:
```
Language and Standard Library
- DB.query now supports nested field access of DB data
i.e. `DB.query (\item -> item.details.age > 22)`
```
> Nested field access db query

- canvases/dark-packages/main.dark
No changelog
No need to alias these types
> Reference package types directly in dark-packages canvas

- backend/src/LibCloud/SqlCompiler.fs
- backend/src/LibCloud/UserDB.fs
- backend/src/LibExecution/DvalReprInternalRoundtrippable.fs
- backend/src/LibExecution/Execution.fs
- backend/src/LibExecution/Interpreter.fs
- backend/src/LibExecution/RuntimeTypes.fs
- backend/src/LibExecution/TypeChecker.fs
- backend/src/Prelude/Prelude.fs
- backend/src/Wasm/DarkEditor.fs
- backend/testfiles/execution/cloud/db.dark
- backend/testfiles/execution/language/elambda.dark
- backend/tests/TestUtils/TestUtils.fs
- backend/tests/Tests/Execution.Tests.fs
- backend/tests/Tests/SqlCompiler.Tests.fs
- backend/tests/Tests/StdLib.Tests.fs
Changelog:
```
Interpreter
- start maintaining/using Map<String, TypeReference> of resolved type parameters, similar to symtable
```
> Start maintaining map of resolved type parameters

- backend/src/LibCloud/SqlCompiler.fs
- backend/src/LibExecution/Errors.fs
- backend/src/LibExecution/Interpreter.fs
- backend/src/LibExecution/RuntimeTypes.fs
- backend/src/LibExecution/TypeChecker.fs
- backend/src/LibParser/FSharpToWrittenTypes.fs
- backend/src/LibParser/NameResolver.fs
- backend/src/LibParser/WrittenTypes.fs
- backend/src/LibParser/WrittenTypesToProgramTypes.fs
- backend/src/Prelude/Prelude.fs
- backend/testfiles/execution/language/econstant.dark
- backend/testfiles/execution/language/type-alias.dark
- backend/testfiles/execution/language/type-enum.dark
- Use NELists in more places
- Add a shorttypename for errors
- better errors for invalid types in enums:
```fsharp
Expected: MyEnum.X (String)
Actual: MyEnum.X (Int)
```
> Use NELists more

- backend/src/LibCloud/Cron.fs
- backend/src/LibCloud/Queue.fs
- backend/src/QueueWorker/QueueWorker.fs
- backend/src/StdLibCloudExecution/Libs/Event.fs
- backend/tests/Tests/Queue.Tests.fs
The queue tests were failing because each dequeueAndProcess was global, so as each test dequeued event, it wasn't guaranteed (though it was likely) that what it dequeued was the same thing it just enqueued.
The new logic takes this into account - a background thread just constantly dequeues and the tests can check properties about the queues.
> Fix queue tests

- backend/src/LocalExec/Libs/List.fs
- backend/src/LocalExec/LocalExec.fsproj
- backend/src/LocalExec/StdLib.fs
- backend/src/LocalExec/local-exec.dark
- backend/src/StdLibExecution/Libs/List.fs
- backend/testfiles/execution/stdlib/list.dark
- packages/darklang/stdlib/list.dark
- scripts/deployment/buildcontainers.dark
No changelog
#5020 follow-up
This PR adds a copy of both List.iter and List.flatten to LocalExec. Reason being, we are unable to use PACKAGE functions during the 'load from disk into DB' process.
> Add a copy of List.iter and List.flatten to LocalExec

- backend/src/LibExecution/ProgramTypesToRuntimeTypes.fs
- backend/src/StdLibExecution/Libs/Math.fs
- backend/src/StdLibExecution/Libs/String.fs
- backend/testfiles/execution/stdlib/crypto.dark
- backend/testfiles/execution/stdlib/math.dark
- backend/testfiles/execution/stdlib/string.dark
- packages/darklang/stdlib/list.dark
- packages/darklang/stdlib/math.dark
- packages/darklang/stdlib/string.dark
Changelog:
```
Packages
- Move constants to packages
```
This PR moves constants to packages.
We are unable to move `List.empty`, `Bytes.empty`, and `Dict.empty` since our current support is limited to types with literal representations, excluding List and Dict constants due to their lack of implicit types
> Move several constants from builtins to package space

- backend/src/BuiltinExecution/Libs/String.fs
- backend/src/LocalExec/local-exec.dark
- backend/testfiles/execution/stdlib/string.dark
- canvases/dark-editor/client.dark
- canvases/dark-editor/main.dark
- canvases/dark-packages/main.dark
- canvases/dark-repl/assets/client.dark
- canvases/dark-repl/main.dark
- packages/darklang/cli/cli.dark
- packages/darklang/stdlib/string.dark
- packages/openai.dark
No changelog
This adds a new fromBytes that doesn't ignore errors and uses it in String.base64Decode
> Add a new fromBytes that doesn't ignore errors

- backend/testfiles/execution/stdlib/option.dark
- backend/testfiles/execution/stdlib/result.dark
- packages/darklang/stdlib/fun.dark
- packages/darklang/stdlib/option.dark
- packages/darklang/stdlib/result.dark
Changelog:
```
Standard library
- Add new Option and Result functions to the standard library
```
This PR introduces new Option and Result functions to the standard library, along with some tests.
Result :
Option:
> Expand the Standard Library: Option and Result

- backend/src/BuiltinExecution/Libs/Json.fs
- backend/testfiles/execution/stdlib/json.dark
No changelog
#5037 follow-up
- The float formatting precision was increased from %.12 to %.16 to match other programming languages (F#, python, and Javascript)
- The added tests that use [number]e+[pow] were removed.
> Add some Json tests #5037 -followup

- .circleci/config.yml
- backend/experiments/CanvasHack/Main.fs
- backend/src/LibCliExecution/PackageManager.fs
- backend/src/LibCloud/SqlCompiler.fs
- backend/src/LibExecution/DvalReprInternalQueryable.fs
- backend/src/LibExecution/RuntimeTypes.fs
- backend/testfiles/execution/cloud/db.dark
- canvases/dark-packages/main.dark
- packages/darklang/prettyPrinter/runtimeTypes.dark
- scripts/build/reload-packages
- scripts/run-backend-server
- scripts/run-canvas-hack
- scripts/run-local-exec
I rewrote dark-packages, using more direct calls (`DB.query` vs `DB.getAll`). This led me on a journey:
- add support for querying EEnums in the SqlCompiler
- allow querying DRecords and DEnums in SqlCompiler
- more docs and more specific errors in SqlCompiler
- handle typeArgs in aliases and fields in SqlCompiler
- print errors better in the CLI
- refactor PackageManager fetching in the cli
- add fetching from packages in CI to find errors earlier
I also tried to enable testing the PackageManager in the CLI, but gave up.
> Add support for more type stuff in SQLCompiler / speed up CLI

- backend/src/BuiltinExecution/Builtin.fs
- backend/src/BuiltinExecution/BuiltinExecution.fsproj
- backend/src/BuiltinExecution/Libs/Bool.fs
- backend/src/BuiltinExecution/Libs/List.fs
- backend/src/BuiltinExecution/Libs/String.fs
- backend/src/LibCloud/PackageManager.fs
- backend/src/LibCloud/SqlCompiler.fs
- backend/src/LibExecution/RuntimeTypesAst.fs
- backend/src/Prelude/Ply.fs
- backend/testfiles/execution/cloud/db.dark
- backend/tests/Tests/SqlCompiler.Tests.fs
- packages/darklang/stdlib/bool.dark
- packages/darklang/stdlib/list.dark
- packages/darklang/stdlib/string.dark
Changelog:
```
Area of change
- Inline package functions in the SQLCompiler
```
This PR:
- Inline package functions in the SQLCompiler
- Add an async version of RuntimeTypesAst.postTraversal function
- Temporarily add Builtin.Bool.not back until we expose `ENot`
- add some db tests for package constants and roundtrip tests for tuple, record, and option.
> Inline package functions in the sqlCompiler

- backend/src/BuiltinExecution/Builtin.fs
- backend/src/BuiltinExecution/BuiltinExecution.fsproj
- backend/src/BuiltinExecution/Libs/Base64.fs
- backend/src/BuiltinExecution/Libs/Bytes.fs
- backend/src/LibExecution/RuntimeTypesAst.fs
- backend/testfiles/execution/language/big.dark
- backend/testfiles/execution/stdlib/bytes.dark
- backend/testfiles/execution/stdlib/string.dark
- packages/darklang/prettyPrinter/runtimeTypes.dark
- packages/darklang/stdlib/base64.dark
- packages/darklang/stdlib/bytes.dark
- packages/darklang/stdlib/string.dark
Changelog:
```
Stdlib improvements
- Migrate Bytes.base64encode and Bytes.base64decode to a separate Base64 module
- Add Bytes.append and Bytes.containsSegment
```
> Migrate base64encode and base64decode from Bytes to a Base64 module

- backend/src/BuiltinExecution/Libs/Dict.fs
- backend/src/BuiltinExecution/Libs/List.fs
- backend/src/BuiltinExecution/Libs/NoModule.fs
- backend/src/LibCloud/Canvas.fs
- backend/src/LibCloud/SqlCompiler.fs
- backend/src/LibCloudExecution/HttpClient.fs
- backend/src/LibExecution/Builtin.fs
- backend/src/LibExecution/DvalReprInternalQueryable.fs
- backend/src/LibExecution/Errors.fs
- backend/src/LibExecution/Interpreter.fs
- backend/src/LibExecution/RuntimeTypes.fs
- backend/src/LibParser/FSharpToWrittenTypes.fs
- backend/src/LibService/ConfigDsl.fs
- backend/src/Prelude/Map.fs
- backend/tests/TestUtils/TestUtils.fs
- backend/tests/Tests/Builtin.Tests.fs
- backend/tests/Tests/Canvas.Tests.fs
- backend/tests/Tests/Prelude.Tests.fs
- backend/tests/Tests/SqlCompiler.Tests.fs
- canvases/builtin/prompt.txt
- packages/darklang/languageTools/runtimeErrors/execution.dark
- packages/darklang/languageTools/runtimeErrors/runtimeErrors.dark
A series of small cleanups mostly enabled by removing DError, with some drive-bys.
- Remove refs from our codebase (in favor of mutable variables, or removing where unused, eg in List.fs)
- `IncorrectArgs` replaced with `Exception.raiseInternal`
- remove remnants of `DIncomplete`
- make interpreter error handling a little more structured/typed
- In cases where we use Errors only to push around a RuntimeError which then gets raised, just raise immediately and simplify the code
- Refactor `EDict` handling
- Remove `eval'`
- Simplify (and optimize) `EString` handling
- Normalize strings during parsing
- Rename name/uses of `Map.find` with `Map.findUnsafe`
- Rename uses of `Map.tryFind` to `Map.find` (which now returns on option)
> Cleanups after DError change

- backend/src/BuiltinExecution/Libs/Json.fs
- backend/src/LibParser/FSharpToWrittenTypes.fs
- backend/src/Prelude/String.fs
- backend/testfiles/execution/stdlib/json.dark
- packages/darklang/stdlib/httpclient.dark
- packages/darklang/stdlib/tuple2.dark
- packages/darklang/stdlib/tuple3.dark
Fix some problems with JSON parsing:
- use Json errors (usually can't match with type) when user input doesn't match the stated type (we often used Exception.raiseInternal, but this is triggered by user code so that's not right)
- remove `Tuple<Int,String>` syntax in favor of `Int * String` (from everywhere, not just Json)
- add modules to json.dark
- add Option and Result alias to json.dark (removes a lot of boilerplate) 
- ensure (and test) that only valid characters are parsed
> Improve JSON functionality part 1

- backend/testfiles/execution/stdlib/httpclient.dark
- backend/testfiles/httpclient/v0/todo/request-query-param-list.test
- backend/testfiles/httpclient/v0/todo/request-query-param-null.test
- backend/testfiles/httpclient/v0/todo/request-query-param-string-basic.test
- backend/testfiles/httpclient/v0/todo/request-query-param-string-emoji-key.test
- backend/testfiles/httpclient/v0/todo/request-query-param-string-empty-key.test
- backend/testfiles/httpclient/v0/todo/request-query-param-string-empty-value.test
- backend/testfiles/httpclient/v0/todo/request-query-param-string-empty-values.test
- backend/testfiles/httpclient/v0/todo/request-query-param-string-punctuation-key.test
- backend/testfiles/httpclient/v0/todo/request-query-param-string-punctuation-value.test
- backend/testfiles/httpclient/v0/todo/request-query-param-string-spaces-key.test
- backend/testfiles/httpclient/v0/todo/request-query-param-string-spaces-value.test
- packages/darklang/stdlib/httpclient.dark
Following up on [this](https://github.com/darklang/dark/pull/4968#discussion_r1259065997).
We had some package functions in `HttpClient` like:
```fsharp
/// Returns a header <type (String*String))> with {{content-type}} set for HTML form requests or responses
let formContentType () : (String * String) =
("content-type", "application/x-www-form-urlencoded")
```
This PR updates them all to be Consts, in a new `ContentType` sub-module of `HttpClient`:
```fsharp
module ContentType =
/// A header <type (String*String))> with {{content-type}} set for HTML form requests or responses
let form = ("content-type", "application/x-www-form-urlencoded")
/// A header <type (String*String))> with {{content-type}} set for JSON requests or responses
let json = ("content-type", "application/json; …
```
> Move content type HttpClient helpers to consts in module

- backend/src/BuiltinCli/Libs/File.fs
- backend/src/BuiltinCli/Libs/Process.fs
- backend/src/LocalExec/local-exec.dark
- packages/darklang/cli/cli.dark
- packages/darklang/languageTools/programTypes.dark
- packages/darklang/prettyPrinter/programTypes.dark
- packages/darklang/stdlib/process.dark
- scripts/hello-world
- scripts/hello-world.dark
- fix some regressions preventing packages getting to the dark-packages canvas locally
- fix `Process.run` function -- I was unable to use the Process.run as-is
- adds a `File.delete` in StdLibCli, as I reached for it when writing a personal script
> Fix Process.run builtin and package fn; add File.delete builtin; fix dark-packages ingest

- backend/src/BuiltinExecution/Libs/Float.fs
- backend/src/BuiltinExecution/Libs/Int.fs
- backend/src/BuiltinExecution/Libs/Uuid.fs
- backend/src/LibExecution/RuntimeTypes.fs
- backend/testfiles/execution/stdlib/float.dark
- backend/testfiles/execution/stdlib/int.dark
- backend/testfiles/execution/stdlib/uuid.dark
- backend/tests/TestUtils/TestUtils.fs
- packages/darklang/languageTools/runtimeErrors/int.dark
- packages/darklang/languageTools/runtimeErrors/runtimeErrors.dark
- packages/darklang/stdlib/float.dark
- packages/darklang/stdlib/int.dark
- packages/darklang/stdlib/uuid.dark
No changelog
This PR:
- Introduces a new IntRuntimeError and uses it for Int.mod, Int.power, and Int.divide
```
type Error =
| DivideByZeroError
| OutOfRange
| NegativeExponent
| NegativeModulus
| ZeroModulus
```
- Replaces Float.parse string error with a custom IntParseError
- Replaces Int.parse string error with a custom IntParseError
- Updates Int.power to return an `Int` instead of `Result`
- Replaces Uuid.parse string error with a custom UuidParseError
> Add a new IntRuntimeError and replace some string errors

- backend/src/BuiltinCli/Builtin.fs
- backend/src/BuiltinCli/BuiltinCli.fsproj
- backend/src/BuiltinCli/Libs/File.fs
- backend/src/BuiltinCli/Libs/LanguageServerProtocol.fs
- backend/src/BuiltinExecution/Libs/AltJson.fs
- backend/testfiles/execution/stdlib/alt-json.dark
- packages/darklang/json-rpc.dark
- packages/darklang/languageTools/lsp-server.dark
- packages/darklang/languageTools/lsp.dark
- packages/darklang/stdlib/alt-json.dark
- scripts/run-cli
- user-code/darklang/scripts/language-server.dark
- vscode-extension/client/src/extension.ts
- vscode-extension/package-lock.json
- vscode-extension/server/src/server.ts
supporting work:
- remove `Builtin.File.append` (broken, ambiguous) with `Builtin.File.appendText` (working, clear)
- update `AltJson` module a bit, mostly removing "token" wording
- rename `type JsonToken` to just `type Json`
- rename fn `parseToken` to just `parse`
- rename fn `serialize` to `format`
- `run-cli` now logs stdout+stderr to `rundir/logs/cli.log` (_so_ helpful)
actual improvements:
- added `Builtin.Danger.LanguageServerProtocol.readNextMessage` to read incoming messages
- because... I'm not sure why - I had issues trying to replicate this with `Builtin.Stdin.readLine` but I'm sure it's solveable :arrow_down: 
- TODO added to remove this in favor of a new Builtin fn or two
- add `@Darklang.JsonRPC` module corresponding to the json-rpc 2.0 spec. I really like how this turned …
> Replace our LSP server, written in Node, with one written in Darklang

- scripts/devcontainer/_vscode-post-start-command
I noticed that devcontainer start-up was failing after the first build, since the `mv`'s _source_ doesn't exist unless the container was _just_ built
> Update copy of built tree-sitter.so in devcontainer start-up

- scripts/build/compile
- scripts/devcontainer/_vscode-post-start-command
If we don't do this, the backend build will fail when trying to build the LibTreeSitter.Darklang project, as-is, (only) on the first build after a container rebuild.
> Build parser before backend

- Dockerfile
Changelog:
```
Area of change
- dockerfile
alternatively:
No changelog
Docker could not build the development contain in a Windows environment
Run dos2unix on installer scripts that are written to the container filesystem during the contain build to eliminate any DOS line endings.
- add dos2unix to apt install list
- run dos2unix on install-targz-file and install-exe-file
- save yugabyte install script as install-yugabyte and run dos2unix on it before running
- save dotnet8 install script as install-dotnet8 and run dos2unix on it before running`
tested only locally on one machine.
back out the commit
> fix: make docker build work on Windows

- packages/darklang/json-rpc.dark
- packages/darklang/languageServerProtocol/README.md
- packages/darklang/languageServerProtocol/common.dark
- packages/darklang/languageServerProtocol/language/completion.dark
- packages/darklang/languageServerProtocol/lifecycle/initialize.dark
- packages/darklang/languageTools/lsp-server.dark
- packages/darklang/stdlib/uint64.dark
- user-code/darklang/scripts/sample-for-testing-extension.dark
- in `initialize` handshake, announce that we support 'completions'
`"completionProvider":{"resolveProvider":false}`
- handle `textDocument/completion` requests, and respond to them with a single fake autocomplete
https://github.com/darklang/dark/assets/906686/20261594-8371-410b-a5ab-794ad5c895f0
> Provide fake autocomplete ("completions") in our Language Server

- packages/darklang/json-rpc.dark
- packages/darklang/languageServerProtocol/README.md
- packages/darklang/languageServerProtocol/common.dark
- packages/darklang/languageServerProtocol/documentSync/textDocument.dark
- packages/darklang/languageServerProtocol/language/completion.dark
- packages/darklang/languageServerProtocol/language/diagnostics.dark
- packages/darklang/languageServerProtocol/language/semanticToken.dark
- packages/darklang/languageServerProtocol/lifecycle/initialize.dark
- packages/darklang/languageTools/lsp-server.dark
- vscode-extension/package.json
behold, the `let` of color.
---
This:
- updates the server's response in the `initialize` handshake to advertise that we support semantic tokens
```fsharp
let initializeResult =
LanguageServerProtocol.Lifecycle.InitializeRequest.InitializeResult.InitializeResult
{ capabilities =
LanguageServerProtocol.Lifecycle.InitializeRequest.ServerCapabilities.ServerCapabilities
{ textDocumentSync = ...
completionProvider = ...
semanticTokensProvider =
Stdlib.Option.Option.Some(
LanguageServerProtocol.SemanticTokens.SemanticTokenProviderOptions.SemanticTokenProviderOptions.SemanticTokensOptions(
LanguageServerProtocol.SemanticTokens.SemanticTokensOptions.SemanticTokensOptions
{ legend =
LanguageServerProtocol.SemanticTokens.SemanticTokensLegend.SemanticTokensLegend
{ tokenTypes = [ "keyword"; …
```
> Language Server 'glue code' for semantic tokens (for syntax highlighting)

- backend/testfiles/execution/language/elet.dark
- backend/testfiles/execution/stdlib/parser.dark
- packages/darklang/languageTools/parser.dark
- packages/darklang/languageTools/programTypes.dark
- packages/darklang/languageTools/writtenTypes.dark
- tree-sitter-darklang/grammar.js
- tree-sitter-darklang/src/grammar.json
- tree-sitter-darklang/src/parser.c
I accidentally did a few things at once:
- removed IDs from `writtenTypes.dark` (I don't think we need them)
- removed PT.FnName.Package reference from writtenTypes.dark
- commented out parts of `writtenTypes` that `grammar.js` doesn't yet support (I think it makes sense to keep these roughly matching)
- add source text `Range`s to various nodes in WrittenTypes, to help with Syntax Highlighting, Completions, etc.
We'll probably have to add `Range`s in a few more places shortly to get complete syntax highlighting, but what's here should be enough to get both syntax highlighting and completions working at least _a bit_.
> Add source ranges to dark writtentypes

- packages/darklang/json-rpc.dark
- packages/darklang/languageServerProtocol/language/semanticToken.dark
- packages/darklang/languageTools/lsp-server/docSync.dark
- packages/darklang/languageTools/lsp-server/semanticTokens.dark
- packages/darklang/languageTools/parser.dark
- packages/darklang/languageTools/semanticTokens.dark
- packages/darklang/stdlib/string.dark
- vscode-extension/client/src/extension.ts
This implements syntax highlighting by way of LSP-powered semantic tokenization.
It's incomplete and doesn't handle errors, but real, written all in Darklang, and we can iterate well from here.
From this point, all frameworky stuff is complete, and relevant changes to semantic tokenization should be limited to only the types and fns in `Darklang.LanguageTools.SemanticTokens` (which is wholly ignorant of LSP and VS Code, and currently sits at < 200LOC)
---
Specifically, the language server:
- receives a request (`textDocument/semanticTokens/full`) for semantic tokenization, and extracts `requestParams.textDocument.uri` from the params
- from our language server's local store of text documents cached, fetches the text of the relevant one
```fsharp
let relevantDoc =
Stdlib.Dict.get …
```
> Real semantic tokenization (syntax highlighting) in lang. server

- backend/src/BuiltinCliHost/Libs/Cli.fs
- packages/darklang/cli/cli.dark
- scripts/run-cli
This PR updates the `Cli.runFunction` function to parse the args as Exprs using the new parser
Example of parsing the function args using the new WIP parser:
`./scripts/run-cli @PACKAGE.Darklang.Stdlib.Bool.or true false --flag=wip-parser` 
Example of parsing the function args using the old parser:
`./scripts/run-cli @PACKAGE.Darklang.Stdlib.Bool.or true false`
> Cli.runFunction : parse function args using the new parser

- backend/testfiles/execution/cloud/internal.dark
Fix internal tests :
We encountered a Stack Overflow error while using `List.map` on a long list. As a temporary solution, we have switched to using `List.findFirst` to address the issue.
Note : the tests were passing in CI but not locally (Release mode vs Debug mode)
> Fix running internal tests locally

- .circleci/config.yml
- scripts/build/dotnet-publish-all-clis.sh
I noticed that the CI artifacts of the `build-cli` step were empty - this fixes that.
edit: Ah, maybe this was intentional? Since each executable is ~12MB, I guess these could add up.
@pbiggar what do you think?
> Preserve CLI build artifacts in CI

- backend/src/BuiltinExecution/Libs/NoModule.fs
- backend/src/Cli/Cli.fs
- packages/darklang/cli/cli.dark
- packages/darklang/languageTools/lsp-server/semanticTokens.dark
- packages/darklang/languageTools/parser.dark
- packages/darklang/languageTools/semanticTokens.dark
- packages/darklang/languageTools/writtenTypes.dark
- packages/darklang/languageTools/writtenTypesToProgramTypes.dark
- user-code/darklang/scripts/sample-for-testing-extension.dark
I [recently gutted](#5215) our semantic tokenization (used by our LSP server for the VS Code extension) in order to get some WrittenTypes changes mergeable.
This PR
- brings it back, with more complete tokenization
- improves error reporting in CLI (if something fails and we have a source, we now print the TLID of failure)
- fixes CLI executions when `--flag` isn't included
https://github.com/darklang/dark/assets/906686/c8d1dcf4-fda1-484c-a8ba-5ccb9b140099
> Fix semantic tokenization

- packages/stachu/json.dark
- packages/stachu/timespan.dark
The PRs #5069 and #5145 have been sitting around stagnant for a while, bugging me.
Because the work is hidden away in a branch, there hasn't been an ergonomic means of quickly playing with these tasks - merging these in, under `packages/stachu` will allow me to get the work out of my head but accessible if I suddenly reach for timespans or want to pursue this json thinking.
I think it'd be OK for a few folks to have their own personal `packages` subdirs like this to play around, though hopefully all is hosted in the cloud pretty soon
> Add temporarily-abandoned WIP around Json and TimeSpans

- .circleci/config.yml
No changelog
This PR addresses the bullet point "CI: build-backend and build-cli are both calling the build-parser script" in the issues mentioned in  https://github.com/darklang/dark/issues/5246 
Pulling the build-parser script into its own CI job and call upon it in the appropriate workflows
> Pull the build-parser script into its own CI job

- scripts/build/dotnet-publish-all-clis.sh
Changelog:
```
Area of change
- Build binaries for remaining runtimes 
```
This PR enables building the binaries for windows and macOS, and fixes the windows binary build by adding the .exe extension
> Build binaries for remaining runtimes (windows and mac)

- backend/src/BuiltinCliHost/BuiltinCliHost.fsproj
- backend/src/BuiltinCliHost/Libs/Cli.fs
- backend/src/Cli/Cli.fs
- backend/src/LibCliExecution/PackageManager.fs
Referencing LibService (indirectly) causes errors on start of the CLI executable, since LibService/Config.fs demands a bunch of environment variables to be set.
> Stop referencing LibCloud (and LibService indirectly) in CLI projects

- backend/src/BuiltinCliHost/Libs/Cli.fs
- backend/src/Cli/Cli.fs
- backend/src/LibPackageManager/ExternalTypesToProgramTypes.fs
- backend/src/LibPackageManager/JsonDeserialization.fs
- backend/src/LibPackageManager/LibPackageManager.fsproj
- backend/src/LibPackageManager/PackageManager.fs
- backend/src/LibPackageManager/README.md
- backend/src/LibPackageManager/SimpleJson.fs
- backend/src/LibPackageManager/Types.fs
- backend/src/Prelude/Json.fs
- backend/tests/Tests/PackageManager.Tests.fs
- backend/tests/Tests/Tests.fs
- backend/tests/Tests/Tests.fsproj
- packages/darklang/languageTools/programTypes.dark
Our F# package manager fetches package items (types, consts, fns) from our dark-packages canvas, over HTTP. Those payloads are in JSON.
Our Json.Vanilla uses System.Text.Json under the hood, which is a reflection-based JSON deserializer.
Our CLI application is AOT-compiled, which puts us in a situation where we can't use run-time reflection.
So, we needed some way to safely deserialize JSON in without using reflection, or by using C# Source Generators (not yet available in F#).
I tried using C# source generators at first, but it broke, and it was broken magic, which is double bad, so abandoned that path.
Then I tried using an F# library Thoth.Json. I didn't quite understand or agree with its types/API, so accidentally started writing an equivalent module, included here as 'SimpleJson'. I …
> Package manager: parse+decode fetched JSON without any reflection

- scripts/publish-vs-code-extension
CI spun for 10mins without this: https://app.circleci.com/pipelines/github/darklang/dark/6996/workflows/e4f4c199-c147-41b7-945d-3e7d51fa31b0/jobs/57826
> try to skip license req when building vscode ext

- backend/testfiles/execution/stdlib/parser.dark
- packages/darklang/cli/cli.dark
- packages/darklang/languageTools/parser.dark
- packages/darklang/languageTools/semanticTokens.dark
- packages/darklang/languageTools/writtenTypes.dark
- tree-sitter-darklang/package.json
- vscode-extension/client/src/extension.ts
Changelog:
```
Parser
- Update the parser to handle unparseable code 
```
This PR adds :
- a new `Unparseable` type to the `CliScript`  type to handle unparseable code and prevent the extension from crashing.
- a `--skip-self-update` flag for the LSP to prevent running the self-update while using the extension
- a `"parse": "tree-sitter parse"` command to tree-sitter-darklang 
A stack overflow occurs when the number of tokens exceeds ~340, which is consistent with the List.map issue #5222
The issue lies in the `SemanticTokens.toJson` function, specifically in:
```
t.data
|> Stdlib.List.map (fun d -> Json.Number(Stdlib.UInt64.toFloat d))
|> Json.Array)
```
> Prevent the extension from crashing due to unparseable Dark code

- backend/src/BuiltinExecution/Libs/Parser.fs
- backend/testfiles/execution/stdlib/parser.dark
- packages/darklang/languageServerProtocol/common.dark
- packages/darklang/languageTools/lsp-server/aaaa_state.dark
- packages/darklang/languageTools/lsp-server/docSync.dark
- packages/darklang/languageTools/lsp-server/semanticTokens.dark
No changelog
This PR :
- moves the parsing from semantic tokens to docSync
- prevents the extension from crashing with empty files
> Move parsing from semantic tokens to docSync

- backend/testfiles/execution/stdlib/list.dark
- packages/darklang/stdlib/list.dark
Changelog:
```
Stdlib 
- Add a `chunkBySize` function to List module
```
> Add a List.chunkBySize function

- backend/tests/Tests/Tests.fs
When we get back to queues, we can get back to handling the flakiness of these tests.
> disable flaky queue tests (for now)

- backend/testfiles/execution/stdlib/parser.dark
- packages/darklang/languageTools/lsp-server/semanticTokens.dark
- packages/darklang/languageTools/parser.dark
- packages/darklang/languageTools/semanticTokens.dark
- packages/darklang/languageTools/writtenTypes.dark
- packages/darklang/languageTools/writtenTypesToProgramTypes.dark
- tree-sitter-darklang/grammar.js
- tree-sitter-darklang/src/grammar.json
- tree-sitter-darklang/src/node-types.json
- tree-sitter-darklang/test/corpus/exhaustive/exprs/Enum.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/bools.txt
- tree-sitter-darklang/test/corpus/exhaustive/type_decls.txt
Changelog:
```
- Update the grammar to support Enums
```
#5321
> Tree-sitter grammar: support Enums

- backend/testfiles/execution/stdlib/parser.dark
- packages/darklang/languageTools/parser/expr.dark
- packages/darklang/languageTools/semanticTokens.dark
- packages/darklang/languageTools/writtenTypes.dark
- packages/darklang/languageTools/writtenTypesToProgramTypes.dark
- packages/darklang/prettyPrinter/programTypes.dark
- tree-sitter-darklang/grammar.js
- tree-sitter-darklang/src/grammar.json
- tree-sitter-darklang/src/node-types.json
- tree-sitter-darklang/test/corpus/exhaustive/exprs/field_access.txt
Changelog:
```
- Update the grammar to support field access
```
#5321
> Tree-sitter grammar: support field access

- backend/src/LibParser/WrittenTypes.fs
- backend/testfiles/execution/stdlib/parser.dark
- packages/darklang/languageTools/parser/expr.dark
- packages/darklang/languageTools/programTypes.dark
- packages/darklang/languageTools/semanticTokens.dark
- packages/darklang/languageTools/writtenTypes.dark
- packages/darklang/languageTools/writtenTypesToProgramTypes.dark
- packages/darklang/prettyPrinter/programTypes.dark
- tree-sitter-darklang/grammar.js
- tree-sitter-darklang/src/grammar.json
- tree-sitter-darklang/src/node-types.json
- tree-sitter-darklang/test/corpus/exhaustive/exprs/fn_calls.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/lambda.txt
Changelog:
```
- Update the grammar to support lambda expressions
```
#5321
> Tree-sitter grammar: support lambda expressions 

- backend/testfiles/execution/stdlib/parser.dark
- packages/darklang/languageTools/parser/expr.dark
- packages/darklang/languageTools/parser/matchPattern.dark
- packages/darklang/languageTools/semanticTokens.dark
- packages/darklang/languageTools/writtenTypes.dark
- packages/darklang/languageTools/writtenTypesToProgramTypes.dark
- packages/darklang/prettyPrinter/programTypes.dark
- tree-sitter-darklang/grammar.js
- tree-sitter-darklang/src/grammar.json
- tree-sitter-darklang/src/node-types.json
- tree-sitter-darklang/test/corpus/exhaustive/exprs/Enum.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/match.txt
- tree-sitter-darklang/test/corpus/exhaustive/type_decls.txt
Changelog:
```
- Update the grammar to support match expressions
```
#5321
> Tree-sitter grammar: support match expressions

- backend/testfiles/execution/stdlib/parser.dark
- packages/darklang/languageTools/parser/expr.dark
- packages/darklang/languageTools/semanticTokens.dark
- packages/darklang/languageTools/writtenTypes.dark
- packages/darklang/languageTools/writtenTypesToProgramTypes.dark
- packages/darklang/prettyPrinter/programTypes.dark
- tree-sitter-darklang/grammar.js
- tree-sitter-darklang/src/grammar.json
- tree-sitter-darklang/src/node-types.json
- tree-sitter-darklang/test/corpus/exhaustive/exprs/record_update.txt
Changelog:
```
- Update the grammar to support Record update
```
#5321
> Tree-sitter grammar: support Record update

- backend/testfiles/execution/stdlib/parser.dark
- packages/darklang/languageTools/parser/typeReference.dark
- packages/darklang/languageTools/semanticTokens.dark
- packages/darklang/languageTools/writtenTypes.dark
- packages/darklang/languageTools/writtenTypesToProgramTypes.dark
- tree-sitter-darklang/grammar.js
- tree-sitter-darklang/src/grammar.json
- tree-sitter-darklang/src/node-types.json
- tree-sitter-darklang/test/corpus/exhaustive/type_refs.txt
Changelog:
```
- Update the grammar to support variable type reference
```
This also updates the parser to handle TUuid and TDateTime
> Tree-sitter grammar: support variable type reference

- backend/src/LibExecution/ProgramTypes.fs
- backend/testfiles/execution/stdlib/parser.dark
- packages/darklang/languageTools/parser/typeReference.dark
- packages/darklang/languageTools/semanticTokens.dark
- packages/darklang/languageTools/writtenTypes.dark
- packages/darklang/languageTools/writtenTypesToProgramTypes.dark
- packages/darklang/prettyPrinter/programTypes.dark
- tree-sitter-darklang/grammar.js
- tree-sitter-darklang/src/grammar.json
- tree-sitter-darklang/src/node-types.json
- tree-sitter-darklang/test/corpus/exhaustive/type_refs.txt
Changelog:
```
- Update the grammar to support function type reference
```
#5321
> Tree-sitter grammar: support Function Type Reference

- backend/testfiles/execution/stdlib/parser.dark
- packages/darklang/languageTools/lsp-server/semanticTokens.dark
- packages/darklang/languageTools/parser/expr.dark
- packages/darklang/languageTools/parser/functionDeclaration.dark
- packages/darklang/languageTools/parser/identifiers.dark
- packages/darklang/languageTools/parser/typeDeclaration.dark
- packages/darklang/languageTools/parser/typeReference.dark
- packages/darklang/languageTools/semanticTokens.dark
- packages/darklang/languageTools/writtenTypes.dark
- packages/darklang/languageTools/writtenTypesToProgramTypes.dark
- packages/darklang/prettyPrinter/programTypes.dark
- tree-sitter-darklang/grammar.js
- tree-sitter-darklang/src/grammar.json
- tree-sitter-darklang/src/node-types.json
- tree-sitter-darklang/test/corpus/exhaustive/exprs/fn_calls.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/if_else.txt
- tree-sitter-darklang/test/corpus/exhaustive/fn_decls.txt
- tree-sitter-darklang/test/corpus/exhaustive/type_decls.txt
- tree-sitter-darklang/test/corpus/exhaustive/type_refs.txt
Changelog:
```
- Update the grammar to support DB type reference
```
#5321
> Tree-sitter grammar: support DB type reference

- backend/src/LibParser/FSharpToWrittenTypes.fs
- backend/src/LibParser/WrittenTypes.fs
- backend/src/LibParser/WrittenTypesToProgramTypes.fs
- backend/testfiles/execution/language/epipe.dark
- backend/testfiles/execution/stdlib/parser.dark
- packages/darklang/languageTools/parser/expr.dark
- packages/darklang/languageTools/parser/identifiers.dark
- packages/darklang/languageTools/parser/matchPattern.dark
- packages/darklang/languageTools/parser/pipeExpr.dark
- packages/darklang/languageTools/semanticTokens.dark
- packages/darklang/languageTools/writtenTypes.dark
- packages/darklang/languageTools/writtenTypesToProgramTypes.dark
- packages/darklang/prettyPrinter/programTypes.dark
- tree-sitter-darklang/grammar.js
- tree-sitter-darklang/src/grammar.json
- tree-sitter-darklang/src/node-types.json
- tree-sitter-darklang/test/corpus/exhaustive/cli_scripts.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/Enum.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/field_access.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/fn_calls.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/if_else.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/match.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/pipe.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/tuple.txt
- tree-sitter-darklang/test/corpus/exhaustive/type_refs.txt
Changelog:
```
- Update the grammar to support pipe expression
```
#5321
> Tree-sitter grammar: support pipe expression

- backend/testfiles/execution/stdlib/parser.dark
- packages/darklang/languageTools/parser/expr.dark
- packages/darklang/languageTools/parser/identifiers.dark
- packages/darklang/languageTools/parser/pipeExpr.dark
- packages/darklang/languageTools/semanticTokens.dark
- packages/darklang/languageTools/writtenTypes.dark
- packages/darklang/languageTools/writtenTypesToProgramTypes.dark
- tree-sitter-darklang/grammar.js
- tree-sitter-darklang/src/grammar.json
- tree-sitter-darklang/src/node-types.json
- tree-sitter-darklang/test/corpus/exhaustive/exprs/constant.txt
Changelog:
```
Tree-sitter grammar
- add support for constant expression
```
#5321
> Tree-sitter grammar: handle constant expression

- backend/testfiles/execution/stdlib/parser.dark
- packages/darklang/languageTools/parser/cliScript.dark
- packages/darklang/languageTools/parser/constantDeclaration.dark
- packages/darklang/languageTools/parser/core.dark
- packages/darklang/languageTools/parser/expr.dark
- packages/darklang/languageTools/parser/matchPattern.dark
- packages/darklang/languageTools/programTypes.dark
- packages/darklang/languageTools/semanticTokens.dark
- packages/darklang/languageTools/writtenTypes.dark
- packages/darklang/languageTools/writtenTypesToProgramTypes.dark
- packages/darklang/prettyPrinter/programTypes.dark
- tree-sitter-darklang/grammar.js
- tree-sitter-darklang/src/grammar.json
- tree-sitter-darklang/src/node-types.json
- tree-sitter-darklang/test/corpus/exhaustive/constant_decls.txt
Changelog:
```
- Update the grammar to support Constant Declaration
```
#5321
> Tree-sitter grammar: support Constant Declaration

- backend/testfiles/execution/stdlib/parser.dark
- backend/testfiles/execution/stdlib/semanticTokenization.dark
- packages/darklang/languageTools/parser/core.dark
- packages/darklang/languageTools/parser/typeDeclaration.dark
- packages/darklang/languageTools/semanticTokens.dark
- packages/darklang/languageTools/writtenTypes.dark
- packages/darklang/languageTools/writtenTypesToProgramTypes.dark
- tree-sitter-darklang/package.json
This PR fixes semantic tokenization, and adds tests for it
> Add semantic tokenization tests

- backend/testfiles/execution/stdlib/semanticTokenization.dark
- backend/tests/Tests/NewParser.Tests.fs
- packages/darklang/languageTools/parser/cliScript.dark
- packages/darklang/languageTools/parser/moduleDeclaration.dark
- packages/darklang/languageTools/programTypes.dark
- packages/darklang/languageTools/semanticTokens.dark
- packages/darklang/languageTools/writtenTypes.dark
- packages/darklang/languageTools/writtenTypesToProgramTypes.dark
- packages/darklang/prettyPrinter/cliScript.dark
- packages/darklang/prettyPrinter/moduleDeclaration.dark
- tree-sitter-darklang/grammar.js
- tree-sitter-darklang/src/grammar.json
- tree-sitter-darklang/src/node-types.json
- tree-sitter-darklang/src/scanner.c
- tree-sitter-darklang/test/corpus/exhaustive/module_decls.txt
Changelog:
```
Tree-sitter grammar
- add support for module declaration
```
> Tree-sitter grammar: add support for module declaration 

- backend/src/LibExecution/CommonToDarkTypes.fs
- backend/src/LibExecution/LibExecution.fsproj
- backend/src/LibExecution/PackageIDs.fs
- backend/src/LibExecution/ProgramTypesToDarkTypes.fs
- backend/src/LibExecution/RuntimeTypesToDarkTypes.fs
- backend/testfiles/execution/stdlib/parser.dark
- backend/testfiles/execution/stdlib/semanticTokenization.dark
- backend/tests/TestUtils/TestUtils.fs
- backend/tests/Tests/Cron.Tests.fs
- backend/tests/Tests/NewParser.Tests.fs
- packages/darklang/cli/cli.dark
- packages/darklang/languageTools/lsp-server/docSync.dark
- packages/darklang/languageTools/lsp-server/handleIncomingMessage.dark
- packages/darklang/languageTools/lsp.dark
- packages/darklang/languageTools/parser/cliScript.dark
- packages/darklang/languageTools/parser/parserTest.dark
- packages/darklang/languageTools/programTypes.dark
- packages/darklang/languageTools/semanticTokens.dark
- packages/darklang/languageTools/writtenTypes.dark
- packages/darklang/languageTools/writtenTypesToProgramTypes.dark
- packages/darklang/prettyPrinter/cliScript.dark
- packages/darklang/prettyPrinter/programTypes.dark
This PR marks the beginning of our transition from LibParser to the darklang-tree-sitter parser.
> Remove LibParser usage from Cron.Tests and NewParser

- backend/testfiles/httphandler/_simple-request-headers.test
- backend/tests/Tests/NewParser.Tests.fs
- tree-sitter-darklang/grammar.js
- tree-sitter-darklang/src/grammar.json
- tree-sitter-darklang/src/node-types.json
- tree-sitter-darklang/test/corpus/exhaustive/exprs/Enum.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/let_expr.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/list.txt
No changelog
This PR adds some tree-sitter-darklang grammar tests, and fixes the following issues: 
Issue 1: 
```
[ ErrorSegment.ErrorSegment.String
"RTETODO typeChecker.toSegments" ] 
```
This was parsed as a list of two elements (an enum and a string literal), rather than a list of one element (an enum with one field)
Issue 2:
```
let x =
1L
|> Stdlib.Option.Option.Some
x
```
The body (`x`) of the let_expression was parsed as part of the pipe, as if it was a field of the enum.
> Tree-sitter-darklang grammar fixes

- backend/testfiles/execution/stdlib/semanticTokenization.dark
- backend/tests/Tests/NewParser.Tests.fs
- backend/tests/Tests/TreeSitter.Tests.fs
- tree-sitter-darklang/grammar.js
- tree-sitter-darklang/src/grammar.json
- tree-sitter-darklang/src/node-types.json
- tree-sitter-darklang/test/corpus/exhaustive/cli_scripts.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/match.txt
- tree-sitter-darklang/test/corpus/exhaustive/fn_decls.txt
- tree-sitter-darklang/test/corpus/exhaustive/module_decls.txt
No changelog
This PR fixes `fn_decl` parsing 
There was a parsing error when I tried to parse the following code: 
```
module Darklang =
let returnsOptionNone () : Stdlib.Option.Option<'a> = Stdlib.Option.Option.None
let returnsResultOk () : Stdlib.Result.Result<Int64, String> =
Stdlib.Result.Result.Ok 5L
```
It was parsed as one function declaration instead of two because there wasn’t a clear delimiter; enums can have fields, so it tried to treat that second `fn_decl` as a field, and errored
This PR handles this issue by:
- forcing the body to be written on a new line and indented for complex expressions
- allowing inline expressions if they are either `simple_expression`, or `paren_expression`
This is how things work now:
```
// have the body on a new line and indented
let …
```
> Tree-sitter-darklang: fix function declaration

- backend/tests/Tests/NewParser.Tests.fs
- packages/darklang/languageTools/parser/expr.dark
- tree-sitter-darklang/grammar.js
- tree-sitter-darklang/src/grammar.json
- tree-sitter-darklang/src/node-types.json
- tree-sitter-darklang/test/corpus/exhaustive/cli_scripts.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/let_expr.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/match.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/pipe.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/record_update.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/variables.txt
- tree-sitter-darklang/test/corpus/exhaustive/fn_decls.txt
> Tree-sitter-darklang: Fix let_expression to handle lp_tuple correctly

- backend/tests/Tests/NewParser.Tests.fs
- tree-sitter-darklang/grammar.js
- tree-sitter-darklang/src/grammar.json
- tree-sitter-darklang/src/node-types.json
- tree-sitter-darklang/test/corpus/exhaustive/comments.txt
- tree-sitter-darklang/test/corpus/exhaustive/constant_decls.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/dicts.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/fn_calls.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/if_else.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/match.txt
Misc tree-sitter-darklang grammar fixes
- ignore inline comment (//)
- use variable_identifier instead of expression for dictionaries
- add support for indented arguments in apply
> Misc tree-sitter grammar fixes

- backend/tests/Tests/NewParser.Tests.fs
- tree-sitter-darklang/grammar.js
- tree-sitter-darklang/src/grammar.json
- tree-sitter-darklang/src/node-types.json
- tree-sitter-darklang/test/corpus/exhaustive/exprs/Enum.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/dicts.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/fn_calls.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/list.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/match.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/strings.txt
- tree-sitter-darklang/test/corpus/exhaustive/module_decls.txt
This PR:
- Fixes mp_list_cons and dictionaries
- Adds support for multiline string
- Allows having type and function declarations before module declarations
- Moves enums from simple_expression to expression
> Tree-sitter-darklang: misc grammar fixes

- scripts/build/build-tree-sitter.sh
- tree-sitter-darklang/package-lock.json
The task from this [issues list](https://github.com/darklang/dark/issues/5409)
```
get the devcontainer to not re-download tree-sitter for every container restart
see build-tree-sitter script. It clones every time now but if we already have the artifact, there should be no need to re-clone.
(I ran into this recently when restarting the container on a train without internet)
```
To add the Tree Sitter artifact checking before building.
> Build Tree Sitter one time only

- packages/darklang/languageServerProtocol/language/completion.dark
- packages/darklang/languageTools/lsp-server/completions.dark
This PR implements requested change from PR #5423 : adding a CompletionItemKind type
>  #5423 Followup

- docs/dev-setup/README.md
I recently tested setting up Dark on a Windows machine, and it worked without any issues
A few others have also successfully set up Darklang on Windows, and we’ve helped them work through the issues they ran into.
specifications of the machine it was tested on:
OS Version: Windows 11 pro 24H2
Architecture: x64
> Update dev-setup docs

- backend/src/LibExecution/ProgramTypesToRuntimeTypes.fs
- backend/testfiles/execution/language/flow-control/ematch.dark
- backend/tests/Tests/PT2RT.Tests.fs
- backend/tests/Tests/TestValues.fs
- packages/darklang/cli/local-install/main.dark
- packages/darklang/stdlib/result.dark
No changelog
We had an issue when pattern matching with OR patterns that share variable names. This PR ensures variables bind to the same register. 
Previously, in patterns like:
```fsharp
match (Stdlib.Result.Result.Ok 1L, Stdlib.Result.Result.Error "error") with
| (Error err, Ok _) 
| (Ok _, Error err) -> err
```
The err variable was incorrectly bound to different registers in each branch (6 and 7). 
```fsharp
MPOr
{ head = MPTuple (MPEnum ("Error", [MPVariable 6]), MPEnum ("Ok", [MPVariable 7]), [])
tail = [MPTuple (MPEnum ("Ok", [MPVariable 6]), MPEnum ("Error", [MPVariable 7]), [])]}
```
> PT2RT: Fix MPOr + add some tests

- backend/src/BuiltinExecution/Libs/Dict.fs
No changelog
There was a `CLEANUP: terrible perf` comment for the dictSet function inside the `backend/src/BuiltInExecution/Libs/Dict.fs` file.
The reason for the poor performance was that `Map.toList` was called, and then the `@` operator (shorthand for the `List.concat` function) was called immediately afterwards to put a key-value pair at the end of the just-created list.
While cons (`(1, 3) :: list`) is an O(1) operation, List.concat/@ is an O(n) operation because it needs to traverse the whole list and put the new tuple at the end.
We can:
1. Delete the call to Map.toList
2. Delete the use of the @ operator
3. Cons a list of all elements in the map starting from the last element to the first element, *passing the tuple we want at the end as the initial list* (which erases the need …
> Performance improvement for dictSet function

- backend/src/BuiltinExecution/Libs/Dict.fs
- backend/src/LibExecution/TypeChecker.fs
- backend/testfiles/execution/stdlib/dict.dark
- packages/darklang/stdlib/dict.dark
- scripts/build/_build-server
There's a performance problem with the `dictSet` function: the dictionary is a map, which we convert to a list, only for the dictionary type-checking function to convert it back to a map.
Suboptimal performance comes from two things:
1. Converting a map to a list, only to convert the list back to a map (and adding one key).
2. Type checking every single element in the dictionary, which is unnecessary because we accept that the map is type safe as a prerequisite for the `dictSet` function.
I think we can perform fewer operations while upholding type safety.
1. Get any key/value pair from the map (preferably without searching the whole map).
2. Compare the types of the old key/value pairvwith the new key/value pair we wish to insert
3. If the old pair and the new pair have the same types, …
> Perform minimal type checking for dictSet function,

- backend/src/BuiltinExecution/Libs/Dict.fs
- backend/src/LibExecution/TypeChecker.fs
This small change to improve the performance of the `Dict.fromListOverwritingDuplicates` function has two commits.
The first commit changes the return type of `TypeChecker.DvalCreator.dictAddEntry` from `Dval` to `ValueType * DvalMap` to make the function easier to reuse in different contexts (like when folding over a data structure).
There isn't anything spooky about that: `TypeChecker.DvalCreator.dict` folds over a tuple of the same type internally before returning a `DDict`.
The only difference between how `DvalCreator.dict` and `DvalCreator.dictAddEntry` handle it is that it's the caller's responsibility to construct the `DDict` when using `dictAddEntry` (because the caller may want to do some additional checks or transformation in each fold iteration and we don't want to pattern …
> Avoid Map -> List -> Map conversion in Dict.fromListOverwritingDuplicates

- backend/testfiles/execution/stdlib/language-tools/semanticTokenization.dark
- backend/tests/Tests/NewParser.Tests.fs
- packages/darklang/languageTools/parser/expr.dark
- packages/darklang/prettyPrinter/programTypes.dark
- tree-sitter-darklang/grammar.js
- tree-sitter-darklang/src/grammar.json
- tree-sitter-darklang/src/node-types.json
- tree-sitter-darklang/test/corpus/exhaustive/constant_decls.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/Enum.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/fn_calls.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/let_expr.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/list.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/pipe.txt
- tree-sitter-darklang/test/corpus/exhaustive/module_decls.txt
No changelog
- MyEnum.MyCase() // no arg
e.g. `Stdlib.Option.Option.None()`
- MyEnum.MyCase(oneArg)
e.g. `Stdlib.Option.Option.Some(1L)`
- MyEnum.MyCase((tupleArg))
e.g. `Stdlib.Option.Option.Some((1L,2L))`
- MyEnum.MyCase(arg1, arg2)
e.g. `Stdlib.Option.Option.Some(1L,2L)`
- MyEnum.MyCase // no arg
e.g. `Stdlib.Option.Option.None`
- MyEnum.MyCase oneArg
e.g. `Stdlib.Option.Option.Some 1L`
- MyEnum.MyCase (tupleArg)
e.g. `Stdlib.Option.Option.Some((1L,2L))`
- MyEnum.MyCase (arg1, arg2)
e.g. `Stdlib.Option.Option.Some(1L,2L)`
Piping into a enum:
- arg1 |> MyEnum.MyCaseWithOneArg
e.g. `1L |>Stdlib.Option.Option.Some`
- (arg1, arg2) |>  MyEnum.MyCaseWithOneTupleArg
e.g. `(1L, 2L) |>Stdlib.Option.Option.Some`
- arg1 |> MyEnum.MyCaseWithTwoArgs 2L
e.g. `1L |>Stdlib.Option.Option.Some 2L` // …
> Improve enum_literal parsing

- backend/src/BuiltinExecution/Libs/List.fs
Small commit which addresses a CLEANUP note in `src/BuiltinExecution/Libs/List.fs`.
The note was: 
```
// CLEANUP something like type ComparatorResult = Higher | Lower | Same
// rather than 0/1/-2
```
in the context of comparing values.
This commit introduces a new `type order = Less | Equal | Greater` in List.fs and refactors the comparison functions to return it.
I thought a bit about other functional languages for the case names. Haskell uses `LT | EQ | GT`, Standard ML uses `LESS | EQUAL | GREATER` and OCaml uses integers instead of a custom order type.
Maybe the original proposal `Higher | Lower | Same` would be a bit better because the average word is less verbose? I thought it made sense to follow the conventions of another functional language but can see the other perspective too. …
> Address CLEANUP note for List.fs: use custom order type in comparison

- packages/darklang/cli/cliColors.dark
- packages/darklang/cli/command.dark
- packages/darklang/cli/syntaxHighlighting.dark
Should syntax highlighting be under a flag? Something like:
`--highlight` or `--style=highlighted` and `--style=plain`
> Add syntax highlighting functionality to `view function/type/constant` command

- packages/darklang/cli/command.dark
Previously, `view [fnName]` failed with “Function not found” when we `cd` into a non–fully qualified name (e.g. `Stdlib.List`). Now, for example, `view map` works correctly in both `Stdlib.List` and `Darklang.Stdlib.List`.
> Improve entity lookup in viewEntityByName function

- backend/src/LibExecution/Interpreter.fs
- backend/src/LibExecution/ProgramTypesToRuntimeTypes.fs
- backend/src/LibExecution/RuntimeTypes.fs
- backend/src/LibExecution/RuntimeTypesToDarkTypes.fs
- backend/testfiles/execution/language/custom-data/enums.dark
- backend/testfiles/execution/language/flow-control/ematch.dark
- backend/tests/Tests/Interpreter.Tests.fs
- backend/tests/Tests/PT2RT.Tests.fs
- packages/darklang/languageTools/runtimeErrors.dark
- packages/darklang/prettyPrinter/runtimeError.dark
- packages/darklang/prettyPrinter/runtimeTypes.dark
Before:
```
Encountered a Runtime Error:
No matching case found for value TODO - use a builtin instead of the thing that was here [] in match expression
Call stack (last call at bottom):
- Package Function PACKAGE.Darklang.Cli.executeCliCommand
- Package Function PACKAGE.Darklang.Cli.processMessages
- Package Function PACKAGE.Darklang.Cli.processMessages
```
After:
```
Encountered a Runtime Error:
No matching case found for value List<PACKAGE.Darklang.Cli.Msg> [] in match expression
Call stack (last call at bottom):
- Package Function PACKAGE.Darklang.Cli.executeCliCommand
- Package Function PACKAGE.Darklang.Cli.processMessages
- Package Function PACKAGE.Darklang.Cli.processMessages
```
Before:
```
Error when executing Script. Call-stack:
Call stack (last call at bottom):
- Package …
```
> Improve error handling for unmatched match cases

- .circleci/config.yml
The parser rarely changes but was getting rebuilt every time. Now we cache it based on the actual grammar/scanner files that matter.
> Cache parser builds in CI to speed things up

- backend/src/Cli/EmbeddedResources.fs
When launching CLI with existing .darklang dir, ask user if they want to overwrite it rather than silently skipping setup.
(the lack of this sort of mechanism caused some confusion for me a bit ago)
> Prompt to overwrite existing .darklang directory

- backend/src/BuiltinCliHost/Libs/Cli.fs
- packages/darklang/cli/cli.dark
- packages/darklang/cli/command.dark
- packages/darklang/cli/commandHelpers/view.dark
- packages/darklang/cli/init.dark
- packages/darklang/cli/model.dark
- packages/darklang/cli/msg.dark
- packages/darklang/cli/terminal.dark
- packages/darklang/cli/update.dark
The CLI now supports an interactive mode when viewing modules to:
- Navigate through different entity categories (functions, types, constants, submodules) using arrow keys
- Expand/collapse categories to see their contents
- Select individual items within categories to see definitions
Interactive mode
https://github.com/user-attachments/assets/8b2fb675-8302-47ce-a9aa-76407fe1c813
non-interactive mode
https://github.com/user-attachments/assets/908902c9-5eeb-4544-9a2d-2a407b48c74c
**Future improvements:**
- Search within viewing mode
- Show entity documentation
> Improve UX of view command

- Dockerfile
I ran into an issue with the devcontainer yesterday where the pubsub emulator wasn't running due to some Java dependency issue. This seemed to fix it for me. That said, I haven't seen the issue since, incl. on other branches, so going to leave this as a Draft until I see it again
> fix pubsub emulator startup issues
