- integration-tests/run.sh
- package-lock.json
- package.json
Seems there are some problems with 1.8.7.
This fixed integration tests.
> Pin to testcafe 1.8.6

- docs/2020-06-03-ssl-cert-rotation.md
> doc how certs in secrets get rotated

- config/dev
- scripts/gcp-proxy-db
- scripts/gcp-psql
- scripts/support/kubernetes/garbagecollector/garbagecollector-deployment.yaml.template
Also make it possible to query the replica as well as the production DB.
> As part of debugging the queue problems, disable the GC for now

- scripts/support/nginx.conf
> Forward presence.darklang.com to ops-presence

- .circleci/config.yml
- client/src/core/Decoders.ml
- docs/production/README.md
> Rename 'master' to 'main'

- esy.json
- esy.lock/index.json
- esy.lock/opam/astring.0.8.4/opam
- esy.lock/opam/cohttp-lwt.2.4.0/opam
- esy.lock/opam/cohttp.1.2.0/opam
- esy.lock/opam/conduit-lwt-unix.2.0.2/opam
- esy.lock/opam/conduit-lwt.2.0.2/opam
- esy.lock/opam/conduit.2.0.2/opam
- esy.lock/opam/cstruct.3.1.1/opam
- esy.lock/opam/ipaddr-sexp.5.0.0/opam
- esy.lock/opam/ipaddr.5.0.0/opam
- esy.lock/opam/js_of_ocaml-compiler.3.4.0/opam
- esy.lock/opam/macaddr.5.0.0/opam
- esy.lock/opam/odoc.1.5.1/opam
- esy.lock/opam/postgresql.4.5.0/opam
- esy.lock/opam/tablecloth-native.0.0.6/opam
- esy.lock/opam/uri.2.2.1/opam
- esy.lock/opam/x509.0.6.2/opam
We imported the jwt library from a place we couldn't control. This moves it inside the darklang org.
> Host jwt in the darklang org

- package-lock.json
- package.json
Dependabot does them separately, but they seem linked
> Update ppx-deriving versions

- backend/bin/get_functions_and_tlids.ml
Gets output showing where in user code package manager functions are called
> See uses of package-manager functions

- backend/test/test_other_libs.ml
> Hi, this is my first PR: added tests to List::isEmpty

- client/src/fluid/Fluid.ml
- client/test/fluid_test.ml
👋  First PR.
A fix for #2517 
I am not sure if pattern match order is perfect. Feel free to comment.
> Added auto complete in lists with comma

- client/src/app/CursorState.ml
- client/src/app/IntegrationTest.ml
- client/src/app/Main.ml
- client/src/canvas/View.ml
- client/src/components/SettingsView.ml
- client/src/components/SettingsViewTypes.ml
- client/src/core/Decoders.ml
- client/src/core/Defaults.ml
- client/src/core/Encoders.ml
- client/src/core/Types.ml
- client/src/fluid/Fluid.ml
- client/src/fluid/FluidUtil.ml
- client/src/forms/Entry.ml
- client/src/forms/KeyPress.ml
- client/src/forms/Pointer.ml
- client/src/forms/Selection.ml
- client/src/forms/ViewBlankOr.ml
- client/src/forms/ViewEntry.ml
- client/src/toplevels/Toplevel.ml
- client/src/toplevels/UserFunctions.ml
- client/test/autocomplete_test.ml
The client is pretty confusing, so this is the first of many refactors to try and make it less confusing.
> Small refactors

- client/src/toplevels/ViewIntrospect.ml
Add return type in function reference, to fix #2687 
Retrieve user function and package function return type, and display it as separated row in reference.
> Add simple returns type for function reference

- client/src/app/CursorState.ml
I accidentally broke this with a recent refactor.
> Fix focus in omnibox

- backend/jsanalysis/jsanalysis.ml
- client/src/analysis/Analysis.ml
- client/src/core/Encoders.ml
- client/src/core/Types.ml
Secrets only worked in the client-side analysis in handlers, not functions.
> Support secrets in functions

- client/src/canvas/View.ml
> Reference some more docs from within the app

- README.md
add notes on running dark on Windows in WSL2, from #2653
> add notes on running dark on Windows in WSL2

- backend/test/test_string_libs.ml
My first pull request!  Adds a test for String::toList_v1.  As far as I can tell this doesn't have tests yet.  There are some string tests in test_other_libs and others in test_string_libs, I added this in test_string_libs, not sure where you would prefer it though.
> String::toList_v1 test

- backend/libbackend/stroller.ml
- client/src/appsupport.js
Couple of small analytics fixes
> Fix analytics

- Dockerfile
- queue-scheduler/src/config.rs
- queue-scheduler/src/errors.rs
- queue-scheduler/src/lib.rs
- queue-scheduler/src/main.rs
- queue-scheduler/src/pg.rs
- queue-scheduler/src/stats.rs
- queue-scheduler/tests/helpers/mod.rs
- queue-scheduler/tests/scheduler.rs
- rustfmt.toml
- scripts/format
- scripts/support/compile
- scripts/support/kubernetes/queueworker/qw-deployment.yaml.template
- stroller/src/config.rs
- stroller/src/heapio.rs
- stroller/src/main.rs
- stroller/src/push.rs
- stroller/src/service.rs
- stroller/src/util.rs
- stroller/src/worker.rs
This started by looking into why rust wasn't working (hence installing support for formatting, rls, and adding more info to traces).
However, the solution was much simpler: a left-behind key.
> Fix pusher messages

- client/src/api/API.ml
- client/src/app/Main.ml
- client/src/canvas/View.ml
- client/src/components/SettingsView.ml
- client/src/components/SettingsViewTypes.ml
- client/src/core/Decoders.ml
- client/src/core/Defaults.ml
- client/src/core/Encoders.ml
- client/styles/_settingsView.scss
- scripts/support/compile
- scripts/support/npm-run-build-with-retry
No-one uses it, doesn't do much.
> Remove settings "about" page

- .circleci/config.yml
- dockerfile-repo/Dockerfile
I had to make the changes directly there as `git subtree` was segfaulting.
> Update to latest dockerfile repo

- client/src/app/Main.ml
- client/src/app/SavedSettings.ml
- client/src/core/Decoders.ml
- client/src/core/Defaults.ml
- client/src/core/Encoders.ml
- client/src/core/Types.ml
- client/src/fluid/FluidUtil.ml
- client/src/forms/Pointer.ml
- client/src/toplevels/Handlers.ml
- client/src/toplevels/SpecHeaders.ml
- client/src/toplevels/ViewHandler.ml
- client/src/util/ViewUtils.ml
- scripts/support/npm-run-build-with-retry
We don't use handler locking or collapsing, so remove the code.
> Remove fields/attributes we don't use

- docs/production/custom-domains.md
- scripts/gke-deploy
In the last deploy, one script had not been updated
> Fix deploy script

- README.md
Updates the readme so that the dig command is formatted correctly.
Updating the readme file
> Updates the readme so that the dig command is formatted correctly.

- backend/test/test_other_libs.ml
"Hi - this is my first pull request. I noticed that Int::greaterThan didn't have any tests so I added one."
> Add test for Int::greaterThan

- docs/production/tls-2018-08-03.markdown
- fsharp-backend/src/LibExecution/Interpreter.fs
- fsharp-backend/src/LibExecution/StdLib/LibBool.fs
- fsharp-backend/src/LibExecution/StdLib/LibList.fs
- fsharp-backend/tests/httptestfiles/subcanvas
- fsharp-backend/tests/testfiles/bool.tests
There were a few merge conflicts which caused a broken build, these are fixed here.
Adds support for Bool::isError_v0, which had a hack in the interpreter.
Adds some TLS notes
> Fix broken build and misc changes

- fsharp-backend/src/LibBackend/Account.fs
> fix regex typo in validateUserName

- fsharp-backend/src/LibBackend/File.fs
> Fix typo in checkFilename

- fsharp-backend/src/ApiServer/Api.fs
> Fix typo in Api.fs

- .devcontainer/devcontainer.json
- fsharp-backend/paket.dependencies
- fsharp-backend/paket.lock
- fsharp-backend/src/LibBackend/Db.fs
- fsharp-backend/src/LibBackend/ProgramSerialization/OCamlInterop.fs
- fsharp-backend/src/LibBackend/UserDB.fs
- fsharp-backend/src/LibExecution/DvalRepr.fs
- fsharp-backend/src/LibExecution/StdLib/LibMiddleware.fs
- fsharp-backend/src/LibExecution/paket.references
- scripts/dotnet-fsi
- scripts/support/compile
The major change here is to remove FSharp.Data to try and improve build speed. It succeeds in improving it by about 10%, although the cost of making System.Net.Json work properly for us was to add a bug hack, and that might need a subsequent hack to make that perform well in production (we'll see at a later date).
> Minor build improvements

- README.md
- dockerfile-repo/Dockerfile
- fsharp-backend/src/LibBackend/Account.fs
- fsharp-backend/src/LibBackend/Db.fs
- fsharp-backend/src/LibBackend/OCamlInterop.fs
- fsharp-backend/src/LibBackend/Password.fs
- fsharp-backend/src/LibBackend/SqlCompiler.fs
- fsharp-backend/src/LibExecution/DvalRepr.fs
- fsharp-backend/src/LibExecution/RuntimeTypes.fs
- fsharp-backend/src/LibExecution/StdLib/LibString.fs
- fsharp-backend/src/Prelude/Prelude.fs
- fsharp-backend/tests/FuzzTests/FuzzTests.fs
- fsharp-backend/tests/TestUtils/TestUtils.fs
- fsharp-backend/tests/Tests/DvalRepr.Tests.fs
- fsharp-backend/tests/Tests/OCamlInterop.Tests.fs
- fsharp-backend/tests/Tests/ProgramTypes.Tests.fs
- scripts/builder
- scripts/run-fsharp-tests
Also improves debugging with lldb, and tidy up some interoperability tests.
> Port Passwords

- README.md
On initial build the script output is: `Initial compile succeeded`
> Update README to match build script message

- fsharp-backend/tests/testfiles/dict.tests
Hi - this is my first pull request. I noticed that Dict::get_v0 and Dict::get_v1 didn't have any tests so I added some.
> Add tests for Dict::get_v0 and Dict::get_v1

- fsharp-backend/src/LibExecution/StdLib/LibInt.fs
- fsharp-backend/tests/testfiles/int.tests
Hello, this is my first code contribution to Dark. I'm totally new to both F# and OCaml so I 100% expect there is room for improvement in this PR.
> Implement FSharp version of Int::sum_v0

- fsharp-backend/src/LibExecution/StdLib/LibFloat.fs
- fsharp-backend/tests/testfiles/float.tests
Float::sum is not implemented in F#
Implement using 'fold'
Added unit tests in float.tests for successful and failed execution
> Implement Float::sum in F#

- fsharp-backend/src/LibExecution/StdLib/LibDict.fs
- fsharp-backend/tests/testfiles/dict.tests
F# version of Dict is not fully implemented
This PR implements a handful of the less complicated functions in Dict
All implemented functions are covered by unit tests
> Implement parts of F# Dict

- fsharp-backend/src/LibExecution/StdLib/LibList.fs
- fsharp-backend/tests/testfiles/list.tests
Implementation and test for List::reverse 
Implementation in F# List::reverse and the tests
Implementation in F# List::reverse and the tests
I ran ./scripts/builder --compile --test --watch and all the test passed
It will be run `git revert <commit hash>`
Yes
> Add implementation and test for List::reverse

- fsharp-backend/tests/testfiles/int.tests
Hi - this is my first pull request. I noticed that Int::clamp didn't have any tests so I added one.
> Test cases for Int::clamp

- fsharp-backend/src/LibBackend/StdLib/LibCrypto.fs
- fsharp-backend/tests/testfiles/crypto.tests
Porting remaining parts of Crypto to F#
Enabled the commented out tests and added a few more
> Port the rest of Crypto

- fsharp-backend/src/LibExecution/StdLib/LibDate.fs
- fsharp-backend/tests/testfiles/date.tests
Date has not been fully ported to F#
Ported the remaining functions except toHumanReadable which I frankly didn't understand how it was supposed to work based on the tests I tried
> Port some more Date to F#

- fsharp-backend/src/LibExecution/StdLib/LibHttp.fs
- fsharp-backend/tests/testfiles/http.tests
Add functions to `LibHttp.fs` and test to `http.test`
Add functions to `LibHtttp.fs` and test to `http.test`
Test cases passed
Yes
> Http functions

- fsharp-backend/src/LibBackend/Canvas.fs
- fsharp-backend/src/LibBackend/Cron.fs
- fsharp-backend/src/LibBackend/EventQueue.fs
- fsharp-backend/src/LibBackend/OCamlInterop.fs
- fsharp-backend/src/LibBackend/ProgramTypes.fs
- fsharp-backend/src/LibBackend/Serialize.fs
- fsharp-backend/src/LibExecution/RuntimeTypes.fs
- fsharp-backend/src/LibExecution/Shortcuts.fs
- fsharp-backend/tests/TestUtils/TestUtils.fs
- fsharp-backend/tests/Tests/Cron.Tests.fs
- fsharp-backend/tests/Tests/EventQueue.Tests.fs
- fsharp-backend/tests/Tests/OCamlInterop.Tests.fs
- fsharp-backend/tests/Tests/Tests.fs
- fsharp-backend/tests/Tests/Tests.fsproj
Implement remaining cron and eventqueue tests.
The only thing interesting here is that I turned an interval into a better type.
Edit: fetchActiveCrons can fail - fix and test
> Implement remaining EventQueue and Cron tests

- fsharp-backend/src/LibBackend/ProgramTypes.fs
- fsharp-backend/src/LibExecution/Shortcuts.fs
- fsharp-backend/src/LibExecution/StdLib/LibDict.fs
- fsharp-backend/src/Scripts/fsharpToDark.fsx
- fsharp-backend/src/Wasm/Wasm.fs
- fsharp-backend/tests/TestUtils/FSharpToExpr.fs
- fsharp-backend/tests/Tests/LibExecution.Tests.fs
- fsharp-backend/tests/httptestfiles/vars-multisegment
- fsharp-backend/tests/testfiles/big.tests
- fsharp-backend/tests/testfiles/crypto.tests
- fsharp-backend/tests/testfiles/dict.tests
- fsharp-backend/tests/testfiles/language.tests
This is the start of revamping parts of the BWD pipeline. However, it got sidetracked so this is a grab-bag of misc changes:
- parse single word functions in more cases
- Add Dict.get_v2 + test
- improve fsharpToDark script and code generation
- add a bigger tests case to Wasm.fs
- add some more crypto tests
- add a language test
> More BWD tests

- fsharp-backend/src/LibExecution/StdLib/LibList.fs
- fsharp-backend/src/Prelude/Prelude.fs
- fsharp-backend/tests/testfiles/list.tests
Add functions to `LibList.fs` and test to `list.test`
Add functions to `LibList.fs` and test to `list.test`
Test cases passed
Yes
> More LibList functions

- fsharp-backend/tests/testfiles/dict.tests
Fairly self-explanatory, adding a couple tests as a first PR as per the guide in the contributor docs.
> Add a few Dict.set_v0 tests

- .circleci/config.yml
> Actually use the new docker container

- .circleci/config.yml
- Dockerfile
- scripts/run-fsharp-tests
- scripts/support/setup-circleci-environment
Can't seem to push to #3057 so this cherrypicks the commits. Thanks @sxmanton for the fix.
> Merge changes from #3057

- fsharp-backend/src/LibExecution/StdLib/LibHttpClient.fs
- fsharp-backend/tests/testfiles/httpclient.tests
Add functions to `LibHttpClient.fs` and the test cases
Add functions to `LibHttpClient.fs` and the test cases
Test cases passed
Yes
> Add HttpClient functions

- .devcontainer/devcontainer.json
- Dockerfile
- README.md
- docs/interviewing.md
- docs/livereload.md
- docs/vscode-setup.md
Improves the README
- makes links work
- add more links
- clarify some content that was unclear
> Improve docs

- containers/ocaml-nginx/nginx.conf
- fsharp-backend/src/ApiServer/Middleware.fs
Minor fixes I found hiding in unmerged branches
> Minor fixes

- .devcontainer/devcontainer.json
- README.md
- docs/editor-setup.md
- docs/vscode-setup.md
- scripts/support/allow-docker-access
- scripts/support/initialize-vscode
Still trying to get VSCode working properly in windows as well as Mac/Linux.
These are misc changes trying to get it to work on windows. The primary issue is that directories were not always present, so trying to make that work.
> More vscode fixes

- fsharp-backend/src/LibExecution/StdLib/LibResult.fs
Migration to F#, fix errors from last PR
Errors fixed
Tests passed
> Fixes in returned values

- .devcontainer/devcontainer.json
- scripts/support/initialize-vscode
Fix a problem which happened during VS initialize, if code runs under WSL it needs to change folder /home.
> Fix container on Windows

- fsharp-backend/src/LibBackend/SqlCompiler.fs
- fsharp-backend/src/LibBackend/StdLib/LibDB2.fs
- fsharp-backend/src/LibExecution/Interpreter.fs
- fsharp-backend/src/LibExecution/StdLib/LibList.fs
- fsharp-backend/src/LibExecution/StdLib/LibString.fs
- fsharp-backend/src/Prelude/Prelude.fs
- fsharp-backend/tests/Tests/Prelude.Tests.fs
Refactoring Prelude.map_s and similar. I didn't understand how these worked originally, but now that it's clearer these can be implemented in a much simpler manner.
This has tests
> Reimplement map_s and friends using much simpler code

- fsharp-backend/src/LibExecution/StdLib/LibNoModule.fs
- fsharp-backend/tests/testfiles/nomodule.tests
Continue with the migration of the functions written in OCaml to F#.
I added some functions left in `LibNoModule.fs` and a file with tests of all functions there
All tests I added passed
> LibNoModule functions migration

- .devcontainer/devcontainer.json
- scripts/support/vscode-post-start-command
The initial build in VSCode would error, saying it couldn't find the log directory.
Create it before trying to write to it.
> Fix initial build in VsCode

- .devcontainer/devcontainer.json
- scripts/support/initialize-vscode
Trying to make cloning from a repo work directly.
> One more step to making cloning directly from the repo work

- .circleci/config.yml
- scripts/gcp-fetch-latest-containers
- scripts/gke-deploy
Deploy BlazorWorker.js so that it loads in prod. Then we can see the next step to fully deploy it.
> Deploy blazor

- backend/bin/legacyserver.ml
- backend/liblegacy/fuzzing.ml
- fsharp-backend/src/BackendOnlyStdLib/HttpClient.fs
- fsharp-backend/src/BackendOnlyStdLib/LibHttpClient5.fs
- fsharp-backend/src/LibBackend/OCamlInterop.fs
- fsharp-backend/tests/FuzzTests/FuzzTests.fs
- fsharp-backend/tests/Tests/OCamlInterop.Tests.fs
- fsharp-backend/tests/Tests/Tests.fsproj
- scripts/run-fsharp-fuzzer
fizzing httpclient, plus some related fixes:
- Make the fuzzer script work again
- Figure out and solve why the debugger was hanging
- Fuzz all 6 httpclient inner functions against their ocaml equivalents
- add some tests for httpclient inner functions
- handle edge cases found
> Fuzz httpclient

- .circleci/config.yml
> Glue together more of the CI pipeline

- .circleci/config.yml
Make sure the build is authorized properly to check k8s configs
> Fix authorization steps

- scripts/deployment/_honeymarker.sh
> Fix honeymarker to use the right name for the metrics dataset

- .circleci/config.yml
> Include the legacyserver ID

- services/apiserver-deployment/apiserver-deployment.template.yaml
This used to be only for stroller, but there's no stroller anymore
> Add pusher secret

- services/apiserver-deployment/apiserver-deployment.template.yaml
It needs to connect to the DB, even if it doesn't do much there
> Fix legacyserver ctr

- scripts/deployment/gke-deploy
Error here: https://app.circleci.com/pipelines/github/darklang/dark/1646/workflows/9aaf80c8-0684-4830-a01e-81013ce53dcd/jobs/16465
> Fix error during gke-deploy

- scripts/deployment/gke-deploy
> Fix last step in deploy

- services/apiserver-deployment/apiserver-deployment.template.yaml
- services/bwdserver-deployment/bwdserver-deployment.template.yaml
(was using wrong names for configmaps, and the names also didn't line up)
> Fix error when deploying

- containers/gcp-exechost/Dockerfile
- containers/gcp-exechost/prep.sh
- containers/gcp-fsharp-apiserver/Dockerfile
- containers/gcp-fsharp-bwdserver/Dockerfile
ExecHost isn't startiing up, looks like permissions were wrong.
> Fix issues with exechost

- containers/gcp-exechost/prep.sh
Looks like the container builds this time, so we'll see if it goes any further.
> Fix execHost again

- fsharp-backend/src/ExecHost/ExecHost.fs
Still trying to figure out the issue
> Another fix for ExecHost

- containers/gcp-fsharp-queueworker/prep.sh
- scripts/build/compile-project
- services/queueworker-deployment/README.md
- services/queueworker-deployment/queueworker-deployment.template.yaml
- services/queueworker-deployment/queueworker-network-policy.yaml
- services/queueworker-deployment/shipit.yaml
Deployments for queue workers.
This is deployed disabled, following the plan in #3267.
> Workers deployments

- fsharp-backend/src/CronChecker/CronChecker.fs
- fsharp-backend/src/ExecHost/ExecHost.fs
- fsharp-backend/src/QueueWorker/QueueWorker.fs
This adds telemetry for cronchecker, queueworker and exechost.
> Configure telemetry for queueworker, cronchecker, and exechost

- services/cron-deployment/cron-deployment.template.yaml
- services/cronchecker-deployment/cronchecker-deployment.template.yaml
> Update to steady-state number of replicas

- backend/libbackend/stored_event.ml
- backend/libbackend/stored_event.mli
- backend/libbackend/stored_function_arguments.ml
- backend/libbackend/stored_function_result.ml
- fsharp-backend/src/LibBackend/TraceFunctionArguments.fs
- fsharp-backend/src/LibBackend/TraceFunctionResults.fs
- fsharp-backend/src/LibBackend/TraceInputs.fs
One customer has so many traces that it's costing the vast majority of our cloud spend. It'll be tricky to get rid of this cost, but let's stop it from growing at least.
> Stop trace growing

- backend/libbackend/legacy.ml
- backend/libbackend/libdarkinternal.ml
- backend/libbackend/libhttpclient.ml
- backend/libbackend/libjwt.ml
- backend/libbackend/libtwilio.ml
- backend/libbackend/webserver.ml
- backend/libexecution/dval.ml
- backend/libexecution/dval.mli
- backend/libexecution/legacy.ml
- backend/libexecution/legacy.mli
- backend/libexecution/libdict.ml
- backend/libexecution/libobject.ml
- backend/libexecution/libstd.ml
- backend/liblegacyfuzzing/fuzzing.ml
- backend/test/test_analysis.ml
- backend/test/test_json.ml
- backend/test/utils.ml
- fsharp-backend/tests/httpclienttestfiles/request-json-derror
- fsharp-backend/tests/httpclienttestfiles/request-json-derror-in-object-fsharp
- fsharp-backend/tests/httpclienttestfiles/request-json-derror-in-object-ocaml
- fsharp-backend/tests/httptestfiles/response-basic-derror-in-obj
- scripts/build/compile
Based on the tests, it seems DError messages can be exposed. It's unclear how much this happens though. This adds logging so we can see how often this happens.
> Log when DError messages are shown to users

- fsharp-backend/tests/FuzzTests/FuzzTests.fs
> Fuzz passwords

- backend/libbackend/stored_function_result.ml
- backend/test/utils.ml
- fsharp-backend/src/LibBackend/TraceFunctionResults.fs
- fsharp-backend/tests/TestUtils/TestUtils.fs
- scripts/run-backend-tests
Read from v2 and v3, store results in v3.
Part of https://github.com/darklang/dark/issues/3379
> Part 2 of function_results_v3

- backend/bin/validate_data_loads.ml
- backend/libbackend/garbage_collection.ml
- backend/libbackend/stored_function_result.ml
- integration-tests/clear-db.sh
- scripts/production/_gcp-proxy-db
- scripts/production/gcp-psql
Remove the code that used function_results_v2.
Point the garbage collector at functions_results_v3.
Also cleanup gcp-psql script
> Switch all code over to function_results_v3

- scripts/build/clear-builder-volumes
per 1:1
Does this look OK as-is @pbiggar?
> Add more volumes to clear-builder-volumes script

- fsharp-backend/src/ExecHost/ExecHost.fs
- services/bwd-deployment/bwd-deployment.template.yaml
- services/cron-deployment/cron-deployment.template.yaml
- services/cronchecker-deployment/cronchecker-deployment.template.yaml
- services/editor-deployment/editor-deployment.template.yaml
- services/garbagecollector-deployment/garbagecollector-deployment.template.yaml
- services/honeycomb-agent/config.yaml
- services/postgres-honeytail-deployment/postgres-honeytail-deployment.template.yaml
- services/qw-deployment/qw-deployment.template.yaml
- services/scheduler-deployment/scheduler-deployment.template.yaml
Starting to fix rollbars in production.
First, let's make sure everything uses the right credentials.
> Fix rollbar

- services/apiserver-deployment/shipit.yaml
- services/bwdserver-deployment/bwdserver-deployment.template.yaml
- services/bwdserver-deployment/bwdserver-network-policy.yaml
- services/bwdserver-deployment/shipit.yaml
Further steps in the journey of #3460
> Move bwdserver back to the default namespace

- fsharp-backend/tests/testfiles/date.tests
Per #3262, several functions in the Date module were un- or under-tested.
Write additional tests covering these functions: `subtract`, `add`, `<`, `>`, `<=`, `>=`, `lessThan`, `greaterThan`, `lessThanOrEqualTo`, `greaterThanOrEqualTo`
Ran unit tests locally
> Add missing tests around Date module

- fsharp-backend/src/ApiServer/Api/API404.fs
- fsharp-backend/src/ApiServer/Api/APIDBs.fs
- fsharp-backend/src/ApiServer/Api/APIExecution.fs
- fsharp-backend/src/ApiServer/Api/APIInitialLoad.fs
- fsharp-backend/src/ApiServer/Api/APIOps.fs
- fsharp-backend/src/ApiServer/Api/APIPackages.fs
- fsharp-backend/src/ApiServer/Api/APISecrets.fs
- fsharp-backend/src/ApiServer/Api/APITraces.fs
- fsharp-backend/src/ApiServer/Api/APIWorkers.fs
- fsharp-backend/src/ApiServer/Functions.fs
- fsharp-backend/src/ApiServer/Http.fs
- fsharp-backend/src/ApiServer/Login.fs
- fsharp-backend/src/ApiServer/Middleware.fs
- fsharp-backend/src/ApiServer/README.md
- fsharp-backend/src/ApiServer/Ui.fs
- fsharp-backend/src/LibBackend/Op.fs
- fsharp-backend/src/LibExecution/ProgramTypes.fs
Increase in-code documentation of ApiServer, for future developers' understanding.
- adjust existing commentary from //-style to ///-style, so IDEs show the the descriptions embedded in their UIs.
- add additional commentary where relevant
> Add various in-code documentation to ApiServer

- fsharp-backend/src/BackendOnlyStdLib/LibTwilio.fs
- fsharp-backend/tests/Tests/BwdServer.Tests.fs
- fsharp-backend/tests/httptestfiles/request-empty.test
- fsharp-backend/tests/httptestfiles/request-header-unicode-invalid-name.test
- fsharp-backend/tests/httptestfiles/request-header-unicode-invalid-value.test
- fsharp-backend/tests/httptestfiles/request-header-unicode-valid.test
- fsharp-backend/tests/httptestfiles/request-header-user-agent.test
- fsharp-backend/tests/httptestfiles/request-header-x-forwarded-host-invalid.test
- fsharp-backend/tests/httptestfiles/request-header-x-forwarded-host-valid.test
- fsharp-backend/tests/httptestfiles/request-url.test
- fsharp-backend/tests/httptestfiles/url-http.test
- fsharp-backend/tests/httptestfiles/url-https.test
These were uncovered by #3513.
> Fix silently failing tests

- fsharp-backend/tests/testfiles/db.tests
Per #3262, several functions in the DB module were un- or under-tested.
Write additional tests covering the relevant fns.
> Backfill tests around DB module

- fsharp-backend/src/ApiServer/Functions.fs
- fsharp-backend/src/LibBackend/Undo.fs
- fsharp-backend/src/LibBackend/UserDB.fs
- fsharp-backend/src/LibExecution/ProgramTypes.fs
- fsharp-backend/src/LibService/Rollbar.fs
- fsharp-backend/tests/testfiles/db.tests
- fsharp-backend/tests/testfiles/httpclient.tests
- scripts/production/download-gcp-db
Fix 6 more FSTODOs:
- add test for lists in DBs
- remove TDbList FSTODOs, I feel confident they aren't used in RT (only in PT)
- remove Undo.preprocess test FSTODO - there is one already
- remove FSTODO about .Inner in rollbar - it's already handled
- add v0-v4 http2 tests
- remove FSTODO where I can't figure out what we would test
Also fix gcp-download-db, and make it save the file
> Fix some FSTODOs

- backend/liblegacyfuzzing/fuzzing.ml
- fsharp-backend/tests/testfiles/string.tests
Several String lib functions are un-tested or undertested.
Add tests.
> Backfill string tests

- fsharp-backend/tests/testfiles/int.tests
- fsharp-backend/tests/testfiles/nomodule.tests
Per #3262, several functions are un- or under-tested
Add additional tests
> Add several (comparison and math) operator tests

- fsharp-backend/src/LibBackend/Account.fs
- fsharp-backend/src/LibBackend/Analytics.fs
- fsharp-backend/src/LibBackend/Authorization.fs
- fsharp-backend/src/LibBackend/Canvas.fs
- fsharp-backend/src/LibBackend/CanvasClone.fs
- fsharp-backend/src/LibBackend/Config.fs
- fsharp-backend/src/LibBackend/Cron.fs
- fsharp-backend/src/LibBackend/Db.fs
- fsharp-backend/src/LibBackend/EventQueue.fs
- fsharp-backend/src/LibBackend/File.fs
- fsharp-backend/src/LibBackend/OCamlInterop.fs
- fsharp-backend/src/LibBackend/Routing.fs
- fsharp-backend/src/LibBackend/Session.fs
- fsharp-backend/src/LibBackend/SqlCompiler.fs
- fsharp-backend/src/LibBackend/StaticAssets.fs
- fsharp-backend/src/LibBackend/TraceInputs.fs
- fsharp-backend/src/LibBackend/Traces.fs
- fsharp-backend/src/LibBackend/Undo.fs
- fsharp-backend/src/LibBackend/UserDB.fs
- fsharp-backend/src/LibService/Config.fs
- fsharp-backend/src/LibService/ConfigDsl.fs
- fsharp-backend/src/LibService/Exception.fs
- fsharp-backend/src/LibService/FireAndForget.fs
- fsharp-backend/src/LibService/HeapAnalytics.fs
- fsharp-backend/src/LibService/Rollbar.fs
- fsharp-backend/src/LibService/Telemetry.fs
I got only part-way through LibBackend - will follow up further in a future PR
> Commentate libservice and libbackend

- fsharp-backend/src/Prelude/Prelude.fs
- fsharp-backend/src/Wasm/Wasm.fs
> Revert "Include metadata in F# Wasm exceptions"

- containers/gcp-fsharp-bwdserver/Dockerfile
It's supposed to be there and it was causing an exception.
Fixes https://github.com/darklang/dark/projects/1#card-79281071
> Add favicon to BwdServer

- fsharp-backend/src/CronChecker/CronChecker.fs
- fsharp-backend/src/LibBackend/Cron.fs
- fsharp-backend/src/LibBackend/Init.fs
I'm trying to figure out why CronChecker continues to throw exceptions that it can't connect to the DB.
> Add debugging for CronChecker's call to WaitForDB

- fsharp-backend/src/CronChecker/CronChecker.fs
- fsharp-backend/src/LibBackend/Cron.fs
- fsharp-backend/src/LibBackend/Init.fs
This went out before and broke things. This version has removed the code that was breaking.
> Re-enable debug code for cronchecker

- fsharp-backend/src/LibService/Telemetry.fs
- fsharp-backend/src/QueueWorker/QueueWorker.fs
Add more metadata to root spans
The information we really want is hostname, but the rest is interesting.
> More telemetry metadata

- fsharp-backend/src/LibService/Kubernetes.fs
Connect the shutdownCallback to SIGTERM. When kubernetes shuts down, it send a sigterm. We're supposed to use that to stop running the queues and the cronchecker, but it seems that we don't. 
I've observed some behaviour that supports this, for example traces that are weirdly cut off.
> Add sigterm handler

- scripts/deployment/_push-assets-to-cdn
> Fix to assets PR

- fsharp-backend/src/LibBackend/Password.fs
This scary looking message has almost certainly been fixed for a long time. There's a
test to fuzz passwords so I can't imagine that whatever I was trying to say here is
right.
> Remove old FSTODO

- services/apiserver-deployment/apiserver-deployment.template.yaml
- services/bwdserver-deployment/bwdserver-deployment.template.yaml
ApiServer and BwdServer are in a CrashLoopBackoff
> Fix nginx configs

- .circleci/config.yml
- Dockerfile
- scripts/build/compile
- scripts/build/compile-project
- scripts/deployment/requirements.txt
- scripts/deployment/shipit
- services/bwdserver-deployment/shipit.yaml
I started adding a very small feature to shipit and did not feel very confident doing it, so I added types to it. This makes no change to functionality, but pretty aggressively types everything.
My plan is to merge this then do a refactor to remove dups and use real types instead of dicts everywhere.
> Add types to shipit

- services/bwd-deployment/bwd-ingress.yaml
They've already been moved - this PR just makes the codebase match the ingress.
> Migrate the first users over

- services/bwdserver-deployment-darklang/bwdserver-service-backendconfig.yaml
The security policy is defined on Google Cloud
> Add securityPolicy to BwdServer

- fsharp-backend/tests/TestUtils/FSI.fs
Noticed an unused function that seemed out of place.
Migrated commentary to a ///-style comment while I was in the file.
> Tidy TestUtils/FSI.fs

- services/bwd-deployment/bwd-ingress.yaml
Waiting for the static assets fix to go to enable.
> Add more volunteers

- fsharp-backend/src/ApiServer/Api/APIOps.fs
Part of #3675 
A bug that we're seeing isn't particularly obvious, and needs more metadata to detect it. 
Plan is to merge this and debug more next time it happens.
> Add more info to find bug

- fsharp-backend/tests/httptestfiles/serve-latest.test
Should resolve #3674, but has not yet passed locally.
> Update canvas of serve-latest.test

- fsharp-backend/tests/httptestfiles/request-header-unicode-invalid-name.test
- fsharp-backend/tests/httptestfiles/request-json-value-obj-trailing-comma.test
- fsharp-backend/tests/httptestfiles/request-path-invalid-unicode.test
- fsharp-backend/tests/httptestfiles/vars-unicode-valid.test
- fsharp-backend/tests/testfiles/db.tests
- fsharp-backend/tests/testfiles/float.tests
- fsharp-backend/tests/testfiles/http.tests
- fsharp-backend/tests/testfiles/httpclient.tests
- fsharp-backend/tests/testfiles/int.tests
- fsharp-backend/tests/testfiles/json.tests
- fsharp-backend/tests/testfiles/language.tests
- fsharp-backend/tests/testfiles/list.tests
- fsharp-backend/tests/testfiles/middleware.tests
- fsharp-backend/tests/testfiles/string.tests
@StachuDotNet and I did a pass through the FSHARPONLY and OCAMLONLY tests, so ensure we were happy with them and that any differences were logged in the changelog.
This PR is a few comments, so reordering/refactoring, and a handful of new tests or test changes. After this, we're happy with the FSHARPONLY situation.
> Updates from FSHARPONLY

- services/bwd-deployment/bwd-ingress.yaml
Applied, will merge once it's clear they work
> We have two canvases we can switch over

- scripts/build/compile
- scripts/custom-domains/_add-to-db
- scripts/custom-domains/check-consistency
- scripts/custom-domains/delete-from-db
- `--production` was removed a while back
- fix some sort order issues
> Fixes for some custom-domain scripts

- services/bwd-deployment/bwd-ingress.yaml
They're already moved over, this just syncs the config.
> Even more users

- fsharp-backend/src/LibService/Rollbar.fs
- fsharp-backend/src/LibService/Telemetry.fs
We've been using Rollbar and Honeycomb a bit. This fixes a few flaws in the data going to them.
> Improve instrumentation

- services/bwd-deployment/bwd-ingress.yaml
Move more (and bigger) users over to the new server.
> Bigger users

- services/bwd-deployment/bwd-deployment.template.yaml
- services/cronchecker-deployment/cronchecker-deployment.template.yaml
- services/editor-deployment/editor-deployment.template.yaml
- services/qw-deployment/qw-deployment.template.yaml
- services/tunnel2-deployment/tunnel2-deployment.template.yaml
I went through kubernetes and checked what services were up against their limits or going over them.
This will allow node autoscaling, which should save money.
> Fix k8s limits

- services/bwd-deployment/bwd-deployment.template.yaml
- services/cronchecker-deployment/cronchecker-deployment.template.yaml
Improve size based on google feedback.
> Pick new sizes

- fsharp-backend/src/BackendOnlyStdLib/HttpClient.fs
- fsharp-backend/src/BackendOnlyStdLib/LegacyBaseHttpClient.fs
- fsharp-backend/src/BwdServer/Server.fs
- fsharp-backend/src/LibBackend/Pusher.fs
- fsharp-backend/src/LibService/FireAndForget.fs
- adds telemetry to httpclient (I couldn't get it to work globally, so I added instrumentation manually).
- adds instrumentation to FireAndForget and pusher
- add more instrumentation to bwdserver
> Improve telemetry

- fsharp-backend/src/ExecHost/ExecHost.fs
- fsharp-backend/src/LibBinarySerialization/SerializedTypesToProgramTypes.fs
- fsharp-backend/tests/Tests/ProgramTypes.Tests.fs
The changes to the canvas are made already, but I forgot to merge this.
> Another 500

- services/apiserver-deployment-darklang/apiserver-deployment.template.yaml
- services/bwdserver-deployment-darklang/bwdserver-deployment.template.yaml
- services/tunnel2-deployment/tunnel2-networkpolicy.yaml
- Don't go down to 1 server during deployment
- Use a little less CPU for the servers
- When making http requests to dark custom domains, allow them through the firewall
> Small infra fixes

- services/honeycomb-agent/config.yaml
- services/honeycomb-agent/shipit.yaml
Adds honeycomb configs for every container we have, removes those we haven't.
> Update honeycomb config

- fsharp-backend/src/LibBackend/EventQueueV2.fs
- fsharp-backend/src/QueueWorker/QueueWorker.fs
Small changes to queueworker Telemetry
> Queueworker fixes

- backend/migrations/20220515_031021_eventsv2-index-for-count.sql
- docs/eventsV2.md
- fsharp-backend/src/ApiServer/ApiServer.fs
- fsharp-backend/src/BwdServer/Server.fs
- fsharp-backend/src/CronChecker/CronChecker.fs
- fsharp-backend/src/ExecHost/ExecHost.fs
- fsharp-backend/src/LibBackend/EventQueueV2.fs
- fsharp-backend/src/LibBackend/Init.fs
- fsharp-backend/src/LibBackend/Stats.fs
- fsharp-backend/src/LibService/Init.fs
- fsharp-backend/src/QueueWorker/QueueWorker.fs
- fsharp-backend/tests/Tests/EventQueueV2.Tests.fs
Add what are hopefully the final features of the queue:
- flush the pubsub clients on shutdown
- handle the FSTODOs
- add the new queue to worker stats
- add an index
> Queueworker pass 4

- fsharp-backend/src/LibBackend/EventQueueV2.fs
This has been paging me.
It seems that the 5 second deadline doesn't return a response with an empty list of messages, it throws an Exception. Took a while to find the exception, but this looks right.
Surprisingly the emulator doesn't seem to have the same behaviour, so we're going to prod and we'll see what happens.
> Catch the exception when we don't find anything in 5 seconds

- fsharp-backend/src/LibBackend/EventQueueV2.fs
The exception wasn't being thrown until the task resolved, which happened outside the
try/catch
> Try queueworker fix again

- services/apiserver-deployment-darklang/apiserver-deployment.template.yaml
- services/bwdserver-deployment-darklang/bwdserver-deployment.template.yaml
- services/queueworker-deployment/queueworker-deployment.template.yaml
We've seen some out of memory exceptions, so let's try a bit more RAM.
> Add more memory, especially to the queueworker

- docs/production/what-to-do-if-something-goes-wrong.md
I figure this is a decent start. A good next step would be to annotate everything with full links and commands.
> Add start of incident doc

- .circleci/config.yml
in hopes of fixing #3872 and in turn #3811
I'm not sure if this will help, but it shouldn't hurt.
> Increase CI cache key of build-fsharp-backend step

- scripts/deployment/_push-assets-to-cdn
towards #3872.
Upon success/failure, I can push another commit to reverse this if you'd like.
> Output information useful in diagnosing CDN-push problem in CI

- fsharp-backend/src/BackendOnlyStdLib/HttpClient.fs
- fsharp-backend/src/BackendOnlyStdLib/LegacyBaseHttpClient.fs
- fsharp-backend/src/QueueWorker/QueueWorker.fs
- fsharp-backend/tests/testfiles/httpclient.tests
I'm debugging user stuff and I'm missing some data. This adds the data and some misc related fixes.
> Improve telemetry messages

- CODING-GUIDE.md
- fsharp-backend/src/LibBackend/TraceFunctionArguments.fs
- fsharp-backend/src/LibBackend/TraceFunctionResults.fs
- fsharp-backend/src/LibBackend/TraceInputs.fs
- fsharp-backend/src/LibBackend/UserDB.fs
- fsharp-backend/src/LibService/Rollbar.fs
An attempt to fix some exceptions I saw.
The main thing here is to remove expensive computation (that is, parsing json) out of the DB loop. That keeps the connection open longer, and those aren't an infinite resource.
May be related to some exceptions, might not.
> Exceptions pass

- scripts/deployment/_push-assets-to-cdn
> Simplify CDN push in CI: iter by mimetypes, not dirs

- fsharp-backend/src/BackendOnlyStdLib/LibTwilio.fs
- fsharp-backend/tests/testfiles/twilio.tests
Seen in a user canvas when switching the queues over.
> Use the right error type for sendText

- fsharp-backend/src/BackendOnlyStdLib/HttpClient.fs
- fsharp-backend/src/BackendOnlyStdLib/LegacyBaseHttpClient.fs
I missed a few spots when refactoring telemetry in #4014.
> Tidyup to httpclient tags

- fsharp-backend/tests/testfiles/httpclient.tests
- fsharp-backend/tests/testfiles/staticassets.tests
Let's disable these tests for now
> Disable flaky tests

- client/src/components/Tooltips.res
- client/test/prettydocs_test.res
> Update 'learn more' links to docs

- fsharp-backend/src/ApiServer/Middleware.fs
- fsharp-backend/src/BackendOnlyStdLib/LibDarkInternal.fs
- fsharp-backend/src/BwdServer/Server.fs
- fsharp-backend/src/ExecHost/ExecHost.fs
- fsharp-backend/src/LibBackend/Account.fs
- fsharp-backend/src/LibBackend/Canvas.fs
- fsharp-backend/src/LibBackend/Init.fs
- fsharp-backend/src/LibBackend/Routing.fs
- fsharp-backend/src/LibBackend/Serialize.fs
- fsharp-backend/src/Prelude/Prelude.fs
- fsharp-backend/src/Wasm/Wasm.fs
- fsharp-backend/tests/TestUtils/TestUtils.fs
- fsharp-backend/tests/Tests/ApiServer.Tests.fs
- fsharp-backend/tests/Tests/Canvas.Tests.fs
- fsharp-backend/tests/Tests/Prelude.Tests.fs
- fsharp-backend/tests/Tests/Routing.Tests.fs
- fsharp-backend/tests/httptestfiles/200-request-canvasname-can-start-with-number.test
- fsharp-backend/tests/httptestfiles/404-invalid-canvas-name-length.test
- fsharp-backend/tests/httptestfiles/404-invalid-user-name-length.test
- fsharp-backend/tests/httptestfiles/404-invalid-username-name-number.test
The intent here is for requests to stop throwing exceptions for invalid canvases.
> Add CanvasName.createExn and make CanvasName.create return a result

- .circleci/config.yml
> Split push-to-gcp into 2 jobs

- fsharp-backend/src/BwdServer/Server.fs
When creating some hostnames, we had an error "System.ArgumentException: Decoded string is not a valid IDN name. (Parameter 'ascii')", which caused [lots of exceptions](https://rollbar.com/darkops/darklang/items/3312/occurrences/231995087299/).
I think this is caused [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.hoststring.fromuricomponent?view=aspnetcore-6.0#microsoft-aspnetcore-http-hoststring-fromuricomponent(system-string)). Here's the stack trace we saw:
<details>
```
1
File ["System.Globalization.IdnMapping"](https://github.com/darklang/dark/blob/082d79974/System.Globalization.IdnMapping#L0), line 0 col 0 in System.Globalization.IdnMapping.IcuGetUnicodeCore(System.String asciiString, System.Char* ascii, System.Int32 count, System.UInt32 flags, …
```
> Catch unicode conversion errors that are tripping up the HostString

- fsharp-backend/src/Wasm/Wasm.fs
Accidentally merged PR prior to static code check
> format wasm.fs

- .circleci/config.yml
I thought there was a race, but now I think there's not. Adding comment explaining.
> Add comment for why there isn't a race

- .circleci/config.yml
- scripts/deployment/_push-assets-to-cdn
- scripts/deployment/shipit
Adds a bunch of running processes in parallel to shipit.
> Parallelize building and pushing containers

- fsharp-backend/src/BackendOnlyStdLib/LibDarkInternal.fs
- fsharp-backend/src/BackendOnlyStdLib/LibStaticAssets.fs
- fsharp-backend/src/BwdServer/Server.fs
- fsharp-backend/src/LibBackend/Account.fs
- fsharp-backend/src/LibBackend/Canvas.fs
- fsharp-backend/src/LibBackend/CanvasClone.fs
- fsharp-backend/src/LibBackend/TraceInputs.fs
- fsharp-backend/src/LibService/Telemetry.fs
- fsharp-backend/tests/Tests/Traces.Tests.fs
Small fixes to honeycomb, adding:
- reason why a http response completed for bwdserver
- libstaticassets telemetry
- some more tags for http
And removing tags that were there just to match the old ocaml http tags.
> Small improvements to honeycomb

- backend/libbackend/webserver.ml
> Remove Stroller check from readiness check

- client/src/app/BrowserListeners.res
- client/src/app/Main.res
- client/src/appsupport.js
- client/src/canvas/Page.res
- client/src/canvas/View.res
- client/src/components/Tooltips.res
- client/src/core/Defaults.res
- client/src/core/Types.res
- client/src/util/Native.res
- client/styles/_canvas.scss
- client/styles/_zindex.scss
- package-lock.json
- package.json
> Remove canvas minimap when viewing fns

- fsharp-backend/src/LibExecutionStdLib/LibDate.fs
> Mark Date::today as impure

- fsharp-backend/src/BackendOnlyStdLib/BackendOnlyStdLib.fsproj
- fsharp-backend/src/BackendOnlyStdLib/LibTwilio.fs
- fsharp-backend/src/BackendOnlyStdLib/StdLib.fs
- fsharp-backend/src/LibExecutionStdLib/LibExecutionStdLib.fsproj
- fsharp-backend/src/LibExecutionStdLib/LibHttpClientAuth.fs
- fsharp-backend/src/LibExecutionStdLib/StdLib.fs
and mark the fns as Pure, rather than Impure
Tested; works great!
> Move LibHttpClientAuth to LibExecutionStdLib

- fsharp-backend/src/ApiServer/Api/APISecrets.fs
It's a general improvement to make, not something blocked by OCaml work.
> Mark a CLEANUP item rather as a TODO

- docs/bs-tea.md
- docs/client-fuzzer.md
- docs/interviewing.md
- docs/production/accounts.md
- docs/production/auth0-branding.md
- docs/unittests.md
> Improve dev docs

- fsharp-backend/src/ApiServer/Middleware.fs
> Update username header in apiserver middleware

- client/src/analysis/Analysis.res
- client/src/api/API.res
- client/src/app/VariantTesting.res
- client/src/core/Types.res
- client/workers/Fetcher.res
> Remove fsharp-backend client "test variant"

- .circleci/config.yml
- README.md
- fsharp-backend/fsdark.sln
- fsharp-backend/paket.dependencies
- fsharp-backend/paket.lock
- fsharp-backend/src/Analysis/Analysis.fs
- fsharp-backend/src/Analysis/Analysis.fsproj
- fsharp-backend/src/Analysis/README.md
- fsharp-backend/src/Analysis/paket.references
- fsharp-backend/src/Analysis/static/BlazorWorker.js
- fsharp-backend/src/LibService/Exception.fs
- fsharp-backend/src/Prelude/Prelude.fs
- scripts/build/compile
This will resolve #4116 and resolve #4069.
> Rename Wasm.fsproj to Analysis.fsproj; add README

- .circleci/config.yml
- integration-tests/messages.ts
- integration-tests/run.sh
- integration-tests/tests.ts
- integration-tests/utils.ts
Replaces #4009. Was originally aimed to help with #3883, but delaying that portion until a further PR.
I'd recommend reviewing commit-by-commit.
> Integration test improvements

- fsharp-backend/src/BackendOnlyStdLib/LibDarkInternal.fs
- fsharp-backend/src/BackendOnlyStdLib/LibPassword.fs
- fsharp-backend/src/BackendOnlyStdLib/LibStaticAssets.fs
> Stdlib fns now all have camelCase params

- fsharp-backend/tests/Tests/HttpClient.Tests.fs
- fsharp-backend/tests/httpclienttestfiles/v0/response-redirect-to-http-relative-404.test
- fsharp-backend/tests/httpclienttestfiles/v1/response-redirect-to-http-relative-404.test
- fsharp-backend/tests/httpclienttestfiles/v2/response-redirect-to-http-relative-404.test
- fsharp-backend/tests/httpclienttestfiles/v3/response-redirect-to-http-relative-404.test
- fsharp-backend/tests/httpclienttestfiles/v4/response-redirect-to-http-relative-404.test
- fsharp-backend/tests/httpclienttestfiles/v5/response-redirect-to-http-relative-404.test
This doesn't fix any flaky tests, unfortunately, but it does provide more information about errors should they flake in the future.
> Flaky tests again

- fsharp-backend/src/BackendOnlyStdLib/LibStaticAssets.fs
- fsharp-backend/tests/testfiles/staticassets.tests
Resolves #2408 and a few CLEANUP items
> Libstaticassets cleanup

- docs/production/accounts.md
> Clarify usage of some of our production accounts in docs

- fsharp-backend/tests/testfiles/twilio.tests
These have been super flaky, and have served their purpose for now.
> Comment out twilio tests

- fsharp-backend/src/BackendOnlyStdLib/LibStaticAssets.fs
> Remove console log

- fsharp-backend/src/LibExecutionStdLib/LibResult.fs
- fsharp-backend/tests/testfiles/result.tests
> Allow non-string errors in Result::fromOption

- .circleci/config.yml
- backend/serialization/vanilla-ApiServer-Execution-Function-Params-simple.json
- backend/serialization/vanilla-ApiServer-Execution-Function-T-simple.json
- backend/serialization/vanilla-ApiServer-Execution-Handler-Params-simple.json
- backend/serialization/vanilla-Microsoft-FSharp-Collections-FSharpMap-2-System-String-ApiServer-DBs-DBStats-Stat-simple.json
- client/src/app/IntegrationTest.res
- fsharp-backend/src/Analysis/Analysis.fs
- integration-tests/tests.ts
Aimed at reproducing and then resolving #4114.
Also forces integration tests to run _not_ in UTC, via a Playwright config, so that we can actually demonstrate the issue in CI.
> Fix analysis timezone offset bug

- fsharp-backend/src/ApiServer/Ui.fs
> Allow admin fns for all admin canvases

- client/src/appsupport.js
- client/src/core/Defaults.res
- client/src/core/Types.res
- client/src/forms/Autocomplete.res
- client/test/TestViewBlankor.res
A small part of #4276 - just noticed this was unused yesterday and figured I'd tidy.
> Remove admin flag from autocomplete

- docs/running-against-production.md
Just some updates that would have been helpful to me as I was going through this.
> Update/improve 'running against prod' doc

- fsharp-backend/src/ApiServer/Http.fs
When we can't parse Json in the APIServer, let's store the json in honeycomb so we can debug it
> Record json in honeycomb when we can't parse it

- client/src/core/ProgramTypes.res
> Fix setting cronintervals

- client/src/analysis/Analysis.res
- client/src/analysis/DarkStorage.res
- client/src/app/Main.res
- client/src/appsupport.js
- client/styles/_canvas.scss
- client/styles/_fluid.scss
While trying to debug some clients code, I realized I can't reach settings if the fluid debugger is enabled. This moves the fluid debugger down enough that it doesn't cover settings.
In doing this, I realized that updates from collaborators we're not being received, due to a path which had not been updated.
Finally, this also slightly refactors some subscriptions, which do not need special keys.
> Misc frontend improvements

- client/src/fluid/Fluid.res
I added some minor commentary to clarify how pasteOverSelection works, as well as the limitation that pasting Pats does not work.
> Add commentary to Fluid.pasteOverSelection

- client/test/TestFluidPattern.res
I've resolved these in a previous PR, but forgot to uncomment them.
> Mark 2 TUPLETODOs as completed

- package-lock.json
- package.json
This doesn't seem to differ from #4394, except that for some reason the integration tests pass.
Verified each commit, and studied the changelog to make sure nothing went wrong
> Upgrade to latest pusher

- client/src/analysis/Functions.res
- client/src/analysis/Functions.resi
- client/src/app/Main.res
- client/test/FluidTestData.res
- client/test/TestRefactor.res
- fsharp-backend/src/LibExecutionStdLib/LibTuple2.fs
- fsharp-backend/src/LibExecutionStdLib/LibTuple3.fs
This will fix #4471 and will fix #4481.
> Allow Tuple2 and Tuple3 stdlib fns when in-progress setting set

- client/src/canvas/View.res
- client/src/fluid/AST.res
- client/src/fluid/Commands.res
- client/src/fluid/FeatureFlags.res
- client/src/fluid/Fluid.res
- client/src/fluid/FluidAST.res
- client/src/fluid/FluidAST.resi
- client/src/fluid/FluidAutocomplete.res
- client/src/fluid/FluidClipboard.res
- client/src/fluid/FluidCommands.res
- client/src/fluid/FluidExpression.res
- client/src/fluid/FluidExpression.resi
- client/src/fluid/FluidTokenizer.res
- client/src/fluid/FluidView.res
- client/src/fluid/IfToMatch.res
- client/src/fluid/Refactor.res
- client/test/TestFluidClipboard.res
incl pattern handling rewrite.
This is WIP - I feel that I'm close, but unfortunately will be largely away for a few days.
IMO it's a merge-able improvement as-is, and fixes #4235 at minimum. Happy to wait until I'm able to revisit, though.
> (start) Fluid reconstruction improvements 

- docs/release
> Add a doc explaining how to do a "release"

- README.md
- client/src/canvas/View.res
- docs/production/accounts.md
- docs/production/what-to-do-if-something-goes-wrong.md
- docs/vscode-setup.md
- fsharp-backend/src/BwdServer/Server.fs
- fsharp-backend/src/LibBackend/SqlCompiler.fs
> Refer to discord instead of Slack

- client/src/fluid/Fluid.res
- client/test/FluidFuzzer.res
- client/test/TestFluidClipboard.res
- client/test/TestFluidMatchPattern.res
resolving some minor TUPLETODOs.
best to review with whitespace changes hidden - the second commit here is largely just indentation.
> Resolving a few tuple todos

- integration-tests/playwright.config.ts
fiddling back and forth hoping I figure out why CI is hanging on Integration Tests
> Add additional playwright timeouts

- integration-tests/playwright.config.ts
> I speculate this will help us debugwhen integration tests hang in CI

- bsconfig.json
- client/src/analysis/Functions.res
- package-lock.json
- package.json
Switch to the published, updated version.
> Switch to tablecloth 0.8.0

- .github/pull_request_template.md
> Update GitHub PR template to include changelog

- .github/dependabot.yml
No changelog
Small cleanup to dependabot: remove settings that aren't necessary.
> Tidy dependabot.yml

- fsharp-backend/src/ApiServer/Templates/ui.html
Changelog:
```
Editor
- upgrade icons to Fontawesome 6
```
> Upgrade to fontawesome 6

- scripts/deployment/deploy-lock-wait-and-acquire
Changelog:
```
Internal improvements
- deploy when no deploy locks are present
```
> When there's no deploy lock, it's safe to deploy

- client/src/api/API.res
- fsharp-backend/src/ApiServer/ApiServer.fs
- fsharp-backend/tests/Tests/ApiServer.Tests.fs
Changelog:
```
Internal changes
- Remove old POST APIs that have already been replaced by GET APIs
```
> Remove old API endpoints

- client/src/components/Settings/SettingsView.res
- client/styles/_settingsView.scss
- tailwind.config.js
Changelog:
```
Internal
- Update settingsView to use TailwindCSS
```
**Changes:**
- Convert settingsView to Tailwind.
- Remove unused CSS.
**Before -> After**
> Convert settingsView to Tailwind

- client/src/api/APIErrorHandler.res
- client/src/app/Main.res
- client/src/app/Rollbar.res
- client/src/canvas/Viewport.res
- client/src/fluid/FluidAutocomplete.res
- client/src/fluid/FluidCommands.res
- client/src/fluid/FluidView.res
- client/src/toplevels/ViewData.res
- client/src/util/Native.res
This replaces most Native externals with their rescript-webapi equivalents.
> Remove some externals and use rescript-webapi instead

- client/src/api/APIErrorHandler.res
- client/src/app/Rollbar.res
> Use reload instead of reloadWithForce

- client/src/appsupport.js
> appsupport.js desktop support check now case-insensitve

- backend/.ocamlformat
> Remove unused .ocamlformat file

- integration-tests/tests.ts
> Skip flaky test

- .circleci/config.yml
- .circleci/gcp-workflow-identity-config.json
No changelog
Some remaining CircleCI builds are broken, trying to push assets to the CDN.
> Fix CircleCI push (step 3)

- integration-tests/_integration-test-results-to-honeycomb.sh
- scripts/deployment/_notify-deployment-honeycomb
> Change key name to be clearer

- .circleci/config.yml
> Don't run dependabot where it doesn't have permission

- integration-tests/test-list.sh
- scripts/deployment/_deploy-lock-request
- scripts/deployment/deploy-lock-one-add
> Remove unused `set -x`

- backend/serialization/vanilla_ClientTypes-Analysis-PerformAnalysisParams_function.json
- backend/serialization/vanilla_ClientTypes-Analysis-PerformAnalysisParams_handler.json
- backend/serialization/vanilla_ClientTypes-Runtime-Dval-T_complete.json
- backend/serialization/vanilla_LibBackend-TraceCloudStorage-CloudStorageFormat_simple.json
- backend/serialization/vanilla_LibExecution-AnalysisTypes-TraceData_testTraceData.json
- backend/serialization/vanilla_LibExecution-DvalReprInternalRoundtrippable-FormatV0-Dval_complete.json
- backend/serialization/vanilla_Microsoft-FSharp-Core-FSharpResult-2-System-Tuple-4-System-Guid-System-Collections-Generic-Dictionary-2-System-UInt64-ClientTypes-Analysis-ExecutionResult-System-Int32-NodaTime-Instant-System-String-_simple.json
- backend/src/ClientTypes/ClientRuntimeTypes.fs
- backend/src/ClientTypes2ExecutionTypes/RuntimeTypes.fs
- backend/src/HttpMiddleware/Http.fs
- backend/src/LibExecution/DvalReprDeveloper.fs
- backend/src/LibExecution/DvalReprInternalRoundtrippable.fs
- backend/src/LibExecution/RuntimeTypes.fs
- backend/src/LibExecutionStdLib/LibHttp.fs
- backend/testfiles/execution/http.tests
- backend/tests/FuzzTests/ExecutePureFunctions.FuzzTests.fs
- backend/tests/TestUtils/LibTest.fs
- backend/tests/TestUtils/TestUtils.fs
- backend/tests/Tests/DvalRepr.Tests.fs
- backend/tests/Tests/Serialization.TestValues.fs
- backend/tests/Tests/Serialization.Vanilla.Tests.fs
Changelog:
```
Area of change
- Remove Http Redirect
```
> Remove HTTP Redirect

- backend/src/LibExecution/DvalReprDeveloper.fs
- backend/src/LibExecution/ProgramTypesParser.fs
- backend/src/LibExecutionStdLib/StdLib.fs
- backend/testfiles/execution/date.tests
- backend/testfiles/execution/db.tests
- backend/tests/Tests/ProgramTypes.Tests.fs
Changelog:
```
Language
- Remove date infix functions
```
> Remove date infix functions

- backend/src/BackendOnlyStdLib/StdLib.fs
- backend/testfiles/execution/db.tests
Changelog:
```
StdLib
- remove remaining function aliases
```
> Remove BackendOnlyStdlib fn renames

- backend/src/BwdServer/BwdServer.fsproj
- backend/src/CanvasHack/CanvasHack.fsproj
- backend/src/CronChecker/CronChecker.fsproj
- backend/src/ExecHost/ExecHost.fsproj
- backend/src/Executor/Executor.fsproj
- backend/src/QueueWorker/QueueWorker.fsproj
- backend/tests/Tests/Tests.fsproj
- scripts/build/compile
- scripts/builder
- scripts/devcontainer/_create-cache-directories
- scripts/run-backend-server
- scripts/run-backend-tests
Changelog:
```
Contributor Experience
- support native arm64 builds
```
> Arm64 fixes

- backend/src/BackendOnlyStdLib/LibDarkInternal.fs
- backend/src/LibBackend/Account.fs
- backend/tests/Tests/Account.Tests.fs
Changelog:
```
Tech debt
- Remove authentication
```
> Remove authentication

- .circleci/config.yml
- Dockerfile
No Changelog
Makes the dockerfile 20% smaller (3.2GB vs 4GB).
> Remove some stuff from the Dockerfile

- backend/testfiles/execution/language.tests
The main goal was to test for negative 0.0.
> Test for weird floats

- backend/src/CanvasHack/Main.fs
- scripts/run-canvas-hack
Changelog:
```
CanvasHack:
- remove some spam details when running
- add list of generated handlers and host when running
- ensure stdout is flushed
- add support for --help
- don't swallow exit code
- allow running script with no parameters
```
> Improve canvas hack main

- backend/experiments/BwdDangerServer/BwdDangerServer.fsproj
Fixes [this issue](https://discord.com/channels/1015413734153388094/1015413734644137987/1095289689700835340) where the project would rebuild correctly.
> fix BwdDangerServer.fsproj references

- backend/src/BackendOnlyStdLib/LibDarkInternal.fs
> Remove some TRecords

- backend/src/LibExecutionStdLib/LibJson.fs
- canvases/dark-elmish-counter/README.md
- canvases/dark-elmish-counter/config.yml
- canvases/dark-elmish-counter/main.dark
- canvases/dark-elmish-editor/README.md
- canvases/dark-elmish-editor/config.yml
- canvases/dark-elmish-editor/main.dark
Changelog:
```
Experiment
- commit unfinished 'elmish' experiment canvases
```
I'd like to revisit this at some point.
For now, just committing the canvases to get them off of my fork / out of my head.
> Commit unfinished elmish experiment canvases

- backend/experiments/packages/openai.dark
> Add link to additional openai package experimental work

- Dockerfile
No changelog
Fix the emscripten installation failed error on an arm64 machine
> Fix build issues caused by emscripten

- canvases/dark-repl/main.dark
> Improve dark-repl

- .vscode/extensions.json
- canvases/dark-editor-vue/src/components/Accordion.vue
- canvases/dark-editor-vue/src/components/AutoSizeTextarea.vue
- canvases/dark-editor-vue/src/components/ResponseChat.vue
- canvases/dark-editor-vue/src/components/UserChat.vue
- canvases/dark-repl/README.md
No changelog
Updates:
- Add volar to the recommended extensions
- Use Composition API everywhere.
- Update dark-repl's README
- Try to follow Vue best practices  -Don't update props directly by the child component. instead, emit events to the parent component to trigger changes.
> Use Composition API everywhere + some cleanups

- .gitignore
- backend/experiments/CanvasHack/Main.fs
- canvases/dark-editor/template.secrets
Changelog:
```
CanvasHack
- add support for loading a .secrets file per-canvas, locally (.gitignore'd)
```
> CanvasHack: load .secrets file

- canvases/dark-editor-vue/package-lock.json
- canvases/dark-editor-vue/package.json
- canvases/dark-editor-vue/src/components/Accordion.vue
- canvases/dark-editor-vue/src/components/ResponseChat.vue
- canvases/dark-editor-vue/src/views/MainView.vue
Changelog:
```
Area of change
- details
```
This adds Codemirror and integrates it into the response component
> Add codemirror and use it in Response component

- backend/src/Wasm/DarkEditor.fs
- backend/src/Wasm/Libs/Editor.fs
- backend/static/dark-wasm-webworker.js
- backend/static/editor-bootstrap.js
- backend/static/webworker-fake-env.js
- canvases/dark-editor-vue/src/App.vue
- canvases/dark-editor/client.dark
- canvases/dark-editor/main.dark
- canvases/dark-repl/assets/client.dark
- canvases/dark-repl/assets/index.html
- canvases/dark-repl/assets/index.js
- canvases/dark-repl/main.dark
- scripts/build/compile
Changelog:
```
WebAssembly runtime
- now loads in a WebWorker
```
Loads the Darklang WASM runtime _in a webworker_.
In some cases, this un-blocks the UI thread.
> Run wasm runtime in webworker (to stop blocking UI thread in some edge cases)

- canvases/dark-cli-demo/main.dark
- canvases/dark-repl/assets/client.dark
- canvases/dark-repl/main.dark
- canvases/dark-single-file-canvas/main.dark
- canvases/dark-tree-sitter-demo/main.dark
No changelog
This Updates the canvases to reflect the recent packages changes.
> fix dark-single-file-canvas

- .circleci/config.yml
- .circleci/gcp-workload-identity-config.json
- tf/.terraform.lock.hcl
- tf/iam.tf
- tf/workload_identity_pool.tf
Changelog:
```
Internal
- use new OIDC setup connecting circle to GCP
```
> Use new OIDC setup connecting circle to GCP

- tf/workload_identity_pool.tf
> terraform: reference main by heads, not head

- .circleci/config.yml
> Go back to using CIRCLE_OIDC_TOKEN v1 (for now)

- .circleci/config.yml
> Set gcloud account before trying to access gcp

- .circleci/config.yml
- tf/iam.tf
- tf/workload_identity_pool.tf
> Diagnose gcp access issue

- .circleci/config.yml
> readd --brief to gcloud auth login

- backend/src/HttpMiddleware/Http.fs
- backend/src/LibExecution/Interpreter.fs
- backend/src/StdLibDarkInternal/Helpers/ProgramTypesToDarkTypes.fs
- backend/src/StdLibDarkInternal/Libs/Canvases.fs
- backend/src/StdLibDarkInternal/Libs/Packages.fs
- backend/src/StdLibDarkInternal/StdLib.fs
- backend/src/StdLibDarkInternal/StdLibDarkInternal.fsproj
- backend/src/StdLibExecution/Libs/Json.fs
- backend/testfiles/execution/dict.tests
- canvases/dark-editor/main.dark
- packages/darklang/prettyPrinter/common.dark
- packages/darklang/prettyPrinter/packages.dark
- packages/darklang/prettyPrinter/programTypes.dark
- packages/darklang/stdlib/http.dark
- packages/darklang/stdlib/programTypes.dark
- scripts/clear-canvas.sh
- scripts/clear-db.sh
```
packages/pretty-printer
- continue pretty-printing of ProgramTypes and Packages
```
> Further pretty printing

- backend/experiments/cli/Cli.fs
- backend/src/HttpMiddleware/Http.fs
- backend/src/LibExecution/Interpreter.fs
- backend/src/LibExecution/RuntimeTypes.fs
- backend/src/LibExecution/StdLib.fs
- backend/src/StdLibCli/Libs/Directory.fs
- backend/src/StdLibCli/Libs/Environment.fs
- backend/src/StdLibCli/Libs/Output.fs
- backend/src/StdLibCli/Libs/Process.fs
- backend/src/StdLibCli/StdLib.fs
- backend/src/StdLibCli/StdLibCli.fsproj
- backend/src/StdLibDarkInternal/Helpers/ProgramTypesToDarkTypes.fs
- backend/src/StdLibDarkInternal/Libs/Canvases.fs
- backend/src/StdLibDarkInternal/Libs/Packages.fs
- backend/src/StdLibExecution/Libs/NoModule.fs
- backend/testfiles/execution/language.tests
- backend/testfiles/execution/result.tests
- packages/darklang/stdlib/process.dark
- packages/darklang/stdlib/result.dark
- scripts/build/compile
- scripts/build/reload-packages
- scripts/deployment/buildcontainers.dark
- scripts/run-backend-server
- scripts/run-backend-tests
- Add cli `debug` function
- print exceptions in CLI
- fix execution so we get earlier errors before later ones
- Start Process module and package
- Rename EnvVar package to Environment
- Add Result.collect
- Make reloading packages faster
> More steps to build containers (in Dark)

- backend/src/StdLibDarkInternal/Libs/Packages.fs
> fix Packages.all return type

- packages/darklang/prettyPrinter/programTypes.dark
> Tidy pretty-printing

- backend/experiments/StdLibExperimental/Libs/Experiments.fs
> Remove unused experimental stdlib fns

- canvases/dark-editor/main.dark
- canvases/dark-exportable/README.md
- canvases/dark-exportable/config.yml
- canvases/dark-exportable/main.dark
> remove unused dark-exportable canvas

- packages/darklang/prettyPrinter/programTypes.dark
No changelog
Make pipe exprs pretty-printing work
> Make pipe exprs pretty-printing work

- packages/darklang/prettyPrinter/programTypes.dark
- packages/darklang/stdlib/programTypes.dark
No changelog
This is a follow up to #4965 (Support typeArgs by moving them into a TypeDeclaration)
> TypeDeclaration changes follow-ups

- backend/testfiles/execution/db.tests
> Add some db tests

- backend/experiments/CanvasHack/CanvasHack.fsproj
- backend/experiments/CanvasHack/Main.fs
No changelog
avails functions like `unwrap`
> provide more builtins to canvashack parsing

- backend/src/StdLibDarkInternal/Libs/Packages.fs
- packages/darklang/prettyPrinter/packages.dark
- packages/darklang/prettyPrinter/programTypes.dark
- packages/darklang/stdlib/httpclient.dark
- packages/darklang/stdlib/packages.dark
- packages/darklang/stdlib/process.dark
- packages/openai.dark
Changelog:
```
Area of change
- Pretty-print constants
```
This PR:
- Adjusts the pretty-printer to work properly with the new name resolution updates
- Adds constants, EDict, and EConstant pretty-printing
> Pretty-print constants + Misc fixes

- scripts/build/compile
- scripts/run-backend-server
No changelog
Works for me - what you were expecting, @pbiggar ?
> Load packages less often

- backend/src/LibCloud/SqlCompiler.fs
- backend/testfiles/execution/cloud/db.dark
> resolve type aliases in lambdaToSql

- backend/serialization/vanilla_LibCloud-TraceCloudStorage-CloudStorageFormat_simple.json
- backend/src/Cli/Libs/Cli.fs
- backend/src/LibExecution/DvalReprDeveloper.fs
- backend/src/LibExecution/DvalReprInternalQueryable.fs
- backend/src/LibExecution/DvalReprInternalRoundtrippable.fs
- backend/src/LibExecution/Errors.fs
- backend/src/LibExecution/Interpreter.fs
- backend/src/LibExecution/RuntimeTypes.fs
- backend/src/LibExecution/TypeChecker.fs
- backend/src/LibHttpMiddleware/Http.fs
- backend/src/LocalExec/Libs/Cli.fs
- backend/src/LocalExec/Libs/Packages.fs
- backend/src/LocalExec/Libs/Packages2.fs
- backend/src/StdLibCli/Libs/Process.fs
- backend/src/StdLibDarkInternal/Helpers/ProgramTypesToDarkTypes.fs
- backend/src/StdLibDarkInternal/Libs/Canvases.fs
- backend/src/StdLibDarkInternal/Libs/Packages.fs
- backend/src/StdLibExecution/Libs/Json.fs
- backend/src/StdLibExecution/Libs/List.fs
- backend/src/StdLibExecution/Libs/NoModule.fs
- backend/testfiles/execution/language/type-alias.dark
- backend/testfiles/execution/language/type-record.dark
- backend/tests/TestUtils/TestUtils.fs
- backend/tests/Tests/DvalRepr.Tests.fs
- Add more tests for records with type args
- errors now use the original source type
- duplicate record keys are now errors
- handle type aliases with type args
> More work on the type system.

- backend/testfiles/execution/cloud/db.dark
- canvases/dark-packages/main.dark
> Fix db test

- backend/src/LibCliExecution/PackageManager.fs
> Remove old NonStandardOption

- backend/serialization/vanilla_LibCloud-TraceCloudStorage-CloudStorageFormat_simple.json
- backend/src/LibExecution/DvalReprDeveloper.fs
- backend/src/LibExecution/DvalReprInternalQueryable.fs
- backend/src/LibExecution/DvalReprInternalRoundtrippable.fs
- backend/src/LibExecution/Interpreter.fs
- backend/src/LibExecution/ProgramTypesToRuntimeTypes.fs
- backend/src/LibExecution/RuntimeTypes.fs
- backend/src/LibExecution/TypeChecker.fs
- backend/src/StdLibDarkInternal/Helpers/ProgramTypesToDarkTypes.fs
- backend/src/StdLibExecution/Libs/Dict.fs
- backend/src/StdLibExecution/Libs/Json.fs
- backend/src/StdLibExecution/Libs/List.fs
- backend/src/StdLibExecution/Libs/NoModule.fs
- backend/src/StdLibExecution/Libs/Option.fs
- backend/src/StdLibExecution/Libs/Result.fs
- backend/testfiles/execution/language/type-alias.dark
- backend/tests/TestUtils/TestUtils.fs
Handle creation of Enums when an alias points to the enum.
> Handle type args in aliases that point to enums

- backend/src/StdLibExecution/Libs/String.fs
- backend/testfiles/execution/stdlib/string.dark
- canvases/dark-packages/main.dark
- packages/darklang/cli/cli.dark
- packages/darklang/prettyPrinter/programTypes.dark
- packages/darklang/stdlib/string.dark
- packages/openai.dark
Changelog:
```
Cli
- Add show command
```
currently:
`show @Owner.Modules.functionName` =>  pretty-prints a function
`show @Owner.Modules.TypeName` =>  pretty-prints a type
`show @Owner.Modules.constantName` =>  pretty-prints a constant
> Add Show command

- canvases/dark-packages/main.dark
- packages/darklang/cli/cli.dark
Changelog:
No changelog
This PR expands the show command to show modules and owner
> Add show module

- canvases/dark-packages/main.dark
> Show module follow-up

- backend/src/StdLibCliHost/Libs/Cli.fs
- packages/darklang/cli/cli.dark
Changelog:
```
Cli
- Enable the execution of package functions from the CLI
```
> Enable the execution of package functions from the CLI

- canvases/dark-editor/system-prompt-cli.txt
- canvases/dark-packages/main.dark
- packages/darklang/cli/cli.dark
- packages/openai.dark
Changelog:
```
Cli
- Enable the Cli to interact with the OpenAI API. 
```
This will enable users to send prompts through the CLI and save the generated output into a specified script
> call OpenAI from the CLI 

- canvases/dark-editor/system-prompt-cli.txt
- canvases/dark-packages/main.dark
- packages/darklang/cli/cli.dark
- packages/darklang/prettyPrinter/programTypes.dark
- packages/openai.dark
No changelog
This PR tackles the feedback received on #5032.
> Call OpenAI from the cli - follow-ups

- .circleci/config.yml
- Dockerfile
- backend/Directory.Build.props
- backend/global.json
There are new options in F# for parallel compilation: https://blog.nojaf.com/2023/08/22/unleashing-parallel-processing-in-your-fsharp-compiler/
This enables them. I didn't notice a speedup personally.
Update some other stuff while we're here.
> Update .net to use some new options

- backend/src/LibParser/NameResolver.fs
> hotfix name resolver

- backend/testfiles/execution/stdlib/json.dark
No changelog
This PR fills in some JSON tests
> Add some Json tests

- packages/darklang/stdlib/list.dark
- packages/darklang/stdlib/option.dark
- packages/darklang/stdlib/result.dark
- packages/darklang/stdlib/string.dark
- packages/darklang/stdlib/tuple2.dark
- packages/darklang/stdlib/tuple3.dark
No changelog
Add missing descriptions, add some spacing, and remove the over-use of pipes now that we can apply functions directly.
> Cleanup package functions

- backend/testfiles/execution/stdlib/list.dark
- packages/darklang/stdlib/list.dark
> Move Some List and String builtins to packages - followup

- backend/testfiles/execution/stdlib/string.dark
- packages/darklang/stdlib/string.dark
> Add some String.fromBytes and String.fromBytesWithReplacement tests

- backend/src/BuiltinExecution/Libs/Dict.fs
- backend/src/BuiltinExecution/Libs/List.fs
- backend/src/LibBinarySerialization/ProgramTypesToSerializedTypes.fs
- backend/src/LibBinarySerialization/SerializedTypes.fs
- backend/src/LibCliExecution/PackageManager.fs
- backend/src/LibExecution/ProgramTypes.fs
- backend/src/LibExecution/ProgramTypesToDarkTypes.fs
- backend/src/LibExecution/ProgramTypesToRuntimeTypes.fs
- backend/src/LibParser/FSharpToWrittenTypes.fs
- backend/src/LibParser/WrittenTypes.fs
- backend/src/LibParser/WrittenTypesToProgramTypes.fs
- backend/testfiles/execution/cloud/db.dark
- backend/testfiles/execution/stdlib/dict.dark
- backend/testfiles/execution/stdlib/list.dark
- canvases/dark-packages/main.dark
- packages/darklang/languageTools/programTypes.dark
- packages/darklang/prettyPrinter/programTypes.dark
- packages/darklang/stdlib/dict.dark
- packages/darklang/stdlib/list.dark
- packages/darklang/test/test.dark
Changelog:
```
Area of change
- Add support for list and dict constant
```
Remaining built-in constants to move: (uncertain about how to move them)
- Bytes
- LibTest (Float constants)
> Add support for list and dict constant

- backend/src/LibCloud/SqlCompiler.fs
- backend/testfiles/execution/cloud/db.dark
Changelog:
```
SQLCompiler
- Inline user functions in the SQLCompiler
```
> Inline user functions in the SQLCompiler

- backend/experiments/BwdDangerServer/Libs/Experiments.fs
- backend/src/BuiltinCli/Libs/Directory.fs
- backend/src/BuiltinCli/Libs/Environment.fs
- backend/src/BuiltinCli/Libs/File.fs
- backend/src/BuiltinCliHost/Libs/Cli.fs
- backend/src/BuiltinCloudExecution/Libs/DB.fs
- backend/src/BuiltinDarkInternal/Libs/Canvases.fs
- backend/src/BuiltinDarkInternal/Libs/Domains.fs
- backend/src/BuiltinDarkInternal/Libs/Secrets.fs
- backend/src/BuiltinExecution/Libs/Base64.fs
- backend/src/BuiltinExecution/Libs/Char.fs
- backend/src/BuiltinExecution/Libs/DateTime.fs
- backend/src/BuiltinExecution/Libs/Dict.fs
- backend/src/BuiltinExecution/Libs/Float.fs
- backend/src/BuiltinExecution/Libs/HttpClient.fs
- backend/src/BuiltinExecution/Libs/Int.fs
- backend/src/BuiltinExecution/Libs/Json.fs
- backend/src/BuiltinExecution/Libs/List.fs
- backend/src/BuiltinExecution/Libs/Math.fs
- backend/src/BuiltinExecution/Libs/String.fs
- backend/src/BuiltinExecution/Libs/Uuid.fs
- backend/src/BuiltinExecution/Libs/X509.fs
- backend/src/LibExecution/Dval.fs
- backend/src/LibExecution/ProgramTypesToDarkTypes.fs
- backend/src/LibExecution/RuntimeTypesToDarkTypes.fs
- backend/src/LibExecution/TypeChecker.fs
- backend/src/LocalExec/Libs/Packages2.fs
- backend/src/Wasm/Libs/Editor.fs
- backend/tests/TestUtils/LibTest.fs
- backend/tests/TestUtils/TestUtils.fs
Final(?) preamble step before adding Types argument to Dval.enum and Dval.record
> Make dval result and option fns ply

- backend/src/BuiltinExecution/Libs/Bool.fs
- backend/src/BuiltinExecution/Libs/Int.fs
- backend/src/BuiltinExecution/Libs/Json.fs
- backend/testfiles/execution/stdlib/json.dark
Remove some test code that's caught by typechecking
Handle edge cases of Json parsing in Ints, Chars, Strings, nested Lists, 
Turn many bad errors into good errors
> Improve JSON libs a bit more

- backend/src/BuiltinExecution/Libs/Float.fs
- packages/darklang/stdlib/char.dark
- packages/darklang/stdlib/dict.dark
- packages/darklang/stdlib/float.dark
- packages/darklang/stdlib/list.dark
- packages/darklang/stdlib/string.dark
> Use package functions whenever possible

- backend/tests/Tests/SqlCompiler.Tests.fs
> Fix conflict

- backend/tests/Tests/SqlCompiler.Tests.fs
> #5083 followup

- backend/experiments/BwdDangerServer/Builtin.fs
- backend/experiments/BwdDangerServer/DangerExecution.fs
- backend/experiments/CanvasHack/Main.fs
- backend/src/BuiltinCli/Builtin.fs
- backend/src/BuiltinCliHost/Builtin.fs
- backend/src/BuiltinCliHost/Libs/Cli.fs
- backend/src/BuiltinCloudExecution/Builtin.fs
- backend/src/BuiltinDarkInternal/Builtin.fs
- backend/src/BuiltinExecution/Builtin.fs
- backend/src/Cli/Cli.fs
- backend/src/LibCloudExecution/CloudExecution.fs
- backend/src/LibExecution/Builtin.fs
- backend/src/LocalExec/Builtin.fs
- backend/src/LocalExec/Libs/Cli.fs
- backend/src/LocalExec/Libs/Packages2.fs
- backend/src/LocalExec/LocalExec.fs
- backend/src/Wasm/Builtin.fs
- backend/src/Wasm/DarkEditor.fs
- backend/src/Wasm/Libs/Editor.fs
- backend/tests/TestUtils/TestUtils.fs
no-op; just a cleanup of unused stuff
> Remove builtin type renames

- tf/apis.tf
- tf/cloudstorage.tf
- tf/iam.tf
- tf/pubsub.tf
- tf/workload_identity_pool.tf
This is the terraform code - already applied.
> Rebuild the infra in the new project

- backend/src/BuiltinExecution/Libs/String.fs
No changelog
Optimize String.slice
> Optimize String.slice

- backend/testfiles/httpclient/v0/basic-delete-helper-function.test
- backend/testfiles/httpclient/v0/basic-get-helper-function.test
- backend/testfiles/httpclient/v0/basic-head-returns-body-helper-function.test
- backend/testfiles/httpclient/v0/basic-options-helper-function.test
- backend/testfiles/httpclient/v0/basic-post-helper-function.test
- backend/testfiles/httpclient/v0/basic-put-helper-function.test
- packages/darklang/stdlib/httpclient.dark
Changelog:
```
Stdlib
- Add some helper functions (get, post, put, delete, options, and head)
```
> Add some helper functions (get, post, put, delete, options, and head)

- Dockerfile
- backend/src/LibCloud/Config.fs
- backend/src/LibService/Config.fs
- backend/src/LibService/ConfigDsl.fs
- containers/base-service-Dockerfile
- containers/bwdserver/Dockerfile
- containers/fsharp-service-Dockerfile
- scripts/deployment/newdeploy.sh
- tf/apis.tf
- tf/artifact_registry.tf
- tf/cloudrun.tf
- tf/iam.tf
- tf/secrets.tf
- tf/service_env_vars.tf
This is enough to enable BwdServer running on Cloud run.
Doesn't do CI.
Fixes building docker containers, pushing to the cloud, running cloud run (including configuring secrets/IAM), and starting up BwdServer.
> Add cloud run

- backend/testfiles/execution/stdlib/int8.dark
- backend/testfiles/execution/stdlib/uint64.dark
>  Add some int8 and uint64 tests - #5155 followup

- .circleci/config.yml
- .devcontainer/devcontainer.json
- Dockerfile
- scripts/build/compile
- scripts/builder
- scripts/devcontainer/_start-yugabyte
- scripts/run-backend-tests
Yugabyte failed to start (and did so very slowly), due to missing binaries. Fixed.
Also refactors the compile script a little bit - it now hits the right path more often.
> Fix local yugabyte problems

- .gitignore
- parser/tree-sitter-darklang/.gitignore
- scripts/build/compile
> reduce compile noise for misc parser files

- backend/src/LibCloud/Init.fs
- backend/src/LibService/DBConnection.fs
- scripts/build/compile
- tf/cloudrun.tf
Also more debugging for DB issues
> Fix breakage to compile script

- .circleci/config.yml
- containers/base-service-Dockerfile
- containers/bwdserver/Dockerfile
- containers/fsharp-service-Dockerfile
- scripts/deployment/new-build-containers.sh
- scripts/deployment/new-push-containers.sh
I need to get my code into production, and we don't have any CD set up. This is the start of getting it working.
> Start working on CD

- scripts/devcontainer/_start-yugabyte
No changelog
Change ownership of /home/dark/yugabyte-data to 'dark:dark'
> Fix ownership of yugabyte-data

- .circleci/config.yml
- backend/src/LibCloud/Init.fs
- backend/src/LibService/DBConnection.fs
- scripts/deployment/new-deploy.sh
- tf/cloudrun.tf
- tf/service_env_vars.tf
Save the image ID and use gcloud to do the deploy.
> Set up deploy automatically

- backend/src/LibCloud/Init.fs
I wasn't super sure my logic was correct, so making sure.
> Tidy up test logic

- backend/experiments/BwdDangerServer/Libs/Experiments.fs
- backend/src/BuiltinCli/Libs/File.fs
- backend/src/BuiltinExecution/Libs/Base64.fs
- backend/src/BuiltinExecution/Libs/Bytes.fs
- backend/src/BuiltinExecution/Libs/Crypto.fs
- backend/src/BuiltinExecution/Libs/HttpClient.fs
- backend/src/BuiltinExecution/Libs/String.fs
- backend/src/LocalExec/Libs/Cli.fs
- backend/tests/TestUtils/TestUtils.fs
> Remove unnecessary parentheses #5171 followup

- backend/src/BuiltinExecution/Libs/Parser.fs
- backend/testfiles/execution/stdlib/parser.dark
- packages/darklang/languageTools/parser.dark
Old TODO I finally got around to
> Make ParseNode.fieldName an Option

- .circleci/config.yml
Take the recent changes to the dockerfile and use them on circleci.
> Update circleci dockerfile

- backend/src/LibCloud/Db.fs
- backend/src/LibCloud/Init.fs
- backend/src/LibService/DBConnection.fs
- backend/src/LibService/paket.references
- backend/src/LocalExec/LocalExec.fs
- tf/.terraform.lock.hcl
- tf/cloudrun.tf
- tf/darklangio.tf
- tf/service_env_vars.tf
- tf/vpc.tf
- move VPCs to terraform
- make debug info conditional and move to a more natural place in the codebase
- switch to cloud_run_v2 config, and sort/combine secrets and env vars for more readable/checkable output
> Finishing touches on yugabyte switch

- backend/testfiles/execution/stdlib/parser.dark
- backend/tests/Tests/TreeSitter.Tests.fs
- packages/darklang/languageTools/parser.dark
- packages/darklang/languageTools/writtenTypes.dark
- parser/tree-sitter-darklang/grammar.js
- parser/tree-sitter-darklang/src/grammar.json
- parser/tree-sitter-darklang/src/node-types.json
- parser/tree-sitter-darklang/src/parser.c
Changelog:
```
Area of change
- Add WrittenTypes.dark 
- Start mapping from parsedNode to WrittenTypes
```
> Add WrittenTypes.dark + Start mapping from parsedNode to WrittenTypes

- .circleci/config.yml
- Dockerfile
- scripts/build/_build-server
- scripts/devcontainer/_start-cockroach
- scripts/installers/install-gz-file
- scripts/run-backend-tests
> Fix the dockerfile

- backend/testfiles/execution/stdlib/parser.dark
- packages/darklang/languageTools/parser.dark
- packages/darklang/languageTools/writtenTypes.dark
- packages/darklang/languageTools/writtenTypesToProgramTypes.dark
- tree-sitter-darklang/grammar.js
- tree-sitter-darklang/src/grammar.json
- tree-sitter-darklang/src/node-types.json
- tree-sitter-darklang/src/parser.c
Changelog:
```
Area of change
- Expand the grammar to support type_def and update the parser accordingly
- Start adding WrittenTypes to ProgramTypes
```
> Parser updates

- .circleci/config.yml
- backend/src/LibTreeSitter/LibTreeSitter.csproj
- scripts/build/dotnet-publish-all-clis.sh
Build the clis for various platforms in CI.
> Build CLI in CI

- backend/src/Cli/Cli.fs
- backend/src/Cli/Cli.fsproj
(and remove ref from Cli to LibCloud entirely)
> Use CLI PackageManager for CLI

- scripts/publish-github-release
> Update the publish-github-release script for improved handling of failed executable uploads

- .circleci/config.yml
> Uncomment publish-github-release CI job

- .circleci/config.yml
- packages/stachu/timespan.dark
- scripts/publish-github-release
> Add attach_workspace to publish-github-release ci job

- scripts/publish-github-release
> Fix release description

- scripts/publish-github-release
> Update the publish-cli-script to remove the tag when the corresponding release is deleted

- scripts/publish-github-release
> Followup to #5253 : Add release tag validation 

- backend/src/Cli/Cli.fs
- packages/darklang/languageTools/lsp-server/lsp-server.dark
Changelog:
```
Area of change
- details
```
alternatively:
No changelog
> Allow Json.Vanilla for PM in CLI

- scripts/deployment/replace-prod-packages
- tf/service_env_vars.tf
I've already re-seeded the cluster, did the terraform dance, verified that https://packages.darklang.com/stats is OK, and terminated my personal one to ensure it's not in use.
> back to old yugabyte cluster

- .circleci/config.yml
- Dockerfile
- scripts/publish-vs-code-extension
- user-code/darklang/scripts/language-server.dark
- vscode-extension/client/src/extension.ts
Almost certainly, this will take some tinkering. Here's the groundwork, though.
> Attempt #1: Publish VS Code Extension

- .circleci/config.yml
- Dockerfile
Changelog:
```
Area of change
- details
```
alternatively:
No changelog
> reference newer base dockerfile and yugabytes version

- vscode-extension/package.json
> Increment extension version

- vscode-extension/client/package.json
- vscode-extension/package.json
> Fix the extension's icon

- docs/dev-setup/README.md
> Minor fixes to dev-setup README

- backend/testfiles/httpclient/v0/basic-get-helper-function.test
- packages/darklang/cli/bash.dark
- packages/darklang/cli/cli.dark
- packages/darklang/cli/selfUpdate.dark
- packages/darklang/cli/zipUtils.dark
- packages/darklang/cli/zsh.dark
- packages/darklang/stdlib/cli.dark
- packages/darklang/stdlib/httpclient.dark
Changelog:
```
CLI: 
- Add a darklang update command to manually update the CLI
- Add bash and zsh modules to the Cli package
- Add some Cli stdlib functions for getting the runtime host and shell
```
This PR refactors the cli's self update code
> Refactor cli self-update

- vscode-extension/client/src/extension.ts
- vscode-extension/package.json
Changelog:
```
Extension
- Add a Run Darklang Script to the extension
```
> Add run command to the extension

- packages/darklang/cli/UninstallCli.dark
- packages/darklang/cli/bash.dark
- packages/darklang/cli/cli.dark
- packages/darklang/cli/uninstall.dark
- packages/darklang/cli/zsh.dark
Changelog:
```
CLI
- Add uninstall command
```
> Add an uninstall command to the CLI

- packages/darklang/cli/uninstall.dark
> Add confirmation check before uninstalling the cli

- packages/darklang/cli/cli.dark
- packages/darklang/languageServerProtocol/common.dark
- packages/darklang/languageServerProtocol/io.dark
- packages/darklang/languageServerProtocol/language/diagnostics.dark
- packages/darklang/languageServerProtocol/lifecycle/initialize.dark
- packages/darklang/languageTools/lsp-server/initialize.dark
- packages/darklang/languageTools/lsp-server/semanticTokens.dark
- packages/darklang/languageTools/parser.dark
Changelog:
```
Extension
- Publish Diagnostics
```
> Publish Diagnostics

- packages/darklang/languageTools/lsp-server/handleIncomingMessage.dark
- packages/darklang/languageTools/lsp-server/semanticTokens.dark
> Move diagnostics publishing from semanticTokens to handleIncomingMessage

- README.md
> Update README - Dark -> Darklang

- backend/testfiles/execution/stdlib/parser.dark
- packages/darklang/languageTools/parser.dark
- packages/darklang/languageTools/semanticTokens.dark
- packages/darklang/languageTools/writtenTypesToProgramTypes.dark
- tree-sitter-darklang/grammar.js
- tree-sitter-darklang/src/grammar.json
- tree-sitter-darklang/src/parser.c
- user-code/darklang/scripts/sample-for-testing-extension.dark
Changelog:
```
- Expand the grammar to support Floats
```
> Update the grammar to support floats

- backend/testfiles/execution/cloud/_events.dark
Gutting these for now. I've added an item in #5333 to follow up on this when the time comes. Tackling this in the meantime feels like it'd be a distraction.
> Disable flaky queue tests

- backend/src/LocalExec/DarkPackagesDataIngest.fs
I'm not sure why the "insert into DB via batches in transactions" strategy wasn't working, but I tried many fixes and wasn't successful.
So, this takes another approach: insert them all at once via COPY rather than INSERTs, after manually CSV-ifying the records.
This seems to work pretty well, doesn't take longer than our previous strat, and isn't flaky.
This "ingest" strategy in general is temporary, so I'm not worried about the scalability of this solution.
> fix package ingest flakiness

- .circleci/config.yml
Also some picky reordering of the written jobs in .circleci/config.yml
> Tidy CI build dependency graph

- backend/testfiles/execution/stdlib/base64.dark
- backend/testfiles/execution/stdlib/dict.dark
- backend/testfiles/execution/stdlib/httpclient.dark
- backend/testfiles/execution/stdlib/int8.dark
- backend/testfiles/execution/stdlib/parser.dark
- backend/testfiles/execution/stdlib/uint128.dark
- packages/darklang/cli/cli.dark
- packages/darklang/cli/local-install/install.dark
- packages/darklang/cli/local-install/uninstall.dark
- packages/darklang/languageTools/nameResolver.dark
- packages/darklang/prettyPrinter/programTypes.dark
- packages/darklang/prettyPrinter/runtimeTypes.dark
> Misc fixes (package refs, CLI install, pretty-printing, etc)

- backend/testfiles/execution/stdlib/html.dark
- packages/darklang/stdlib/html.dark
> Make HTML Tag Attributes Optional

- backend/testfiles/execution/stdlib/html.dark
- packages/darklang/stdlib/html.dark
> Apply self-closing tags only to void elements

- backend/testfiles/execution/stdlib/html.dark
- packages/darklang/stdlib/html.dark
> Fill in more helper functions for common Html tags

- backend/src/BuiltinExecution/Libs/Parser.fs
- backend/testfiles/execution/stdlib/parser.dark
- packages/darklang/languageTools/lsp-server/handleIncomingMessage.dark
- packages/darklang/languageTools/parser/cliScript.dark
- packages/darklang/languageTools/parser/core.dark
- packages/darklang/languageTools/parser/expr.dark
- packages/darklang/languageTools/parser/functionDeclaration.dark
- packages/darklang/languageTools/parser/identifiers.dark
- packages/darklang/languageTools/parser/typeDeclaration.dark
- packages/darklang/languageTools/parser/typeReference.dark
> Rename sourceRange to range

- packages/darklang/languageTools/parser/typeDeclaration.dark
- packages/darklang/languageTools/semanticTokens.dark
- packages/darklang/languageTools/writtenTypes.dark
- packages/darklang/languageTools/writtenTypesToProgramTypes.dark
- tree-sitter-darklang/grammar.js
- tree-sitter-darklang/src/grammar.json
- tree-sitter-darklang/src/node-types.json
- tree-sitter-darklang/test/corpus/exhaustive/type_decls.txt
No changelog
- Capture the ;s separating the record fields 
- Some renaming for clarity
> Capture Record Field Separators

- backend/testfiles/execution/cloud/db.dark
- packages/darklang/stdlib/db.dark
> Create stdlib wrappers for built-in db functions

- tree-sitter-darklang/grammar.js
- tree-sitter-darklang/src/grammar.json
- tree-sitter-darklang/test/corpus/exhaustive/type_refs.txt
> Tree-sitter grammar: refactor fn_type_reference 

- backend/src/LibExecution/Interpreter.fs
In the most recent PR, I had a few changes I wanted to make, but saved them for a (this) follow-up PR
> no-op interpreter cleanup

- backend/src/BuiltinCliHost/Libs/Cli.fs
- backend/src/BuiltinDarkInternal/BuiltinDarkInternal.fsproj
- backend/testfiles/execution/stdlib/parser.dark
- backend/tests/TestUtils/TestUtils.fsproj
- backend/tests/Tests/Tests.fsproj
- packages/darklang/languageTools/parser/cliScript.dark
- packages/darklang/languageTools/writtenTypes.dark
- packages/darklang/languageTools/writtenTypesToProgramTypes.dark
> Minor cleanup and tidying

- backend/tests/Tests/NewParser.Tests.fs
- tree-sitter-darklang/grammar.js
- tree-sitter-darklang/src/grammar.json
- tree-sitter-darklang/src/node-types.json
- tree-sitter-darklang/test/corpus/exhaustive/type_decls.txt
> Tree-sitter-darklang: update the grammar to support multi-line records

- backend/testfiles/execution/stdlib/semanticTokenization.dark
- backend/tests/Tests/NewParser.Tests.fs
- packages/darklang/languageTools/parser/core.dark
- packages/darklang/prettyPrinter/programTypes.dark
- tree-sitter-darklang/grammar.js
- tree-sitter-darklang/src/grammar.json
- tree-sitter-darklang/src/node-types.json
- tree-sitter-darklang/test/corpus/exhaustive/constant_decls.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/Enum.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/fn_calls.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/let_expr.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/list.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/match.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/pipe.txt
- tree-sitter-darklang/test/corpus/exhaustive/module_decls.txt
> Refactor the grammar to support only tuple-style Enum literals

- packages/darklang/languageTools/parser/expr.dark
- packages/darklang/languageTools/parser/identifiers.dark
- packages/darklang/languageTools/semanticTokens.dark
- packages/darklang/languageTools/writtenTypes.dark
- packages/darklang/languageTools/writtenTypesToProgramTypes.dark
- tree-sitter-darklang/grammar.js
- tree-sitter-darklang/src/grammar.json
- tree-sitter-darklang/src/node-types.json
- tree-sitter-darklang/test/corpus/exhaustive/cli_scripts.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/constant.txt
- tree-sitter-darklang/test/corpus/exhaustive/fn_decls.txt
> Misc parser fixes

- backend/src/LibExecution/ProgramTypesToDarkTypes.fs
- backend/tests/Tests/NewParser.Tests.fs
- packages/darklang/languageTools/nameResolver.dark
- packages/darklang/languageTools/parser/core.dark
- packages/darklang/languageTools/parser/expr.dark
- packages/darklang/languageTools/parser/matchPattern.dark
- packages/darklang/languageTools/parser/pipeExpr.dark
- packages/darklang/languageTools/writtenTypesToProgramTypes.dark
No changelog
Misc parser refactors and fixes
> More parser fixes

- backend/src/LibTreeSitter/LibTreeSitter.fsproj
- scripts/build/build-release-cli-exes.sh
- scripts/build/build-tree-sitter.sh
> Build the darklang exe for Windows

- backend/src/LibTreeSitter/LibTreeSitter.fsproj
- scripts/build/build-parser
> Fix build-cli step again

- backend/src/BuiltinCli/Libs/Execution.fs
- backend/src/LibExecution/PackageIDs.fs
- packages/darklang/cli/cli.dark
- packages/darklang/cli/local-install/README.md
- packages/darklang/cli/local-install/install.dark
- packages/darklang/cli/local-install/main.dark
- packages/darklang/cli/local-install/uninstall.dark
- packages/darklang/github.dark
- packages/darklang/languageTools/parser/cliScript.dark
- packages/darklang/stdlib/cli/host.dark
- packages/darklang/stdlib/cli/powershell.dark
Changelog:
```
CLI
- Implement CLI installation, update, and uninstallation on Windows
```
> Get the CLI to work on Windows 

- backend/src/BuiltinCli/Libs/Execution.fs
- backend/testfiles/execution/language/custom-data/constants.dark
- packages/darklang/languageServerProtocol/documentSync/textDocument.dark
- packages/darklang/languageTools/lsp-server/diagnostics.dark
- packages/darklang/languageTools/lsp-server/docSync.dark
- packages/darklang/languageTools/lsp-server/handleIncomingMessage.dark
- packages/darklang/languageTools/lsp-server/hoverInformation.dark
- packages/darklang/languageTools/lsp-server/semanticTokens.dark
- packages/darklang/languageTools/parser/cliScript.dark
- packages/darklang/languageTools/writtenTypesToProgramTypes.dark
- packages/darklang/prettyPrinter/programTypes.dark
- packages/darklang/prettyPrinter/runtimeTypes.dark
- user-code/darklang/scripts/sample-for-testing-extension.dark
> runtime rewrite follow-ups

- backend/src/BuiltinCliHost/Libs/Cli.fs
- packages/darklang/cli/cli.dark
> Pretty-print cliExecuteFunction error messages

- backend/src/BuiltinExecution/Libs/LanguageTools.fs
- backend/tests/Tests/NewParser.Tests.fs
- packages/darklang/languageTools/lsp-server/diagnostics.dark
- packages/darklang/languageTools/nameResolver.dark
- packages/darklang/prettyPrinter/programTypes.dark
> Better error message when sending diagnostics + small fixes

- backend/src/LibTreeSitter/LibTreeSitter.fsproj
> Fix CLI issues with running functions and scripts on macOS

- packages/darklang/languageTools/lsp-server/docSync.dark
- packages/darklang/stdlib/cli/unix.dark
> more cli fixes

- scripts/deployment/replace-prod-packages
- scripts/devcontainer/_vscode-post-start-command
- vscode-extension/README.md
> misc. tidyings

- backend/tests/Tests/NewParser.Tests.fs
- packages/darklang/languageTools/lsp-server/hoverInformation.dark
- packages/darklang/languageTools/parser/expr.dark
- packages/darklang/languageTools/semanticTokens.dark
- packages/darklang/languageTools/writtenTypes.dark
- packages/darklang/languageTools/writtenTypesToProgramTypes.dark
- packages/darklang/prettyPrinter/programTypes.dark
- packages/darklang/prettyPrinter/runtimeTypes.dark
- tree-sitter-darklang/test/corpus/exhaustive/exprs/Enum.txt
- tree-sitter-darklang/test/corpus/exhaustive/exprs/Record.txt
- tree-sitter-darklang/test/corpus/exhaustive/type_decls.txt
> Handle type arguments for Enums and Records in the parser and LSP

- backend/testfiles/execution/stdlib/list.dark
- packages/darklang/cli/cli.dark
- packages/darklang/cli/local-install/install.dark
- packages/darklang/cli/local-install/main.dark
- packages/darklang/cli/local-install/uninstall.dark
- packages/darklang/github.dark
- packages/darklang/languageServerProtocol/lifecycle/initialize.dark
- packages/darklang/languageTools/lsp-server/hoverInformation.dark
- packages/darklang/languageTools/parser/constantDeclaration.dark
- packages/darklang/languageTools/parser/core.dark
- packages/darklang/languageTools/parser/expr.dark
- packages/darklang/languageTools/parser/functionDeclaration.dark
- packages/darklang/languageTools/parser/identifiers.dark
- packages/darklang/languageTools/parser/matchPattern.dark
- packages/darklang/languageTools/parser/typeDeclaration.dark
- packages/darklang/languageTools/parser/typeReference.dark
- packages/darklang/languageTools/programTypes.dark
- packages/darklang/languageTools/semanticTokens.dark
- packages/darklang/languageTools/writtenTypes.dark
- packages/darklang/prettyPrinter/programTypes.dark
- packages/darklang/stdlib/list.dark
> Refactors - match patterns grouping

- .gitignore
- backend/src/BuiltinCliHost/Libs/Cli.fs
- backend/src/BuiltinExecution/Libs/NoModule.fs
- backend/src/DvalReprDeveloper/DvalReprDeveloper.fs
- backend/src/DvalReprDeveloper/DvalReprDeveloper.fsproj
- backend/src/LibExecution/Execution.fs
- backend/tests/Tests/NewParser.Tests.fs
- tree-sitter-darklang/grammar.js
- tree-sitter-darklang/src/grammar.json
- tree-sitter-darklang/src/node-types.json
- tree-sitter-darklang/test/corpus/exhaustive/exprs/match.txt
> Replace IDs with names in error messages

- .roo/rules/rules.md
Extracting this PR out of #5463.
> add initial .roo config

- packages/darklang/_modelContextProtocol/README.md
- packages/darklang/_modelContextProtocol/common.dark
- packages/darklang/_modelContextProtocol/io.dark
- packages/darklang/_modelContextProtocol/lifecycle/initialize.dark
- packages/darklang/_modelContextProtocol/resources/resources.dark
- packages/darklang/_modelContextProtocol/tools/tools.dark
- packages/darklang/_modelContextProtocol/tracing.dark
- packages/darklang/languageTools/_mcp-server/README.md
- packages/darklang/languageTools/_mcp-server/handleIncomingMessage.dark
- packages/darklang/languageTools/_mcp-server/initialize.dark
- packages/darklang/languageTools/_mcp-server/mcp-server.dark
> Sketch MCP server infra+impl (commented)

- packages/darklang/languageTools/parser/constantDeclaration.dark
- packages/darklang/languageTools/parser/identifiers.dark
- packages/darklang/languageTools/parser/matchPattern.dark
- packages/darklang/languageTools/parser/moduleDeclaration.dark
- packages/darklang/languageTools/parser/pipeExpr.dark
- packages/darklang/languageTools/parser/typeDeclaration.dark
- packages/darklang/languageTools/runtimeErrors.dark
- packages/darklang/languageTools/runtimeTypes.dark
- packages/darklang/languageTools/writtenTypes.dark
- packages/darklang/stdlib/alt-json.dark
- packages/darklang/stdlib/dict.dark
- packages/darklang/stdlib/html.dark
- packages/darklang/stdlib/httpclient.dark
- packages/darklang/stdlib/list.dark
- packages/darklang/stdlib/tuple2.dark
- packages/darklang/stdlib/tuple3.dark
> Parser Improvements Followups

- packages/darklang/cli/cli.dark
- packages/darklang/languageTools/lsp-server/treeView.dark
No changelog
Please don't merge #5474 should be merged first
https://github.com/user-attachments/assets/24d2d065-0a36-4438-8ca3-4261c6a1180d
> VSCode Extension: make tree view work

- CODE-OF-CONDUCT.md
> Update code of conduct

- packages/darklang/cli/update.dark
> follow-ups to command history nav

- .gitignore
- Dockerfile
- packages/darklang/cli/integrationTests/.gitignore
- packages/darklang/cli/integrationTests/README.md
- packages/darklang/cli/integrationTests/integrationTests.dark
- packages/darklang/cli/integrationTests/record-failure.dark
- packages/darklang/cli/integrationTests/run-integration-tests.dark
- packages/darklang/cli/integrationTests/test-config.dark
- packages/darklang/cli/integrationTests/test-framework.dark
- packages/darklang/cli/integrationTests/test-utils.dark
- packages/darklang/cli/integrationTests/vhs-recorder.dark
- packages/darklang/stdlib/cli/unix.dark
> Add CLI integration tests

- packages/darklang/cli/init.dark
- packages/darklang/cli/model.dark
- packages/darklang/cli/render.dark
- packages/darklang/cli/update.dark
- Handle left/right arrow keys for character-by-character movement
- Support text insertion and deletion at cursor position
> Implement left/right arrow navigation in CLI prompt

- packages/darklang/cli/command.dark
- packages/darklang/cli/completion.dark
- packages/darklang/cli/init.dark
- packages/darklang/cli/model.dark
- packages/darklang/cli/msg.dark
- packages/darklang/cli/render.dark
- packages/darklang/cli/update.dark
Add CLI auto-completion support
https://github.com/user-attachments/assets/d4ade356-f4cc-4c90-9b59-17de854cd659
> CLI: implement tab-completion with context-aware suggestions

- packages/darklang/languageTools/lsp-server/fileSystemProvider.dark
- packages/darklang/languageTools/lsp-server/treeView.dark
- vscode-extension/client/src/ServerBackedTreeDataProvider.ts
- vscode-extension/client/src/extension.ts
- vscode-extension/package.json
https://github.com/user-attachments/assets/381cf051-74fb-4681-be4d-4690b0c36c9f
tooltip
https://github.com/user-attachments/assets/a8608a01-5d6b-40b4-a270-0c7d9b6736fe
> Add VSCode tree view icons and full module viewing support

- packages/darklang/cli/old_notes/README.md
- packages/darklang/cli/old_notes/_command.dark
- packages/darklang/cli/old_notes/_model.dark
- packages/darklang/cli/old_notes/_msg.dark
- packages/darklang/cli/old_notes/_render.dark
- packages/darklang/cli/old_notes/_update.dark
- packages/darklang/cli/old_notes/commandHelpers/_view.dark
I've had some notes locally that have been in my way; just committing them to be reviewed+deleted at some later date.
> commit some CLI notes
